### ISSUE TITLE
【ブログ】必須入力未入力箇所がある状態で「一時保存」ボタンを押すと他の入力値がぶっ飛ぶ

### ISSUE THREAD

**Issue by osws-makino** [opensource-workshop/connect-cms#1035]
## 概要
ブログで、例えばタイトルを入力し忘れた状態で、本文を入力し「一時保存」等のボタンを押すと
まっさらな新規投稿画面に飛んでしまい、今まで入力した分が消える。

## 実行環境
OS：Windows10
ブラウザ：Microsoft Edge

## 再現手順

1. ブログの「新規登録」ボタンを押す
2. 本文のみ入力
3. 「一時保存」ボタンを押す
4. 初期画面に戻る
5. 心が折れる

**Comment by osws-makino** [comment]
登録確定ボタンでは再現せず。
一時保存ボタンのみ。

**Comment by akagane99** [comment]
あら？最近どっかで直したかも。

**Comment by akagane99** [comment]
@osws-makino 
11/10に修正したみたい。
https://github.com/opensource-workshop/connect-cms/commit/9c9448c04b8451f6eccd0af2e15ea2bfcc47b505

公式サイト適用済みだから、確認してみてー。

**Comment by osws-makino** [comment]
公式サイトでも……消えますね、まだ。

**Comment by akagane99** [comment]
おっと失礼。公式サイト最新でなかったわ。
最新にして、バグ解消したの確認しました。
