### ISSUE TITLE
ヘッダーバーのColor schemes

### ISSUE THREAD

**Issue by nagasheep** [opensource-workshop/connect-cms#104]
navbar-dark など、管理画面で選択できるように。
もしくは、テーマにするか。

**Comment by akagane99** [comment]
サイト管理>サイト基本設定から、ヘッダーバーの背景色を設定できるようになっていました。
クローズします。
![Uploading 6630B2C7-F9EB-4FB7-A02E-AB6FEC30DCE8.jpeg…]()
