### ISSUE TITLE
【データベース検索】空白行が表示される

### ISSUE THREAD

**Issue by gakigaki** [opensource-workshop/connect-cms#1060]
## 概要

ページングのあるデータベース検索で途中以降に空白行が表示されています。

## 実行環境

Connect-CMS公式サイト
https://connect-cms.jp/

## 再現手順

公式サイトの機能テストページより確認できます。
https://connect-cms.jp/test/database_search?frame_204_page=9#frame-204

## スクリーンショット

![image](https://user-images.githubusercontent.com/32890286/147540937-5f51dcfe-1ec5-4288-b952-d403e19f6f0d.png)
このページ以降、すべて空白行が表示されます。

**Comment by osws-makino** [comment]
原因：
データベース検索の設定が「全て表示する」になっていたから。
![image](https://user-images.githubusercontent.com/34463938/147543402-25e98a28-3efc-4ebb-897c-33e0b19e4076.png)

この場合、サイト上にある全てのＤＢが対象となる。
しかし、抽出項目がない為、空行として表示されている。

抽出項目が１件もヒットしない場合は、表示しないようにするなどの処理が必要と思われる。

**Comment by osws-makino** [comment]
こちらの件は、要望の方に転記してこちらのissueはクローズしますね。

**Comment by osws-makino** [comment]
こちらに要望として出しておきました。
https://github.com/opensource-workshop/connect-cms-ideas/issues/115
