### ISSUE TITLE
【新着プラグイン】未ログイン時、メンバーシップページ＆ログインユーザーのみページに配置されたプラグインの更新情報が表示される

### ISSUE THREAD

**Issue by osws-makino** [opensource-workshop/connect-cms#1061]
## 概要

- 未ログイン時、メンバーシップページ＆ログインユーザーのみページに配置されたプラグインの更新情報が表示される
そのままそのタイトルをクリックすると、403 Forbidden. （権限がありません）と表示される
![image](https://user-images.githubusercontent.com/34463938/147540595-66f8d12c-8518-4eb2-b2da-15507f3ffc06.png)

- 未ログイン時、メンバーシップページ＆ログインユーザーのみページのサムネイルが、禁止マークになる
![image](https://user-images.githubusercontent.com/34463938/147540641-304df1e0-cacb-437b-a43f-80277afc7836.png)

## 実行環境
2021/12/28時点ソースコード

## 再現手順

1. ページAにブログを配置する
2. トップページ等誰でも見えるページに新着プラグインを配置し、ブログの更新情報を表示するよう設定する
3. ページAの公開設定を。メンバーシップ、またはログインユーザーに変更する

**Comment by nagasheep** [comment]
まだ、考えてない部分ですね。
パブリック部分の新着に、メンバーページのブログの新着を表示したいのかな。

**Comment by osws-makino** [comment]
未ログイン・そのアカウントにそのページへの参照権限がない場合には、表示されない方がいいのではないかと思われますね。
NetCommonsと同じ動きです。

**Comment by nagasheep** [comment]
権限を加味した状態での新着ということでは、ちょっと複雑になるので、1月にじっくりみてみますね。

**Comment by osws-makino** [comment]
そうですね。今のところ、どのお客様からも問い合わせ等は来ていないので、１月以降にでも～。

**Comment by akagane99** [comment]
既に対応済みのため、クローズします
