### ISSUE TITLE
【新着プラグイン】タイトルにタグがそのまま表示される

### ISSUE THREAD

**Issue by osws-makino** [opensource-workshop/connect-cms#1064]
## 概要
タイトルにタグがそのまま表示される

データベースを新着情報表示させるとした時、タイトル指定された項目がウィジウィグの場合、
そこに記載されたタグが新着情報にそのまま表示される

default、onerow、両方ともで発生

**Comment by akagane99** [comment]
修正しました。

## 修正プログラム

https://github.com/opensource-workshop/connect-cms/pull/1203/files
