### ISSUE TITLE
【プラグイン全般】バケツ指定がないフレームがあった時、ユーザーにも「設定がない」エラー文言が見えてしまっている

### ISSUE THREAD

**Issue by osws-makino** [opensource-workshop/connect-cms#1066]
## 概要
バケツ指定なしでフレームだけ配置している時、ログインしていないユーザーにも「設定がないよ」というエラー文言が見えてしまっている。

【同じ現象が発生するプラグイン】
- スライドショー
- データベース
- フォーム
- 掲示板
- キャビネット
- カウンター
- リンクリスト
- サイト内検索
- データベース検索
- Opac
- 開館カレンダー
- イベント
- フォトアルバム
- データ収集　※データ収集の見え方はまた違う

## スクリーンショット
![image](https://user-images.githubusercontent.com/34463938/147993552-ad7fb49c-568b-4977-bc8d-fadfc5b48fa1.png)

※データ収集
![image](https://user-images.githubusercontent.com/34463938/147994007-31a85343-b4fd-4fa6-a5f0-d1796212855f.png)

**Comment by gakigaki** [comment]
@osws-makino 
このメッセージを表示するのはbucketsを作成できるユーザー（コンテンツ管理者、プラグイン管理者）とするのはいかがでしょうか？
メッセージの内容を考慮すると上記が適切かと思います。

ブログプラグインについて、
プラグイン管理者だとログインしてもメッセージが表示されません。
件のメッセージはプラグイン管理者に表示すべきだと思います。
そのため、前述の対応で問題ないようでしたら、ブログプラグインも修正します。

**Comment by gakigaki** [comment]
@osws-makino 
データ収集プラグインについて
このメッセージは未ログインでも見えていていいように思います。
未ログインだとデータ収集プラグインは使えない、
ログインしてモデレータ以上の権限者なら使える、といった内容を表しているためです。

**Comment by osws-makino** [comment]
@gakigaki 
＞このメッセージを表示するのはbucketsを作成できるユーザー（コンテンツ管理者、プラグイン管理者）とするのはいかがでしょうか？
とても良いと思います。

＞ブログプラグインについて、
＞プラグイン管理者だとログインしてもメッセージが表示されません。
＞件のメッセージはプラグイン管理者に表示すべきだと思います。
はい、お願い致します。

＞データ収集プラグインについて
データ収集プラグインの具体的な仕様が分からないので、ちょっと変な事言ってる部分があるかもしれないですが。
何も知らないユーザーさんに見えてしまう、というのが問題だと思われます。
使う側も、知らずに間違えて配置してしまった時、ユーザーさんに見えてしまう現象が発生してしまいます。
モデレータ権限以上の人しか使えないのだとしたら、モデレータ以上の権限を持つ人しか見えないようにするのが、ユーザーさんに親切なのかな、と思いました。

**Comment by gakigaki** [comment]
@osws-makino 
メンバーシップページも参照権限がない場合、同じようなメッセージが表示されます。
これのフレームバージョンと考えると、データ収集プラグインのメッセージは違和感なくなるかもしれないです。

<img width="382" alt="image" src="https://user-images.githubusercontent.com/32890286/152075269-6a6b7fb1-77ca-4eb5-b529-840b62a8cd37.png">

**Comment by osws-makino** [comment]
@gakigaki 
だとすると、メッセージを変えた方がいいかもしれませんね。
メンバーシップのように「利用権限がありません」的な感じで。

**Comment by osws-makino** [comment]
@gakigaki 
上が長いので結論だけ。

- 未ログインのただサイトを訪れる人にも見せるエラー文言であれば、詳細情報を出さずある程度不親切ではあるもの「見る権限ないよ」的なある程度不親切なメッセージの方が、逆に混乱を招かない。
- 未ログインのただサイトを訪れる人にも見せるエラー文言であれば、今のままでＯＫ

もし、運営者にエラー詳細を伝える意味のエラー文言であるのなら、サイト運営者しか見えない部分に解説等を入れる方が親切だと思います。

（やっぱり長い……

**Comment by osws-makino** [comment]
あ、もしかしたら、ここらへん他の人も巻き込んで、ＵＩの要検討事項かもしれませんね。

**Comment by osws-makino** [comment]
```@can('frames.edit',[[null, $frame->plugin_name, $buckets]])```

こういう小ネタ、どっかにまとめておきたい……
作る上で超便利。

**Comment by gakigaki** [comment]
データ収集プラグインのメッセージはこのissueの内容と違ってくるので、別issueにしましょう！

当issue：バケツ配置を促すメッセージ
データ収集プラグイン：利用権限を確認するメッセージ

**Comment by gakigaki** [comment]
データ収集以外のプラグインに関しては対応完了、masterマージ済みです。
データ収集のメッセージについては、 #1112 にて別途検討します。
