### ISSUE TITLE
【フォトアルバム】フォトアルバムのファイルへのURLがおかしい

### ISSUE THREAD

**Issue by osws-makino** [opensource-workshop/connect-cms#1088]
## 概要
ディレクトリインストールされているConnect-CMSのフォトアルバムに
写真や動画をアップすると、ディレクトリ名が入らないURLになってしまい、写真や動画が表示されない。

例：Connect-CMSへのURL　https://test.xxxxxx.jp/connect-cms/
の場合
フォトアルバムのファイルへのURLが
https://test.xxxxxx.jp/file/123
になってしまう。

**Comment by nagasheep** [comment]
失礼。
修正します。

**Comment by nagasheep** [comment]
修正完了。
git pull で最新取り込んでください。
