### ISSUE TITLE
「タブ」プラグインで、DBプラグイン・フォトアルバムプラグインを管理する際の不具合と思われます

### ISSUE THREAD

**Issue by dreamer9999** [opensource-workshop/connect-cms#1092]
## 概要

「タブ」プラグインで、

・「データベース」プラグインの一覧表示のあと、詳細ボタンをクリックすると、詳細画面が出ないで
　「タブ」の先頭ページに戻る。
　　※　「タブ」の先頭ページに戻ったあと、確認すると、詳細画面が出ている

・「フォトアルバム」も同様に、アルバムをクリックすると、写真が出ないで、
　「タブ」の先頭ページに戻る。
　　※　「タブ」の先頭ページに戻ったあと、確認すると、写真が出ている

## 実行環境

OS: windows8.1
ブラウザ: Brave
Connect-CMS: 2022/01/21 git pull
php version: 7.3.0 

## 再現手順

下記サイトで、再現確認できます。
https://dreamer.cfbx.jp/contest3/

**Comment by kousei86** [comment]
タブの挙動については「そういうもの」のようです。
　
参考： **他のページからのアクセス時に特定のタブコンテンツを開く方法**
https://techmemo.biz/javascript/tab-direct-link/
→「通常、他のページからタブが設置されたページにアクセスすると、1つ目のタブがアクティブな状態になります。」
　
－－－
初期表示の「固定記事」、「データベース」の［詳細］、「フォトアルバム」の中身は
それぞれURLが異なるため、違いとして使えそうな文字列を確認した後、
Java Script か JQuery で
　
（１）「現在のURL」を取得する
（２） もし「現在のURL」に【 他と区別できる文字列 】を含むなら
　　　　・初期表示のタブ「#tab_X a」のCSSクラスから「active」を削除する
　　　　・見せたいタブ「#tab_Y a」のCSSクラスに「active」をつける
　
のような動きを該当ページに付けたらよいのではないかと思います。
（ユーザーには見えない固定ページの中の〈script〉〈/script〉ようなかたちで）
　
　
［参考］
https://www.delftstack.com/ja/howto/jquery/how-to-get-current-url-in-jquery/
https://techmemo.biz/javascript/tab-direct-link/

**Comment by dreamer9999** [comment]
kousei86様、お久しぶりです。
タブ挙動の仕様なんですね、ご説明頂いた内容は、私にとり難しく、時間をかけて調べていこうと思います。
いつもありがとうございます。

**Comment by Sasaki-EddyK** [comment]
横からすみません。
タブでの使用方法の問題ではと思いますがいかがでしょうか。

kousei86さんが言われているように、タブを使用しているページを初期表示した場合、タブの１つ目のコンテンツが表示されるのは問題ないと思います。これがページのリロードとの区別がつかないために起こっている事象と考えられると思います。

タブで使用するコンテンツとしては、「データベース」とか「フォトアルバム」での「詳細」などがあるコンテンツには不向きではと考えます。
このようなコンテンツ（「データベース」「フォトアルバム」）は別途他のページにおきタブで使用するのは、そのコンテンツに対する新着情報をおかれてはと考えます。
そうすれば、新着の特定のものを選択すれば、実際に掲載しているコンテンツのページに飛び、なおかつその詳細を表示されるのではと想像します。

いかがでしょうか。

**Comment by dreamer9999** [comment]
EddyK さん、お久しぶりです。
地味ですが、代替案は内部リンクを使うことでしょうね
[https://dreamer.cfbx.jp/contest3/](https://dreamer.cfbx.jp/contest3/)
EddyK さんのアドバイスも、今後、試してみます。

**Comment by dreamer9999** [comment]
kousei86様　Sasaki-EddyK様

お忙しい中、アドバイスをありがとうございます。

この件、今後実装できたらいいな、という思いで、提案に転記させていただこうと思います。

このissueはcloseさせていただきます。
