### ISSUE TITLE
ページ作成画面（＝ページの全体設定画面）の「クラス」の影響範囲

### ISSUE THREAD

**Issue by kousei86** [opensource-workshop/connect-cms#1106]
私の思い違いかもしれないのですが、確認させて下さい。
　
－－－－－－－－
　
（１）システム管理者でログイン後、「ページ管理」→「ページ登録」より、
　　　ページ全体の設定をし、一番下の「クラス名」に「abcdefg」と書いた。
　
![page-class1](https://user-images.githubusercontent.com/82799412/151688744-2bfc108c-4848-4c4b-8b31-a83df7580f35.png)
　
　
　
（２）CSSで「クラス abcdefg は背景を緑にする（ background-color: green;  ）」と指定した。
　
　
（３）反映を確認すると、タブメニューの該当ページへのリンク領域の背景だけが緑色になった。（非アクティブ時の背景）
　
![page-class2](https://user-images.githubusercontent.com/82799412/151688745-fd56927a-0173-455c-9bb1-b5b3f1eb643a.png)
　
　
　　　なお、ページ登録で「abcdefg」のクラスを記述した**ページの背景は緑色になっていない**。
　　　該当ページでのメニューは「アクティブ」であるため、別の色（灰色）で上書きされているようだ。
　
　　
（４）ソースコードを検索すると、確かに「メニューリンク」の**ところだけ**に「abcdefg」の文字が見つかった。
　　　〈li class="nav-item abcdefg"〉
　
![page-class3](https://user-images.githubusercontent.com/82799412/151688746-527c18f0-0429-42d6-8d40-799695d4b875.png)
　
　
－－－－－－－－－
　
ページ登録画面でクラスを指定すると、ページ全体に影響をもつCSSクラス 〈**body class**="〇〇 **abcdefg**"〉を適用できると思っていたのですが、これは勘違いでしょうか？
お忙しいところ、申し訳ございません。
　
使用Connect-CMS：　2022年1月30日 （update）
　
－－－－－
（追記）
Connect-CMSを新しくインストールしましたが、同様でした。
default型メニューで（３）と（４）は起こらず、タブ型メニューの時に起こりました。

**Comment by nagasheep** [comment]
こんにちは。
永原です。

この件、社内でも話題になったことがありました。
・ページ全体に設定するセレクタ（クラス名）欲しいですよね。
・既存サイトへの影響は避けたい。
・なかなか時間が取れない（作業もだけど、そもそも考えるのに）
という状況です。

以上、言い訳だけですが。(笑)

**Comment by kousei86** [comment]
お返事ありがとうございます。
　
－－－－－－－
　
公式サイトの機能解説にある「ページ管理」ページにおいて、
「クラス名はページのbody に付与されます。オリジナルテーマを作成する際に使用することを想定しています。」と書かれています。
https://connect-cms.jp/manual/manager/page
　
そのため、元々〈 body class="ページ名 " 〉のclassに追加されるようにプログラムされており、
（この記憶に自信はないのですが）以前はそうなっていたような気がします。
　
ということで、「出てくるべきところに出てきていないのでは」と訝しむところです。
もちろん、社内検討中のため、そのようにしているのかもしれません。
　
－－－－－－－
　
また、ページ管理のclassに書いた「abcdefg」が、
なぜかタブメニューの〈li class="nav-item"〉に追加されて出現しているように見えます。
　
よって、「意図しないところに出てきているのでは」と訝しむところです。
実は意図があることかもしれないので、確認をお願いした次第です。

**Comment by nagasheep** [comment]
以前、そうなっていたかどうか。の部分なんですが、
Githubで該当のコードの履歴を追いかけると、確認できると思うのです。
とりあえず、その情報だけ返信しますね。

**Comment by kousei86** [comment]
【 /resources/views/layouts/app.blade.php 】の 203行目：
　<body class="@if(isset($page)){{$page->getPermanentlinkClassname()}}@endif {{ $body_optional_class }}">
の「$body_optional_class」から遡り、
183行目：
　$body_optional_class = Configs::getConfigsRandValue($cc_configs, 'body_optional_class');
の$body_optional_classの中身が「 "" 」でした。
（ → 183行目の次にvar_dumpを置いて調べた：［  string(0) "" ］）
　
－－－－
そして、183行目の後ろに自分で
　$body_optional_class = "abcdef"
と追加してみたら、該当ページ全体の背景は緑色になりました。
　
－－－－
そのため、「$body_optional_class に自分で入力した「abcdefg」が入っていないんだな」と思うのですが、
【 app/Plugins/Manage/PageManage/PageManage.php 】の222行目：
　$page->class                = $request->class;
から $body_optional_class に至る実際の経路については、よく分かりませんでした。

いまの私の能力ではここまでが限度です。
ご助言いただいたにも関わらず、申し訳ございません。
ご迷惑をおかけしました。

**Comment by akagane99** [comment]
> 【 /resources/views/layouts/app.blade.php 】の 203行目：
>　〈body class="@if(isset($page)){{$page->getPermanentlinkClassname()}}@endif {{ $body_optional_class }}"〉

ここの設定値はbody全体のclass指定なので、設定画面では下記のようです。
（なのでページ設定のクラスはここではないみたい。）

サイト管理＞サイト基本設定　の「bodyタグ任意クラス」

![image](https://user-images.githubusercontent.com/2756509/152460927-130760fd-918f-423d-91ff-c8a2989e80df.png)

参考まで。

**Comment by kousei86** [comment]
ご指摘ありがとうございます。
私の勘違いだったようです。失礼しました。
　
より有効な方法が見つかるまで、該当のページを表示したら
「指定の要素に特定のクラス名を付加する」というスクリプトを JQuery で作り、
「固定記事」内に詰め込んでおく方法を採ってみます。

**Comment by kousei86** [comment]
タブメニューのクラスに追加された件には触れていませんが、
なんらかの意図があるか、別に調整が入るものと思いますので、
本質問は［Close］にします。
