### ISSUE TITLE
バケツ指定がないフレームでメール設定を開くとシステムエラーとなる

### ISSUE THREAD

**Issue by gakigaki** [opensource-workshop/connect-cms#1108]
## 概要

バケツ指定がないフレームでメール設定を開くとシステムエラーとなります。
（対象プラグイン：掲示板、データベース）
システムエラーにはしないで、他ページと同様に「 選択画面から、使用する〇〇を選択するか、作成してください。」のようなメッセージを表示したほうがよいと思います。

## 実行環境

OS: windows11
ブラウザ: Chrome
Connect-CMS: 2022/02/01 git pull
php version: 7.4.27

## 再現手順

1. データベースプラグインを新規に配置する
2. フレームの歯車からメール設定をクリックする

## スクリーンショット
<img width="416" alt="image" src="https://user-images.githubusercontent.com/32890286/151905588-8a838183-6155-4629-9408-19f68736c9ff.png">
↓
<img width="579" alt="image" src="https://user-images.githubusercontent.com/32890286/151905613-5409df16-47e2-4482-8c09-45c235deea1c.png">

**Comment by akagane99** [comment]
以下で対応しました。

## 修正プログラム

https://github.com/opensource-workshop/connect-cms/pull/1052/commits/b24f38089a731c68bbdff49760346bb8ca93e372
