### ISSUE TITLE
【データ収集】権限なしのメッセージを変更すべきでしょうか

### ISSUE THREAD

**Issue by gakigaki** [opensource-workshop/connect-cms#1112]
#1066 から議論が派生したため、別のissueに切り出します。

![image](https://user-images.githubusercontent.com/32890286/152078174-28ef5f30-8ca5-4fef-b9fe-dcbde1ef5bb9.png)

データ収集プラグインを参照する権限がない場合、上記のメッセージが表示されます。
このメッセージを変更すべきか、変更する場合はどのようなメッセージがよいかご意見を頂戴したいです。

- 変更したほうが良い
  - 詳細情報を出さずある程度不親切ではあるもの「見る権限ないよ」的なある程度不親切なメッセージの方が、逆に混乱を招かない。
  - 本来、モデレータとか編集者、とかという権限名は、管理者以外には見せてはいけないはず
  - このメッセージが出ると、ユーザーさんはサイト運営側に「じゃあ権限ください」って連絡しちゃう事がある
    - 本来、その権限を与える必要がない人であっても
- そのままで良い
  - ”現在閲覧している状態だとデータ収集プラグインは使えない”、”ログインしてモデレータ以上の権限者なら使える”とユーザーにとって十分なメッセージになっている

**Comment by akagane99** [comment]
そのまんまに１票。

・ほとんど使われてない。使う人が限定されるプラグインだから。
※ 初期に作られたプラグインだから、そんなに考えられてないよなぁ。
・データ収集は、データためて、そのデータをCSVをダウンロードするだけのシンプルなプラグインだから、基本公開ページに配置しないよなぁ。
（限定公開ページに配置して、データ収集プラグインを配置した人が使うか、その関係者数人がダウンロードする位かなぁと想像。プラグインを配置した人、ユーザ権限も含めて設定するよね、みたいな）

**Comment by osws-makino** [comment]
私が問題提起した理由
・間違えて配置してしまってそのまま放置された時、エラー文言がユーザーに見えてしまう為

↑『間違えて配置してしまって、なのに気にせずそのまま放置』という現象、かなり多いんです。
今までユーザーさんのサイトで、放置された空のフレームをごまんと見てきています。

**Comment by nagasheep** [comment]
永原が、あまり考えずに作っている分で混乱させてて申し訳ない。
権限のないユーザにどう見せるか、Connect-CMSとしての考え方、をまとめていくのは、良いことですね。
整理して考えたいです。
