### ISSUE TITLE
モジュールづくりの練習したいのですが、そろそろ可能でしょうか

### ISSUE THREAD

**Issue by zanjibar** [opensource-workshop/connect-cms#112]
結構できているので、モジュールづくりしてみようと思うのですが、そろそろ可能でしょうか？
モジュールのインストーラなどまだまだだと思いますが、どうでしょうか？
年内まったほうがいいでしょうか？

**Comment by nagasheep** [comment]
永原です。

モジュール作りの要望、ありがとうございます。

いま、権限周りの実装中です。
(いまのは権限は仮の状態)
それができたら、モジュール作りの資料をまとめたいです。
10月には、権限周りも実装したいと思っているので、もう少しお待ちください。
資料作る際は、連絡しますので、ご協力いただければうれしいです。(^^)

**Comment by zanjibar** [comment]
１１月くらいから、モジュールづくりですね。了解。
