### ISSUE TITLE
【ブログ】designbaseテンプレートでTwitter/Facebookアイコン表示設定ONにすると記事詳細でシステムエラー

### ISSUE THREAD

**Issue by masaton0216** [opensource-workshop/connect-cms#1120]
## 概要
- 掲題の通り。
- defaultテンプレートは対応できている為、これに追従する。
https://github.com/opensource-workshop/connect-cms/commit/09a0992b7eb72cdf14906c22b7825e0c9b4ae8e4

## エラーログ
> Undefined variable: post_title (View: C:\sites\connect_cms_php_7422\htdocs\resources\views\plugins\common\twitter.blade.php)

**Comment by nagasheep** [comment]
すまん、永原がミスってたね。
