### ISSUE TITLE
xampp 以外のＯＳでの稼動状況はどうでしょうか？　ubuntu 18.04LTS にははいりますか？

### ISSUE THREAD

**Issue by zanjibar** [opensource-workshop/connect-cms#115]
いま、ubuntu 18.04LTS にいれていますが、うまく動きません。

初期データのインポートがされないようです。

**Comment by akagane99** [comment]
centos7で動きました。

seederコマンドって実行してみました？
このコマンドで初期データインポートできると思います。
```
# php artisan db:seed
```

また、インストールページにseederのコマンド書いてなかったため、記載してみました。
https://github.com/opensource-workshop/connect-cms/wiki/Install-(インストール)#initial-data-import-with-seederseederで初期データインポート

**Comment by zanjibar** [comment]
こんなエラーがでました。前途多難です。

>  SQLSTATE[HY000] [1698] Access denied for user 'forge'@'localhost' (SQL: select * from information_sch  
>   ema.tables where table_schema = forge and table_name = migrations)

**Comment by nagasheep** [comment]
まだ、そこまでインストールの準備ができていないんですよ。申し訳ない。
XAMPP 以外で動かしたい。ということですよね。
XAMPP のデータをLinux にもコピーすれば動くと思うんです。

**Comment by zanjibar** [comment]
ＰＨＰのモジュールにどんなものがはいっているかですね。

**Comment by nagasheep** [comment]
この前、amazon linux で動かしたときは、以下のオプションでインストールしたPHP で動いたんじゃなかったかなと思います。
yum install php73 php73-devel php73-mbstring php73-mysqlnd php73-xml php73-gd php73-bcmath

**Comment by zanjibar** [comment]
Larabel のログイン画面まできた
[Laravel - 192.168.33.118.pdf](https://github.com/opensource-workshop/connect-cms/files/3635494/Laravel.-.192.168.33.118.pdf)

**Comment by zanjibar** [comment]
centOS7 だと、PHP 入れ替えでしょうか？

**Comment by nagasheep** [comment]
はい。PHP5.4 では動かないのです。
PHP7.2 以降でお願いします。

**Comment by zanjibar** [comment]
ansible をつかって、ubuntu 18.04LTS 設定までいきました。
現時点で、想定ＯＳとして
ubuntu 18.04LTS
CentOS 8
amazon linux

**Comment by zanjibar** [comment]
CentOS 8 リリースされていますね。
ansible-playbook 作成中です。

**Comment by zanjibar** [comment]
個別ＯＳについてのissue をたてるのでクローズします。
