### ISSUE TITLE
block はあるのでしょうか？

### ISSUE THREAD

**Issue by zanjibar** [opensource-workshop/connect-cms#117]
ぱっとみたところ、ブロックの仕組みはないみたいなんですが、

**Comment by nagasheep** [comment]
blockとは、どういうものを指しています？
データでは、framesが画面の枠（Window）を表していて、データの塊はbuckets で管理しています。
って、これで伝わります？

**Comment by zanjibar** [comment]
ＮＣ２にあったブロックですね。管理モードになると、そこにデータ書き込めます。
今使っているシステムは、それで画面遷移を制御しています。
管理者しかアクセスできないページとか簡単につくれます。

**Comment by zanjibar** [comment]
ＮＣ２だとログインブロックとかありました。機能をもったブロックですね。

**Comment by nagasheep** [comment]
こういうことかな。
![管理機能クリック](https://user-images.githubusercontent.com/3079435/65323777-413cad00-dbe5-11e9-98c7-7544100618a4.png)
<img width="898" alt="フレーム追加" src="https://user-images.githubusercontent.com/3079435/65323787-47328e00-dbe5-11e9-9374-f5bb1e1a1e1d.PNG">

**Comment by zanjibar** [comment]
おお、いけますね。

**Comment by nagasheep** [comment]
はい。
Connect-CMSの画面作成は、ブロック方式を最初に実装しました。(^^)

**Comment by nagasheep** [comment]
では、このIssueは解決ということで、Closeしますね。
