### ISSUE TITLE
【データベースプラグイン】画像の交換（更新）ができませんでした

### ISSUE THREAD

**Issue by dreamer9999** [opensource-workshop/connect-cms#1171]
## 概要

バグに該当するかどうかは定かではないのですが、データベースプラグインの画像型への画像アップデートができませんでした。
（connect-cmsは本日の作業前にアップデートしました）

### ①初めの画面
![名前追加](https://user-images.githubusercontent.com/3895089/154668383-0e745d55-85d9-425c-ba7a-06faf632fe4d.png)

### ②新しい画像に交換する（ｽﾊﾟｹﾞﾃｨからﾎｯﾄｹｰｷに交換する）
![名前追加後、画像変更](https://user-images.githubusercontent.com/3895089/154669187-c42b7f64-a5fc-4b26-843c-f31e9c53a916.png)

### ③エラーが出ます

![エラー2](https://user-images.githubusercontent.com/3895089/154800755-fcaf1ee5-6f70-4ed3-a3d9-fdcc766376b1.png)

#### ※アップロード画像一覧

![ファイル一覧](https://user-images.githubusercontent.com/3895089/154669781-00adcdfe-d48e-4b8e-b862-4a825b1e5019.png)

**Comment by kousei86** [comment]
私のところではエラーを再現できなかったのですが（つまり、普通に画像を更新できた）、
#732 として把握はされているようです。

**Comment by dreamer9999** [comment]
kousei86 様

ありがとうございます。

上記アドバイスいただいた作業を行ってみましたが、同様のエラーが出てしまいました。
現在は、「画像型」を回避して「ウィズウィグ型」を設置して、画像を表示しています。

・現在のサイトで、他の項目は一切設定せず、「画像型」だけにして、同様作業を行うと、エラーが出ない、
・他のサイトで、他項目も設定、「画像型」も設定し、同様作業行っても、エラーが再現できなかった、

などが確認できました。

アップロードファイルを削除したらどうかな、と思いましたがよくわからずじまいでした。（「public/storage/app/uploads/1」の該当画像を削除しましたが、管理画面のアップロードファイル一覧には全画像名が残ったままだったので、元に戻し、作業中止しました）

現在のサイトは昨年4月くらいから稼働し、アップデートを繰り返しているので、何か不具合が出ているのかもしれません。現在のサイトは試運転中なので、本稼働するときは、現在のサイトを削除し、まっさらな状態で、再度サイト作成したほうがいいだろうな、と思っています。

いつも、お手数をおかけしてしまい、申し訳ございません。
いつも、ありがとうございます。

**Comment by kousei86** [comment]
サブドメイン型でインストールしても、サブディレクトリ型でインストールしても、
ご提示のエラーを再現できませんでした。

あと私に思いつく対策は、エラーが出たデータベースの公開画面・編集画面・確認画面ごとに
「ブラウザのキャッシュクリア（Windowsで  [ctrl]+[F5]）」をするぐらいでしょうか。
　
お力になれず、申し訳ございません。

**Comment by dreamer9999** [comment]
本当にありがとうございました。

**Comment by gakigaki** [comment]
@dreamer9999 
こちらまだ発生していますか？
もし発生している場合はサーバーの情報を教えていただけますか？

- サーバーのOS
- PHPのバージョン
- DBのバージョン

**Comment by dreamer9999** [comment]
バージョン1.6.2で確認しましたが、エラーが発生しませんでしたので、クローズさせていただきます。
kousei様、gakigaki様、関係者の方々に、お手数を煩わせてしまい、誠に申し訳ございませんでした。
