### ISSUE TITLE
設定情報には、コメント欄つけてほしい

### ISSUE THREAD

**Issue by zanjibar** [opensource-workshop/connect-cms#118]
設定情報や、ユーザ情報などには、コメント（備考）欄をつけてほしい。

**Comment by nagasheep** [comment]
ユーザー情報は、属性を増やせるようにするつもりです。
設定情報のコメントというのが、イマイチ、ピンとこなかったんですけど、どういうものです？

**Comment by zanjibar** [comment]
人間が読む情報だったら、なんでも、備考欄があった方がいいです。という発想です。

（例）
ユーザ情報だったら、コメント（備考欄）に、例えば、「このユーザは、テスト用なんで、本番のときは、削除のこと」と書いておくと便利だなと思っています。

そういう意味で設定ファイルは、JSON でなく、私は、Yaml つかっています。コメントを自由に書くことができます。

**Comment by nagasheep** [comment]
設定情報というのは、ファイルを想定している。ということですね。
yamlはコメント書けるんですね。
yamlの読み方など、調べてみたいと思います。
laravelの作法にも合わせたいですしね。

**Comment by nagasheep** [comment]
Laravel のconfig ディレクトリの設定ファイルはLaravel のルールに合わせてPHP。
その他、Connect-CMS で作成する設定ファイルは ini 形式にしました。
コメントも書けますしね。
https://www.php.net/manual/ja/function.parse-ini-file.php
