### ISSUE TITLE
【メール設定】がおかしな動きをする気がします

### ISSUE THREAD

**Issue by dreamer9999** [opensource-workshop/connect-cms#1189]
メール設定がおかしな動きをする気がします。

昨日新たなサイトでメール設定をしました。
1年くらい前に設定して現在、正常に動いている他のメールと同じ設定にしています。
※私の設定間違いでしたら、申し訳ございません。

**おかしな箇所**

下記の様に、laravel/.envでFromメールアドレスと差出人を設定しています。

MAIL_FROM_ADDRESS=info@XXX.com
MAIL_FROM_NAME=message

しかしながら、メール送信は出来るのですが、差出人<メールアドレス>の<メールアドレス>の部分が
hello@example.com
となります。

MAIL_FROM_ADDRESS=info@XXX.com が正常に表示されないように思えます。

**原因と推測する箇所1**

Fromアドレスは、設定はlaravel/config/mail.phpで行っているようです。

'from' => [
    'address' => env('MAIL_FROM_ADDRESS', 'hello@example.com'),
    'name' => env('MAIL_FROM_NAME', 'Example'),
],

ここの　hello@example.com　がこのまま表示されている気がします。

**素人の邪推**

　1年前と現在のシステムの何かが変わったためかなあ、、、

※私の設定間違いでしたら、本当に、申し訳ございません。

**Comment by kousei86** [comment]
先ほど（3月3日22時ごろ）にインストールしてみました。
私のところでは**正常に差出人とメールアドレスが表示されました**。
（さくらレンタルサーバー，php7.4）

MAIL_FROM_ADDRESS=info@XXX.com　の先頭に　#　が付いていたりしませんか？

**Comment by dreamer9999** [comment]
kousei86様、ありがとうございます。

現象が再現できないという事は私の何かの設定が違うのでしょうね、、
時間をおいて、再度確認してみます。

closeさせていただきます。

**Comment by kousei86** [comment]
#MAIL_FROM_ADDRESS=info@XXX.com　とした場合に再現できました。

そのため、MAIL_FROM_ADDRESS に指定したいメールアドレスが代入されていないか、代入されたとしても最後まで適用されず、
Laravelの初期状態である「hello@example.com」が使われていることが原因だと予想します。

使用環境の違いにより生じる気もしますが、私にはよく分かりません。
申し訳ございません。
