### ISSUE TITLE
nginx 対応可能？

### ISSUE THREAD

**Issue by zanjibar** [opensource-workshop/connect-cms#119]
nginx にしてほしいという人がいるかもしれません。可能でしょうか？

**Comment by nagasheep** [comment]
対応したいですね。
laravelベースなので、対応はできると思っています。
予定までは、まだまだ決められないですけど。

**Comment by zanjibar** [comment]
ansible 落ち着いたら、調べてみます。

**Comment by nagasheep** [comment]
はーい。お願いします。
