### ISSUE TITLE
opacs_books に page のカラムがない

### ISSUE THREAD

**Issue by zanjibar** [opensource-workshop/connect-cms#120]
sudo php artisan migrate
したところエラーがでました。

`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'page' in 'opacs_books' 
`

**Comment by nagasheep** [comment]
失礼。
確認します。

**Comment by nagasheep** [comment]
修正しました。
以下がミスでした。
https://github.com/opensource-workshop/connect-cms/commit/347e64f2c29bdbb6ba08e8ed7e1385c0ca0dedba#diff-d8bc849d9dfdec4a8e78f69992c3d28a

**Comment by zanjibar** [comment]
ありがとうございます。動作確認しました。
