### ISSUE TITLE
Windows + XAMPP Portable でのインストールのPHP

### ISSUE THREAD

**Issue by kousei86** [opensource-workshop/connect-cms#1206]
2022年3月12日にWindows＋XAMPPでのインストール方法が追加されたので、試してみました。
［ XAMPP Protable（ xampp-portable-windows-x64-7.4.27-2-VC15.zip ）でUSBメモリ（Fドライブ）にインストール ］

しかし、PHPもComposerもインストールしていない（ごく一般的な）私のWindows10環境では

　**（コマンドプロンプト作業）ルートディレクトリに移動**
　`cd sites\connect_cms_php_7427\htdocs`

まではできましたが、次の

　**（コマンドプロンプト作業）composer installを実行 ※Connect-CMS動作に必要な周辺プログラムのダウンロード**
　`composer install`

が、「コマンドとして認識されない」との旨で実行できませんでした。

XAMPPに同封されているPHPの実行ファイル（ \ xamppフォルダ \ **php \ php.exe** ）に向けてパスを通す操作を間に入れることで、その後の操作が可能になりました。
具体的には以下のとおりです。

－－－－－－－－－－－－－－－－－－－－－－－－－
　
【既記の手順：ルートディレクトリ htdocs に移動した後から】
　
**○ PHPへのパスを通す**
Windowsでのテキストファイルの作成（私はVS Codeを使った）または コマンドプロンプトの操作により、
下の領域のスクリプトを転記した「php.bat」というファイルを新規作成する。（ → \connect_cms_php_7427\htdocs\php.bat ）
［Fドライブを使っているため、F: で始まる］
```
@echo off
SET PHP_HOME=F:\sites\connect_cms_php_7427\php\
SET CURRENT_DIR=%~dp0
SET PATH=%PHP_HOME%

%PHP_HOME%php %*
```
　
**○ （コマンドプロンプト作業）composer.pharファイルのダウンロード**
`php  -r "eval('?>'.file_get_contents('https://getcomposer.org/installer'));"`
　
→ \connect_cms_php_7427\htdocs\composer.phar
　
　
**○ （コマンドプロンプト作業）composer installを実行 ※Connect-CMS動作に必要な周辺プログラムのダウンロード**
`php composer.phar install`
　
　
【以下、Wikiの操作手順に戻る】
**○ （コマンドプロンプト作業）APP KEY生成**
･･･ 

－－－－－－－－－－－－－－－－－－－－－－－－－

httpd.confでDocumentRootを変えた後、
Apacheを再起動させる必要がありました。

－－－　－－－

○感想１（利用者の目的に依りますが）
手順は範囲外で構いませんが、phpmyadminで**rootのパスワード変更を勧める一言**は添えてあげた方がよいと思います。
　
○感想２
「git clone」はWindowsユーザーが元から使えるものなのかなぁ？
　
－－－－－－－－－－－－－－－－－－－－－－－－－

GitHubの機能で更新を書いてリクエストをするほどの技量がありませんので、ここに記します。
お手数ですが、よろしくお願いします。

**Comment by masaton0216** [comment]
検証ありがとうございます。
抜けの指摘とても助かります。
アドバイスも含め後々、直しておきます😀

**Comment by masaton0216** [comment]
@kousei86 
ご指摘ありがとうございます。手順を修正しました。
https://github.com/opensource-workshop/connect-cms/wiki/Install-XAMPP/_compare/4c709663465b3a32ee6935769f1c78b47972c65a...d58ae3d1b201898b09ec1b7da732b84fd33580a8

お手数をおかけして恐縮ではございますが、
ご確認の上、問題がなければIssueのクローズまでよろしくお願いいたします。

**Comment by dreamer9999** [comment]
xamppのマニュアルに従ってインストールしてみました。

途中までしか進めませんでした、、、
いくつか気になったこと、、
・フォルダconnect_cms_php_7427の7427が、何か所か7422になっていました。
・httpd.confの場所が
　C:\sites\connect_cms_php_7427\apache\conf\httpd.conf　とありましたが
　C:\sites\connect_cms_php_7427\xampp\apache\conf\httpd.conf  かと思いました

エラーが出て、分からなくて、作業をやめた箇所
![エラー3](https://user-images.githubusercontent.com/3895089/158064255-e486ffc1-d9f9-47b5-9571-40ebf7abc5fd.png)

xamppがよくわからず、へんなことをやったり、言ってるかもしれませんが、私なりに気になったところを、記載させていただきました。

**Comment by kousei86** [comment]
dreamer999 様

Wikiページ初版の修正に情報を提供したことから、
それなりの責任があろうかと思いますので、私から返答を差し上げます。

－－－－－－－－－－－
（１）**・フォルダconnect_cms_php_7427の7427が、何か所か7422になっていました。**

言われて気づきました。昨日の段階で気づくべきでした。すみません。

－－－－－－－－－－－

（２）**・httpd.confの場所が
　　　C:\sites\connect_cms_php_7427\apache\conf\httpd.conf　とありましたが
　　　C:\sites\connect_cms_php_7427\xampp\apache\conf\httpd.conf かと思いました**

XAMPP Portableを展開したら「xampp」フォルダが出てくるため、
それを「connect_cms_php_7427」という名前に書き換えるか、
「connect_cms_php_7427」というフォルダを作り、その下に配置するかで、ご提示の上か下かが決まります。
おそらく数日中には「xampp」を「connect_cms_php_7427」という名前に変える方向でWikiが更新されると思います。

－－－－－－－－－－－

（３）**エラーが出て分からなくてやめた箇所**

上の２に関連し、「connect_cms_php_7427」のしたに「xampp」フォルダがある場合、
php.exeまでのパスである冒頭の「 C:sites\ ～ php\php 」は正しくは
「 C:\sites\connect_cms_php_7427**\xampp**\php\php 」ですので、
その位置に「 \xampp 」を足していただければ正しく作動するはずです。

－－－－－－－－－－－

あと、現状では「php artisan key:generate」と「php artisan migrate:fresh --seed」の冒頭にある
「php」を「C:\sites ～ php\php 」までのパスで置換して使って下さい。
（ その前の composer.phar install の部分を参考に  ）

－－－－－－－－－－－
以上、よろしくお願いします。

**Comment by masaton0216** [comment]
@dreamer9999 
@kousei86 
ご確認を頂きありがとうございます。
手順書は「その通り実行すれば誰でも再現できるべきもの」と考えていますので、
それぞれの見地からのご指摘大変ありがたいです。

手順書をさらに修正してみたので恐れ入りますがご確認頂けますと幸いです。
https://github.com/opensource-workshop/connect-cms/wiki/Install-XAMPP/_compare/d58ae3d1b201898b09ec1b7da732b84fd33580a8...7cc6e39a57217cc9ab7a9d857ea4ade5ecd9ed4a

**Comment by kousei86** [comment]
変更を確認しました。ありがとうございます。
　
－－－
ちなみに、上で示したbatファイルを作成する方法は、そのbatファイルを置いた「htdocs」フォルダにいる時だけ使え、
他のフォルダに移動し、コマンドプロンプトで「php artisan ～」と入力しても使えませんでした。
Windowsの環境変数として永続的にPHPにパスを通すような仕組みではなさそうです。
そのため、XAMPPフォルダごとを捨ててしまえば、Windowsに影響なく、元に戻せるようです。
　
「htdocs」は一般的なConnect-CMSでphpコマンドを入力するディレクトリですので、
phpコマンドで使えるようにするとUpdate操作などでそのまま使えて便利かと思いましたが、
「 C:\sites\connect_cms_php_7427\php\php 」でコマンドを使用するという判断もそれはそれで支持しますので、
さらなる改善案として主張するつもりはありません。
　
－－－
冒頭で提示した課題は可決しましたので、本issueはクローズドにします。
お世話をかけました。
