### ISSUE TITLE
Windows + XAMPP Portable でのインストールのPHP（追記）

### ISSUE THREAD

**Issue by dreamer9999** [opensource-workshop/connect-cms#1209]
Windows でのXAMPPのインストールマニュアルに従って、インストール完了しました。
その間、気が付いたことを記載させていただきます。

・「ファイル「.env.sample」をコピーして「.env」にファイル名を変更」で
　　直接フォルダ名を変更すると、下記エラーが出ました（私の環境だけかもしれませんが、、）

![エラー](https://user-images.githubusercontent.com/3895089/158302913-a9c19fb4-ba61-46d8-be61-5c4906378c3a.png)

　ここは、下記でクリアしました。
　
　【コマンドライン作業】
　C:\Users\（ユーザー名）>cp  C:\sites\connect_cms_php_7427\htdocs\.env.example   C:\sites\connect_cms_php_7427\htdocs\.env 
　
　
・wikiのconnect-cmsのアップデートマニュアル（Windows +XAMPP環境）を変更しようと思い、チャレンジしましたが、下記エラーが出てしまいました。
![エラー9](https://user-images.githubusercontent.com/3895089/158307045-5483a0a7-368b-4280-aa9a-44494a9a7a04.png)

関連
[https://github.com/opensource-workshop/connect-cms/issues/1206](https://github.com/opensource-workshop/connect-cms/issues/1206)

**Comment by kousei86** [comment]
**（１）ドットで始まるファイルが作れない**
「Windows 10 19H1Build 18342 」からドットで始まるファイルを作成できるようになりました。
https://forest.watch.impress.co.jp/docs/serial/yajiuma/1172064.html
Windows8でも「.ファイル名.」のように末尾に「 . 」をつけると作成できるようです。

**（２）openssl extension が利用できない**
php -d allow_url_fopen=1 composer.phar install --no-dev　とご入力ですが、
「Windows＋XAMPPのインストール」ページの末尾にある説明を受け、
　`C:\sites\connect_cms_php_7427\php\php -d allow_url_fopen=1 composer.phar install --no-dev
`
として読み替えて実行すれば、アップデートできるのではないかと思います。

**Comment by dreamer9999** [comment]
kousei86様
いつもありがとうございます。

（１）私、win8.1を使ってます、ご紹介頂いたサイトの最下部あたりの
「たとえば、“.gitignore.”というファイル名にすれば（「エクスプローラー」はそれを受け入れてくれます！）、末尾のドットが取り除かれて“.gitignore”になります。いずれ要らなくなる裏ワザですが、Windows 7やWindows 8.1、古いバージョンのWindows 10ではまだ有効なので、覚えておいて損はないでしょう。」が役に立ちました。
ただ、マニュアル的には、ＯＳに依らず実行できるので、コマンドライン作業を記載するのが汎用性が高い気がしました。

（２）アドバイスして頂いたコマンドを実行したら新たな下記エラーが出ました、
　　何か、この辺りはよくわからないです、、、
![エラー11](https://user-images.githubusercontent.com/3895089/158396258-a00b7c00-06df-4999-94e0-aa1a4cf435ce.png)

**Comment by kousei86** [comment]
コマンドプロンプトの操作で C:\sites\connect_cms_php_7427\htdocs\ に移動してから行うと、
実行できる気がします。

**Comment by dreamer9999** [comment]
kousei86様
いつもありがとうございます。

できました。
これをもとに、wikiのアップデートマニュアルに追記させていただこうと思います。
