### ISSUE TITLE
【ユーザー登録】ユーザー登録しようとするとエラーが出る

### ISSUE THREAD

**Issue by osws-makino** [opensource-workshop/connect-cms#1211]
## 概要
モデレータ権限でログインした状態のまま、ユーザー登録画面からユーザー登録しようとすると
「ユーザーにメソッドに対する権限がありません。」と出る。

## 再現手順
・自動ユーザー登録設定機能をONにしておく
・モデレータの権限しかもっていないユーザーでログインする
・ユーザー登録画面へ行く（※ログインしたまま）
・データを登録すると「ユーザーにメソッドに対する権限がありません。」と出る。

※でも、ユーザーの登録はちゃんと行われている。

## 事情
ユーザー管理機能は使わせたくないユーザーに、ユーザー登録だけはさせたい時がある。
なので、ログインしたまま、ユーザー登録画面を使用する事がある。
ユーザー登録自体はできているので、エラーが出ないようにして欲しい。

**Comment by akagane99** [comment]
追加検証しました。
管理権限のないユーザでログインしていると、ユーザ登録後に/manage/user に飛んでしまうため、`403 Forbidden. （権限がありません）` になっていました。
![image](https://user-images.githubusercontent.com/2756509/159082965-67b373b4-a9c6-42cd-a9fd-6adaa1db052d.png)

**Comment by gakigaki** [comment]
対応済み
