### ISSUE TITLE
テーマチェンジャー

### ISSUE THREAD

**Issue by nagasheep** [opensource-workshop/connect-cms#122]
テーマチェンジャー（テーマビューアー）の開発

**Comment by yotaca** [comment]
gitの使い方がいまいちよくわからなくて流れに乗れなくて申し訳ありません。
winが壊れていて最新版ではありませんが、ソース見てていくつか気になる点がありました。

１）タグに style="〜" 記載されているとCSSで上書きできない。
２）class="col-sm-12" だけが指定されているけど、これは col-12 でいいのでは？
３）tableタグは極力減らしてほしい。たとえば『横浜CP蔵書』のところテーブルだと、表示を組み替えが面倒なんですけど、<dl><dt><dt><dd><dd></dl>で書き出してあるとレイアウトの幅が広がると思います。

ご検討ください。

**Comment by nagasheep** [comment]
yotacaさん、コメントありがとうございます。
Github の使い方も、確認しながら進めましょう。（^^）

で、このIssue のスレッドは、「テーマチェンジャー」のスレッドなので、CSS に関する別スレッド（別 Issue）を作って欲しいです。

以下のIssue のトップページに、「New Issue」の緑のボタンがあります。
https://github.com/opensource-workshop/connect-cms/issues
手間かけて申し訳ないのですが、そっちに転記して欲しいです。

以上、お願いします。

**Comment by yotaca** [comment]
ありがとうございます。
『New Issue』作成いたしました。

**Comment by nagasheep** [comment]
テーマチェンジャーは作成済み。
