### ISSUE TITLE
【ユーザ管理】ユーザ登録後にメール通知機能の追加

### ISSUE THREAD

**Issue by akagane99** [opensource-workshop/connect-cms#1223]

**Comment by gakigaki** [comment]
@akagane99 
当issueの対応で #1221のPRにconflictsが発生しています。
衝突解消の判断がつかないため、変更内容を教えていただけますか？

**Comment by akagane99** [comment]
@gakigaki 
直したよー

**Comment by akagane99** [comment]
対応しました。

ユーザ管理画面＆ユーザ登録時にメール入力ありの時のみ、メール送信画面を開きます。

## 修正後画面
### ユーザ登録画面（メールアドレス下部にメッセージ追加）
![image](https://user-images.githubusercontent.com/2756509/160083471-51d1031f-7e49-4ca8-83b5-9cfdeac56cc6.png)

### メール送信画面（追加）
![image](https://user-images.githubusercontent.com/2756509/160083776-b1487223-3e1a-486e-8f11-878529d3df7e.png)
