### ISSUE TITLE
【ウィジウィグ】PDFアップロードがIEでできない

### ISSUE THREAD

**Issue by akagane99** [opensource-workshop/connect-cms#1267]
## 概要

・PDFのアップロードのアイコンを押下時にJSエラーで、動作しませんでした。
・画像のアップロードはできました。
・今年の６月にIEはサポート切れるため、備忘録として残しておきます。

## スクリーンショット

![image](https://user-images.githubusercontent.com/2756509/163926157-c2fafeac-e203-40e3-bc07-0a636607bc6a.png)

![image](https://user-images.githubusercontent.com/2756509/163926184-6d368257-80b4-46aa-ad3d-2f3539ca70e1.png)

## 参考：画像アップロード

JSエラーは出てましたが、アップロードできました。
![image](https://user-images.githubusercontent.com/2756509/163926364-ebf365ed-c4ae-4e44-8ecd-e8e39d149e34.png)

**Comment by gakigaki** [comment]
startsWith()がIE11で使えないようです。
https://opensource-workshop.slack.com/archives/CH7B0PP8Q/p1650346968424199?thread_ts=1650345206.389289&cid=CH7B0PP8Q

代替策を講じればIEでも動きそうです。
https://aruo.net/arbk/blog/article/techclip_determine_string_prefix_matching_by_javascript

**Comment by nagasheep** [comment]
修正しました。
IE、Edge（Chrome版）、Chrome確認済み。
マージしてよいかな？？

**Comment by akagane99** [comment]
OK！

**Comment by nagasheep** [comment]
サンキュー。マージします。
