### ISSUE TITLE
ログインのIP制限

### ISSUE THREAD

**Issue by nagasheep** [opensource-workshop/connect-cms#127]
ログインのIP制限

**Comment by zanjibar** [comment]
管理者権限のＩＰ制限もあるのでしょうか？

**Comment by nagasheep** [comment]
どうせなら、ip制限する対象（権限 or ロール）も選択できた方が良いですね。

**Comment by nagasheep** [comment]
こんな感じで実装しました。
はじめにAllow/all or Deny/all を選択できて、
詳細としてIPアドレス、権限、Allow/Deny を追加できます。
Apache のアクセス許可設定と同じ考え方です。

![Connect-CMS_ログインIPアドレス制限](https://user-images.githubusercontent.com/3079435/69008062-72d5b880-0989-11ea-9e2a-fa6008ad1854.png)
