### ISSUE TITLE
レイアウトについて

### ISSUE THREAD

**Issue by yotaca** [opensource-workshop/connect-cms#132]
レイアウトについての要望スレッド

**Comment by yotaca** [comment]
１）タグに style="〜" 記載されているとCSSで上書きできない。
２）class="col-sm-12" だけが指定されているけど、これは col-12 でいいのでは？
３）tableタグは極力減らしてほしい。たとえば『横浜CP蔵書』のところテーブルだと、表示を組み替えが面倒なんですけど、

で書き出してあるとレイアウトの幅が広がると思います。

**Comment by nagasheep** [comment]
永原です。
コメント、ありがとうございます。

> １）タグに style="〜" 記載されているとCSSで上書きできない。

すみません。見つけたら修正していきたいと思います。
具体的に、まずはここが邪魔。とかあったら言ってください。

> ２）class="col-sm-12" だけが指定されているけど、これは col-12 でいいのでは？

永原がbootstrap をまだわかっていないだけですね。
col-12 に修正します。

> ３）tableタグは極力減らしてほしい。たとえば『横浜CP蔵書』のところテーブルだと、表示を組み替えが面倒なんですけど、

table 使わずに、表を作る方法、教えて欲しいです。
まだ、CSSのスキルがその程度でして。すみません。
もしくは、修正して、プルリクエストしてもらえたらうれしいです！

**Comment by yotaca** [comment]
永原さん　ありがとうございます。

１と２の対応了解です。
３の table ですが、私は style display:table , display:table-row , display:table-cell を使用しています。
とりあえずサンプル作成しますので少々お待ちください。

**Comment by yotaca** [comment]
レイアウトのサンプルを作成しました。
もともとnucleusCMS用に作成していたので、まだ手直しは必要ですが参考にしていただけると思います。

bootstrap4 でレスポンシブ化。
スマホ表示時には、一般的なアプリを真似てメニューを下に配置しています。
カテゴリーメニューはオフキャンバスで表示させてます。

http://yotaca.com/demo/

現在のソースから組み込む必要がありますしどこまで反映できるか不明ですので、
とりあえず nucleusCMS用に仕上げますから、動かしてみて検討していただければと思います。

**Comment by akagane99** [comment]
スマホで見た時カッコいいですね。
iphone8で見た時、フォントアイコンが横幅くってたのか横スクロールがでてました。
![D3FF5948-C4F5-492B-B7B9-C49FFD7E077D](https://user-images.githubusercontent.com/2756509/68354075-b725b500-014e-11ea-8562-952a51231f29.png)
![87095BD3-4AF4-41E9-AEEC-6E4C61C51662](https://user-images.githubusercontent.com/2756509/68354077-b7be4b80-014e-11ea-9c70-2aad71120616.png)

**Comment by yotaca** [comment]
レイアウト完成しました。（カラーバリエーション付き）
http://yotaca.com

現在はnucleusCMS版ですが、conectCMSへ移植してみます。
こういっった場合はブランチを分ければ良いのでしょうか？

**Comment by nagasheep** [comment]
おおー。デザインカッコ良いですね。

・テーマを追加する形で、作ってもらえると嬉しいです。
・ディレクトリは以下の下に作るルールにしています。
https://github.com/opensource-workshop/connect-cms/tree/master/public/themes
・少しですが、ドキュメントは以下
https://github.com/opensource-workshop/connect-cms/wiki/Theme%EF%BC%88%E3%83%86%E3%83%BC%E3%83%9E%EF%BC%89
・ドキュメントが足りないとか、クラスなどのセレクタ名が必要、とかあれば言ってくださいね。
・ブランチの方法、それでお願いします。

以上、今年もよろしくお願いします。

**Comment by yotaca** [comment]
ありがとうございます。
手が空き次第確認して、ブランチ追加します。
