### ISSUE TITLE
【メニュー】タブフラットの表示見直し

### ISSUE THREAD

**Issue by akagane99** [opensource-workshop/connect-cms#1348]
* https://github.com/opensource-workshop/connect-cms/pull/1325

上記修正で、親階層のメニューをチェックしないと、子をチェックしても表示しなくなった。
しかし、タブフラットは階層構造を意識してない表示（フラット）なので、親階層のメニューOFFでも、子がONなら、（権限チェック等はしてOKなら）表示してもいいのかな？と思った。
（実際にプログラム上、できるかどうか、まだわかんない）

階層構造を意識したメニューテンプレート（サイトマップ等）は、この表示の対象外かなぁ。どうかなぁ。

## 親OFF、子ON（表示しない）

![image](https://user-images.githubusercontent.com/2756509/177075243-49b2d054-dd6d-4c9e-97da-c2bc3bfe76cc.png)
![image](https://user-images.githubusercontent.com/2756509/177075298-d6881d92-7635-46ad-bd23-f13e5040b3ca.png)

## 参考：親ON、子ON（表示される）
![image](https://user-images.githubusercontent.com/2756509/177075127-4d48da5d-ad57-4d60-b758-2404a589e24c.png)
![image](https://user-images.githubusercontent.com/2756509/177075171-b4c8e928-590d-4a69-a424-0706b8d7db72.png)

**Comment by nagasheep** [comment]
タブフラット、親がOFFでも表示して欲しいです。

**Comment by akagane99** [comment]
とりあえずタブフラットのみ見直す

**Comment by akagane99** [comment]
対応しました。

## 修正後画面
### メニュー（タブフラット テンプレート）
![image](https://user-images.githubusercontent.com/2756509/183368655-3a168c5e-3175-41f9-984d-491cfde14dea.png)
![image](https://user-images.githubusercontent.com/2756509/183368798-43e2a26a-b5fa-4755-9760-a62c4caedc75.png)

## 修正後プログラム

https://github.com/opensource-workshop/connect-cms/pull/1396/files
