### ISSUE TITLE
カレンダーのキャンセルボタンが空振り？

### ISSUE THREAD

**Issue by nagasheep** [opensource-workshop/connect-cms#1368]
## 概要

カレンダーのキャンセルボタンが空振りする。
予定一覧に遷移することを期待しました。

## 実行環境

Windows10＆Chrome

## 再現手順

カレンダーで新規投稿画面を開き、キャンセルボタンをクリックする。

## スクリーンショット

![image](https://user-images.githubusercontent.com/3079435/178622549-c35aaf06-f51b-440f-a318-baae8d71633c.png)

**Comment by akagane99** [comment]
対応しました。

## 修正プログラム

https://github.com/opensource-workshop/connect-cms/pull/1519/files
