### ISSUE TITLE
採番プラグイン

### ISSUE THREAD

**Issue by masaton0216** [opensource-workshop/connect-cms#141]
＜背景＞
受付チャネルがシステム上（問い合わせフォーム受付等）とアナログ（窓口受付等）で分かれている場合に受付番号の管理体系が２系統できてしまう。採番画面を操作しての採番、任意のプラグインで登録があった場合の採番をプラグインで1本化できればありがたい？

**Comment by nagasheep** [comment]
管理機能に採番管理を追加
