### ISSUE TITLE
マニュアルページへのリンクが有効でない

### ISSUE THREAD

**Issue by gakigaki** [opensource-workshop/connect-cms#1416]
## 概要

プログラム内に旧マニュアルへのリンクがあります。
旧マニュアルページが閉鎖されたので、現在リンク切れとなっています。

https://connect-cms.jp/plugin/blogs/show/2/5/296#frame-5

## 実行環境

OS: windows11
ブラウザ: Chrome
Connect-CMS: 2022/09/06 git pull
php version: 8.1.10

## 再現手順

1. コード管理画面を開く
2. はてなアイコンをクリックする

## スクリーンショット

一例として、コード管理画面のはてなアイコン
<img width="923" alt="image" src="https://user-images.githubusercontent.com/32890286/188558805-fcceff53-c811-4c0e-aaa2-10cf37240871.png">

**Comment by akagane99** [comment]
@nagasheep 

マニュアルページへのリンク切れの１件で、新マニュアルサイトにないページ「エラー説明」がありました。
とりあえず連絡まで。

対象画面
https://github.com/opensource-workshop/connect-cms/blob/master/resources/views/plugins/common/errors_inline_wysiwyg.blade.php

旧URL「エラー説明」ページ
https://connect-cms.jp/manual/error

新マニュアルサイト「共通機能」ページ（エラー説明ページなし）
https://manual.connect-cms.jp/common/index.html

インターネットアーカイブで　左メニュー　共通機能＞エラー説明　あり（ページデータなし）
https://web.archive.org/web/20211026024349/https://connect-cms.jp/manual/common/wysiwyg
![image](https://user-images.githubusercontent.com/2756509/188809005-c65cc83b-8073-4302-8dbe-42230332d0a4.png)

**Comment by akagane99** [comment]
新マニュアルサイト「ページ管理 - CSVインポート」ページで、旧マニュアルには書いてあった「CSVファイル項目説明」が抜けていました。
今後、新マニュアルサイトに追記したいなぁ。

新マニュアルサイト「ページ管理 - CSVインポート」（CSVファイル項目説明　の記載なし）
https://manual.connect-cms.jp/manage/page/upload/index.html

インターネットアーカイブ「ページ管理 - CSVインポート」（CSVファイル項目説明　の記載あり）
https://web.archive.org/web/20211026030706/https://connect-cms.jp/manual/manager/page

**Comment by nagasheep** [comment]
マニュアルの漏れ、やってみますね。

**Comment by nagasheep** [comment]
エラー説明は、マニュアルの以下のページにしたのを思い出しました。
なので、このURLへのリンクに変更をお願いします。
https://manual.connect-cms.jp/manage/system/index/index.html

**Comment by akagane99** [comment]
新マニュアルサイト「ユーザ管理 - ユーザ一覧」「ユーザ管理 - CSVインポート」ページで、旧マニュアルには書いてあった「ダウンロードの詳細」「インポートの詳細」がそれぞれ抜けていました。
今後、新マニュアルサイトに追記したいなぁ。


新マニュアルサイト「ユーザ管理 - ユーザ一覧」（ダウンロードの詳細　の記載なし）
https://manual.connect-cms.jp/manage/user/index/index.html

新マニュアルサイト「ユーザ管理 - CSVインポート」（インポートの詳細　の記載なし）
https://manual.connect-cms.jp/manage/user/import/index.html

Googleのキャッシュページ「ユーザ管理 - ユーザ一覧」「ユーザ管理 - CSVインポート」ページ
https://webcache.googleusercontent.com/search?q=cache:Qc9OFBDMrvIJ:https://connect-cms.jp/manual/manager/user&cd=1&hl=ja&ct=clnk&gl=jp
![image](https://user-images.githubusercontent.com/2756509/189020289-50410ec5-5d4a-4d3a-8899-198c84e6bea7.png)
![image](https://user-images.githubusercontent.com/2756509/189020338-970f58b1-d6aa-448e-bf88-bb93388bac01.png)

**Comment by akagane99** [comment]
https://github.com/opensource-workshop/connect-cms/issues/1416#issuecomment-1240113261

エラー説明ページ（ウィジウィグの最大バイト数越えエラーの詳細説明）を追加してもらうよう、連絡済み。

**Comment by akagane99** [comment]
ありがとうです。
WYSIWYGエラー説明のリンク、修正してプルリクに含めました。
https://github.com/opensource-workshop/connect-cms/pull/1418/commits/fa4fa7b99dfb7c01114b7894231b75dd74f46efa

**Comment by akagane99** [comment]
新マニュアルサイト「フォーム - カラム詳細編集」ページで、旧マニュアルには書いてあった「詳細画面で設定できる内容」等が抜けていました。
今後、新マニュアルサイトに追記したいなぁ。

新マニュアルサイト「フォーム - カラム詳細編集」（詳細画面で設定できる内容　等の記載なし）
https://manual.connect-cms.jp/user/forms/editColumnDetail/index.html

インターネットアーカイブ「フォーム - カラム詳細編集」（詳細画面で設定できる内容　等の記載なし）
https://web.archive.org/web/20210123011014/https://connect-cms.jp/manual/user/form#frame-125
![image](https://user-images.githubusercontent.com/2756509/189786650-47a7c427-9cce-4de5-a13c-8429e380b060.png)

参考：新マニュアルサイト「データベース - カラム詳細編集」（詳細画面で設定できる内容　等の記載はあった）
https://manual.connect-cms.jp/user/databases/editColumnDetail/index.html

**Comment by gakigaki** [comment]
マニュアルがマークダウンファイルになってたら上のような内容が編集しやすいのかなと思いました。

**Comment by akagane99** [comment]
@nagasheep 

マニュアルページへのリンク切れの１件で、新マニュアルサイトにないページ「課題管理」がありました。
とりあえず連絡まで。

対象画面
https://github.com/opensource-workshop/connect-cms/blob/master/resources/views/plugins/user/learningtasks/default/learningtasks_edit_users.blade.php#L34

旧URL「課題管理マニュアル」ページ
https://connect-cms.jp/manual/user/learningtasks

新マニュアルサイト「一般機能」ページ（課題管理ページなし）
https://manual.connect-cms.jp/user/index.html

インターネットアーカイブ「課題管理マニュアル」ページ　あり
https://web.archive.org/web/20210617052519/https://connect-cms.jp/manual/user/learningtasks
![image](https://user-images.githubusercontent.com/2756509/189789449-0d4c8ed3-7678-45c6-920f-b6659b82312f.png)

Googleのキャッシュ「課題管理マニュアル」ページ　あり
https://webcache.googleusercontent.com/search?q=cache:4ID2d45VKpYJ:https://connect-cms.jp/manual/user/learningtasks&cd=1&hl=ja&ct=clnk&gl=jp

**Comment by akagane99** [comment]
マークダウンファイルで書けたらいいよねー。
ただ現在は、dusk使ってマニュアル出力＋コントローラーのphpdocに追記＋フッターヘッダーは[htmlっぽいテキスト](https://github.com/opensource-workshop/connect-cms/blob/master/tests/Manual/insertion/user/databases/editColumnDetail/foot.txt) なんで難しそーかなぁと。

**Comment by akagane99** [comment]
残：課題管理

**Comment by akagane99** [comment]
マニュアルサイトの課題管理のページを作るのに時間がかかったため、一旦Connectの課題管理ページを復活させました。
https://connect-cms.jp/manual/user/learningtasks
これで、リンク切れは解消されたため、クローズします。

他作業があったら再オープンで。

もしマニュアルサイトの課題管理のページができたら、Connectのリンクを修正＋公式サイトの課題管理ページを削除位で良いかなぁと、個人的に思います。
