### ISSUE TITLE
【コア】静的コンテンツのキャッシュ機能 

### ISSUE THREAD

**Issue by gakigaki** [opensource-workshop/connect-cms#1429]
負荷軽減のために、静的コンテンツのキャッシュ機能を設けることを検討しています。

Connect-CMSは、画像やCSSなどの静的コンテンツをキャッシュさせる仕組みにはなっていません。
そのため、アクセスが集中すると、サーバーの負荷が上がります。
CDNを利用できるようにすることや、クライアントへのキャッシュをできるような仕組みを検討します。

**Comment by akagane99** [comment]
参考メモ
*  別件で調査したら [キャッシュコントロール・ミドルウェア](https://readouble.com/laravel/8.x/ja/responses.html#cache-control-middleware) はファイルキャッシュには使えなかった。
    * cache.headersミドルウェアがファイルのレスポンスに対応しないため https://github.com/laravel/framework/issues/31922
* ファイルの対応は UploadController.phpを修正かなぁと。

参考）UploadController.php修正
https://github.com/opensource-workshop/connect-cms/blob/master/app/Http/Controllers/Core/UploadController.php#L177
```php
            return response()
                    ->file(
                        $fullpath,
                        ['Content-Disposition' => $content_disposition]
                    );
↓
            return response()
                    ->file(
                        $fullpath,
                        ['Content-Disposition' => $content_disposition]
                    )->setCache(['private' => true, 'max_age' => 604800]);     // ←ここ修正
```

**Comment by akagane99** [comment]
画像やCSSをクライアントキャッシュする対応を入れたのでクローズします。
他対応あったら再オープンで。
