### ISSUE TITLE
[管理画面]Connect-CMS 更新情報等が表示されない

### ISSUE THREAD

**Issue by gakigaki** [opensource-workshop/connect-cms#1451]
## 概要

Connect-CMS 更新情報等に「Connect-CMS 更新情報が解析できませんでした。」と表示されて、公式サイトの内容が表示されません。

## 実行環境

OS: windows11
ブラウザ: Chrome
Connect-CMS: v1.1.0
php version: 8.1

## 再現手順

1. ログインして、管理画面を開く

## スクリーンショット

<img width="760" alt="image" src="https://user-images.githubusercontent.com/32890286/194035026-be3995ab-2b67-4356-89e8-1c2da9769fd1.png">

**Comment by gakigaki** [comment]
修正完了しました。

**Comment by akagane99** [comment]
当修正をConnect公式サイトに適用して、更新情報が表示されるようになったことを確認しました。
連絡まで。
