### ISSUE TITLE
[Opac] OpacAPIで、書籍を借りようとするとシステムエラーとなる

### ISSUE THREAD

**Issue by osws-makino** [opensource-workshop/connect-cms#1469]
## 概要
OpacAPIを利用して、書籍を借りようとした時、WEBシステム側でシステムエラーが発生する

## 再現手順
https://{サイトドメイン}/api/opac/rent/{Opac_ID}/barcode/{書籍バーコード}/{ユーザID}?secret_code={シークレットコード}&escape=json_unescaped_unicode

## スクリーンショット
![image](https://user-images.githubusercontent.com/34463938/196909140-4240325d-0a7a-4d0a-b8cb-4f646ea35f16.png)

## 原因
先日、opacs_books_lentsテーブルに追加した「delivery_request_flag」にデフォルト値がない為、設定せずテーブルにInsertしようとすると、エラーとなる為

## 対応
opacs_books_lentsテーブルのdelivery_request_flagのデフォルト値を「0」にする

**Comment by akagane99** [comment]
@osws-makino 
* https://github.com/opensource-workshop/connect-cms/pull/1470

上記で対応済みっぽい？
対応済だったらこのissueクローズしといてー。

**Comment by osws-makino** [comment]
対応済み。
CLOSEします。
