### ISSUE TITLE
セキュリティ管理、Chromeで見ると権限の選択がつぶれてる

### ISSUE THREAD

**Issue by akagane99** [opensource-workshop/connect-cms#150]
ちょっとバグ。選択はできるので見た目だけつぶれてる感じでした。

* windows10+Chrome
* 管理者メニュー＞セキュリティ管理　の画面

## 画面
![image](https://user-images.githubusercontent.com/2756509/71243286-5c899680-2353-11ea-94f5-0c6f995a65b3.png)

## 追記

bootstrapの記述を直せばいけるのかなぁ？

**Comment by akagane99** [comment]
iOS+safariでも同様でした。
![31197501-B715-40B2-AB04-ECD83933F4FB](https://user-images.githubusercontent.com/2756509/71243472-c86bff00-2353-11ea-8b17-0e9651f39b0b.png)

報告まで。

**Comment by nagasheep** [comment]
修正しました。
