### ISSUE TITLE
メニューとタブプラグインのフレーム削除時のプラグインデータ

### ISSUE THREAD

**Issue by nagasheep** [opensource-workshop/connect-cms#156]
ゴミが残る。
方法検討。

**Comment by akagane99** [comment]
メモ
・フレーム削除時に、各プラグインへのコールバックメソッドがあったらそれを呼ぶ処理があればできそう。
・ファイルプラグイン＋課題管理プラグインで、既にコールバックの仕組みをやってるみたい。
