### ISSUE TITLE
[コア]envでログ出力をdaily設定しても、スタック型のログも出力されている

### ISSUE THREAD

**Issue by masaton0216** [opensource-workshop/connect-cms#1563]
## 概要
 - dailyの設定の為「laravel-yyyy-mm-dd.log」の出力は想定できるが、「laravel.log」にも追記型でログが出力（connect_error_logの記載あり）されている。
     - laravel-yyyy-mm-dd.log
         - ローテーション型。
         - Excepionが出力されていない。
     - laravel.log
         - スタック型
         - Excepionが出力されている。
         - connect_error_logの記載あり。
 - ローテーションされず、トランザクションの多いシステムだとログが肥大化する為、ヘルシーではない。
 - ソース見たところ下記当たりが該当処理かと思われます。
https://github.com/opensource-workshop/connect-cms/blob/master/app/Plugins/User/UserPluginBase.php#L1284-L1292
```
～略～
-rw-r--r-- 1 apache apache     1871436  1月 17 23:48 laravel-2023-01-17.log
-rw-r--r-- 1 apache apache     1957610  1月 18 23:30 laravel-2023-01-18.log
-rw-r--r-- 1 apache apache     1528202  1月 19 14:11 laravel-2023-01-19.log
-rw-rw-r-- 1 apache apache 15968689510  1月 19 14:28 laravel.log
```

## 実行環境
Connect-CMS: v1.4.0

## 再現手順
 - envの「LOG_CHANNEL」に「daily」にセット
 - 何某かエラーを発生させる

**Comment by akagane99** [comment]
## 再現手順2

* envの「LOG_CHANNEL」に「daily」にセット
* .envで「APP_DEBUG=false」 
* 一般プラグインで、何某かエラーを発生させる
    *  laravel.log、laravel-2023-01-19.logの２つできる。画面は表示できるが、エラー該当プラグインの部分のみ500エラー。
* 備考
    * envの「LOG_CHANNEL」に「daily」にセット
    * .envで「APP_DEBUG=true」
    * 一般プラグインで、何某かエラーを発生させる
        *  laravel-2023-01-19.logのみ。「APP_DEBUG=true」のため、例外発生時は開発エラー画面を出すために画面表示がされ、全処理が中断するため、putlog()に到達しない。

**Comment by masaton0216** [comment]
PR後のverで事象の解消を確認したのでclose
