### ISSUE TITLE
[システム管理]「メール設定」の入力項目に null という文字列が付く

### ISSUE THREAD

**Issue by aquazaur** [opensource-workshop/connect-cms#1584]
## 概要
「メール設定」の各項目を入力した後、一旦「メール送信テスト」タブをクリックし、すぐに「メール設定」タブをクリックすると、「メール設定」の以下の項目に null が付加されています。（スクリーンショット(1)）

- 送信者メールアドレス
- SMTPAuthのユーザ
- SMTPAuthのパスワード（伏せ字になっているが元の個数より4文字多い）

（「メール設定」で「更新」をクリックせずに）再び「メール送信テスト」タブに移り、テストメールを送信しようとすると、スクリーンショット(2)のようなエラーが表示される。このとき、null 文字が散見される。（テストメールは送信できません）

## 実行環境
OS: macOS Monterey バージョン12.6.1
PC: MacBook Air (Apple M1 チップ)
ブラウザ: バージョン: 109.0.5414.119（Official Build） （arm64）
Connect-CMS: 1.3.0
サーバ: さくらのレンタルサーバ 　プレミアム
Webサーバ: Apache/2.4.54
PHP: 7.4.33 (モジュールモード)
DB: MySQL 5.7

## 再現手順
概要欄のとおり。

## スクリーンショット
(1)「メール設定」画面（「メール送信テスト」から戻ってきた時の画面）
<img width="873" alt="メール設定" src="https://user-images.githubusercontent.com/76809352/219603682-090d1e35-e62f-41b3-9348-172b0983530a.png">

(2)「メール送信テスト」画面でメール送信をしたときのエラー表示
<img width="1171" alt="メール送信テスト" src="https://user-images.githubusercontent.com/76809352/219603709-b232a3b6-f8f5-4187-a41d-55a8327ef235.png">

**Comment by akagane99** [comment]
詳しいご報告、ありがとうございました。
修正しました。

## 修正プログラム

https://github.com/opensource-workshop/connect-cms/pull/1592
