### ISSUE TITLE
ページ管理＞ページ一覧の項目名（略称）にツールチップ表示等で正式名表示する方向

### ISSUE THREAD

**Issue by akagane99** [opensource-workshop/connect-cms#160]
「背」「へ」だと意味が通じないので、ツールチップ表示等で正式名を表示する方向
![image](https://user-images.githubusercontent.com/2756509/72143261-bec93a80-33d9-11ea-903d-396bc74b11b0.png)

**Comment by nagasheep** [comment]
アイコンで対応しました。
