### ISSUE TITLE
[ページ管理] php8.1でページ登録の際、固定リンクに何も入れずに「ページ追加」しようとするとシステムエラー

### ISSUE THREAD

**Issue by osws-makino** [opensource-workshop/connect-cms#1821]
## 概要
ページ登録にて、固定リンクエリアを空のままにして「ページ追加」すると、システムエラーとなり

## 実行環境
PHP：8.1

## 再現手順
管理機能　→　管理者メニュー　→　ページ管理　→　ページ登録
「固定リンク」を空のままにして、「ページ追加」ボタン押下

## スクリーンショット
![image](https://github.com/opensource-workshop/connect-cms/assets/34463938/5b31d77f-07c4-4684-b05f-58180ab9b75a)
![image](https://github.com/opensource-workshop/connect-cms/assets/34463938/db1bbcb1-da66-4309-a3be-1a0452314c03)

## デバッグログ
![image](https://github.com/opensource-workshop/connect-cms/assets/34463938/300b683b-2cac-4732-a813-6957e0cc6686)

**Comment by akagane99** [comment]
メモ
* https://github.com/opensource-workshop/connect-cms/issues/1752

**Comment by akagane99** [comment]
対応しました。
