### ISSUE TITLE
【施設予約】キャプションの多言語対応

### ISSUE THREAD

**Issue by masaton0216** [opensource-workshop/connect-cms#192]
ConnectCommonTrait
の
getPageLanguage($page, $languages)
getPageLanguage4url($languages)

**Comment by nagasheep** [comment]
コアでの対応を行いました。
各プラグインで
$request->session()->get('applocale');
とすると、言語が取れます。
・デフォルトの場合は"jp"になります。

課題はまだ残っていて、以下のもの
・言語設定で自由入力になっている言語を選択肢にする。
・選択肢の追加方法を検討する。（ユーザが追加できる方法。”kids”なども対応したい）
・デフォルト言語の文字列の設定（URL的には空だけど、言語定数は必要）
・コントローラのコンストラクタでsessionが効かない問題の解決

以上、まずは使えるようになったはず。

**Comment by masaton0216** [comment]
下記の可変項目を除いて対応済み。
- 施設名
- 項目名
- 項目に紐づく選択肢名

**Comment by masaton0216** [comment]
運用が回っている為、クローズ。要求が上がってきたら再検討します。
