### ISSUE TITLE
【ブログ・各プラグイン】wysiwyg化のscriptスコープが他プラグインにも及んでいる

### ISSUE THREAD

**Issue by masaton0216** [opensource-workshop/connect-cms#194]
フォームプラグインで複数行選択の項目がwysiwyg化してしまうケースがある。

＜再現手順＞
※同一ページに
・ブログプラグインを設置
・フォームプラグインを設置（データ型「複数行」項目）
・ブログで記事の新規登録ボタンを押下

**Comment by nagasheep** [comment]
プラグイン側でWYSIWYGにすべきセレクタを設定できるようにした。

【WYSIWYG側】
https://github.com/opensource-workshop/connect-cms/blob/master/resources/views/plugins/common/wysiwyg.blade.php#L101

【プラグイン側】
https://github.com/opensource-workshop/connect-cms/blob/master/resources/views/plugins/user/databases/default/databases_input_wysiwyg.blade.php#L18

**Comment by nagasheep** [comment]
各プラグインを確認して修正が残っている。

**Comment by akagane99** [comment]
対応しました。

## 修正プログラム

https://github.com/opensource-workshop/connect-cms/commit/6c337b4549492ed3c8caac98ce229cb12452af8a
