### ISSUE TITLE
[カレンダー]同一日内の予定が、時間順ではなく登録順に並ぶ

### ISSUE THREAD

**Issue by osws-makino** [opensource-workshop/connect-cms#1963]
## 概要
カレンダーに登録した予定が、時間順ではなく登録順に並ぶ。
時間指定のある予定であれば、時間順に並ぶのがカレンダーとしては正解なのではないか？

## 実行環境
バージョン：バージョン: 1.15.4　にて再現
※たぶん昔からずっと

## 再現手順
・カレンダーのとある日に、「15:00～16:00」の予定を入れる
・カレンダーの同一日に、「10:00～11:00」の予定を入れる
・先に登録した、後の時間の予定の方が先に表示される

## スクリーンショット
【月表示（大）】
![image](https://github.com/opensource-workshop/connect-cms/assets/34463938/27ddc838-c504-40e9-a738-fd80ebd41379)
【月表示（小）】
![image](https://github.com/opensource-workshop/connect-cms/assets/34463938/1c956849-ad81-432e-9e13-1582c39dfdd2)
【日表示】
![image](https://github.com/opensource-workshop/connect-cms/assets/34463938/22dac71f-be2c-450a-84ae-312f5db66531)
【月表示（大）english】
![image](https://github.com/opensource-workshop/connect-cms/assets/34463938/ffd25952-627f-41d1-b333-53a71f7f12f4)

**Comment by akagane99** [comment]
対応済み
