### ISSUE TITLE
[ユーザ管理]インポートの新規登録でシステムエラーとなる

### ISSUE THREAD

**Issue by gakigaki** [opensource-workshop/connect-cms#1965]
## 概要

インポートCSVに新規登録のデータが含まれるとシステムエラーとなります。

以下、ログです。

> [2024-03-04 15:57:33] production.ERROR: SQLSTATE[HY000]: General error: 1364 Field 'columns_set_id' doesn't have a default value (SQL: insert into `users` (`userid`, `name`, `email`, `password`, `status`, `updated_at`, `created_at`) values (xxxx, ＸＸＸＸ, ?, $, 0, 2024-03-04 15:57:33, 2024-03-04 15:57:33)) {"userId":1,"exception":"[object] (Illuminate\\Database\\QueryException(code: HY000): SQLSTATE[HY000]: General error: 1364 Field 'columns_set_id' doesn't have a default value (SQL: insert into `users` (`userid`, `name`, `email`, `password`, `status`, `updated_at`, `created_at`) values (xxxx, ＸＸＸＸ, ?, $, 0, 2024-03-04 15:57:33, 2024-03-04 15:57:33)) at /var/www/html/connect-cms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:712)

## 実行環境

OS: windows11
ブラウザ: Brave
Connect-CMS: 1.16.0
php version: 7.4.33

## 再現手順

1. ユーザ管理のCSVインポートを開く
3. id列を空である行を含むCSVファイルを選択してインポートボタンを押下する

**Comment by akagane99** [comment]
.envの`USE_USERS_COLUMNS_SET=false` の時かな？
`USE_USERS_COLUMNS_SET=false` の時の、項目セットID（columns_set_id）のデフォ値の設定が漏れてるのかも。

**Comment by gakigaki** [comment]
`USE_USERS_COLUMNS_SET=true` でもシステムエラーになるので、おそらく値の設定処理が漏れていそうです。
