### ISSUE TITLE
[新着情報]もっと見るの動作不良

### ISSUE THREAD

**Issue by horitada** [opensource-workshop/connect-cms#2010]
## 概要
新着プラグインのもっと見る機能を利用した際にエラー

## 実行環境
OS: windows10
ブラウザ: Chrome
Connect-CMS: 1.11
php version: 8.1

## 再現手順
WAFを利用し通信がポート443　→　WAFからWEBサーバまでの通信がポート80
の場合に発生する。

## スクリーンショット
![pasted-2024 05 13](https://github.com/opensource-workshop/connect-cms/assets/12688974/f4b6ea7d-c0d0-4161-9699-5cc47814c570)

**Comment by akagane99** [comment]
・相対パスにしたら、動いちゃったりするのかなぁ。（動作確認する環境がないので、あてずっぽうですが。）
　→ ※ もし相対パスでOKの場合、ディレクトリインストールしたConnectでちゃんと動くか気になる

# 相対パスに修正
https://github.com/opensource-workshop/connect-cms/blob/master/resources/views/plugins/user/whatsnews/whatsnews_script.blade.php#L64
```js
                axios.get("{{url('/')}}/json/whatsnews/indexJson/{{$page->id}}/{{$frame_id}}?limit=" + this.limit + "&offset=" + this.offset + "&post_detail_length=" + this.post_detail_length)
↓
                axios.get("/json/whatsnews/indexJson/{{$page->id}}/{{$frame_id}}?limit=" + this.limit + "&offset=" + this.offset + "&post_detail_length=" + this.post_detail_length)
```

# WAF対応関連

* https://github.com/opensource-workshop/connect-cms/pull/1818

**Comment by akagane99** [comment]
ディレクトリインストールで動くかお試し。
うまくいかなかった。

# 修正１＝NG

https://pre.osws.jp/tmp/ のトップページに新着配置

```js
                axios.get("/json/whatsnews/indexJson/{{$page->id}}/{{$frame_id}}?limit=" + this.limit + "&offset=" + this.offset + "&post_detail_length=" + this.post_detail_length)
```

NG. ディレクトリ部分が抜けて動かない（https://pre.osws.jp/　になった）
![image](https://github.com/opensource-workshop/connect-cms/assets/2756509/db904f1f-5a47-4b22-8697-b90d0ef6bc53)

# 修正２＝NG

```js
                axios.get("./json/whatsnews/indexJson/{{$page->id}}/{{$frame_id}}?limit=" + this.limit + "&offset=" + this.offset + "&post_detail_length=" + this.post_detail_length)
```

トップページだと動くけど、階層が変わると動かなくなる

・トップページ＝動いた
・階層を深くしたところに新着情報配置＝NG

https://pre.osws.jp/tmp/tag/cabinet に新着配置（https://pre.osws.jp/tmp/tag/xxx になった。）

![image](https://github.com/opensource-workshop/connect-cms/assets/2756509/73411005-e9ee-46b5-b95f-2b3a7114bbbb)

**Comment by akagane99** [comment]
メモ

> Connect-CMS: 1.11

バグのConnetバージョンが1.11だった。

末尾/が悪さしてたっぽく、[v1.14.2](https://github.com/opensource-workshop/connect-cms/releases/tag/v1.14.2) で解消したっぽい。

修正内容
https://github.com/opensource-workshop/connect-cms/commit/296fdf6dfad1af9c6b98c381f72e97906cbba23b

**Comment by akagane99** [comment]
v1.14.2で解消済みだった事がわかったので、クローズします。
