### ISSUE TITLE
システム管理のメール送信テストで 500 internal server error

### ISSUE THREAD

**Issue by aquazaur** [opensource-workshop/connect-cms#2024]
## 概要
システム管理メニューの「メール送信テスト」をすると、500 internel server errorが発生し、メールを送信できない。

## 実行環境
OS: macOS Sonoma 14:5
ブラウザ: Google Chrome 125.0.6422.142（Official Build） （arm64）
Connect-CMS: 1.18.3
php version: 8.2.15
サーバ さくらのレンタルサーバ（メールアドレスの発行もこのサーバにて）

## 再現手順
1. 「管理者メニュー」
2. 「システム管理」
3. 「メール設定」でSMTP設定を行う（後述）
4. 「メール送信テスト」で「宛先メールアドレス」「件名」「本文」を入力の上、「送信」ボタンをクリック

## スクリーンショット
<img width="1262" alt="mail-smtp-test1" src="https://github.com/opensource-workshop/connect-cms/assets/76809352/5589166b-63d8-4f55-8f11-239db12d1b02">
<img width="876" alt="mail-smtp-test3" src="https://github.com/opensource-workshop/connect-cms/assets/76809352/6a0e2a8e-940f-4d5e-9655-e697e73a0f3c">

- 「SMTPサーバアドレス」には、さくらのレンタルサーバの"初期ドメイン"を使用しています。
- 設定にあたり、さくらインターネットの[こちらのサイトを参照しました](https://help.sakura.ad.jp/mail/2114/)。

## ログ
pathは dummy という文字を使って、一部伏せております。

[2024-06-13 13:01:01] production.ERROR: Callables of the form ["Swift_SmtpTransport", "Swift_Transport_EsmtpTransport::__construct"] are deprecated {"userId":1,"exception":"[object] (ErrorException(code: 8192): Callables of the form [\"Swift_SmtpTransport\", \"Swift_Transport_EsmtpTransport::__construct\"] are deprecated at /home/dummy/www/dummy/vendor/swiftmailer/swiftmailer/lib/classes/Swift/SmtpTransport.php:36)

## 「メール設定」の内容
- 「SMTPサーバのポート番号」として、25, 465, 587, 2525 の4通りを試しました。いずれも 500 エラーとなります。
- 「メール暗号化」では、25と2525については「設定なし」を、465と587では「TLS」を指定しました。

## メールアカウントの有効性
- さくらのレンタルサーバで発行したメールアカウントです。
- メーラー(Thunderbird)を用いて、当該メールアカウントでメールの送受信ができることを確認済みです。
- このとき、SMTPサーバのポート番号は 587の場合はSTARTTLS を使い、465の場合はSSL/TLSを使いました。どちらのポート番号であっても、メーラーからは送信できます。

## お願い
ここが解決しないと大ピンチなので、なる早で解決したいですm(..)m

**Comment by aquazaur** [comment]
したがいまして、ログイン画面の「パスワードを忘れた場合」リンクから「パスワードのリセットリンクを送信する」が機能しません。下のような画面となってしまいます。
<img width="1194" alt="password-forget" src="https://github.com/opensource-workshop/connect-cms/assets/76809352/93c8eb4f-02c1-47ba-99b5-8062aa9bad83">

**Comment by nagasheep** [comment]
aquazaur さん

こんにちは。
永原です。

設定がらみじゃないかなと思うので、Connect-CMSの公式サイトのフォーラムに書いてもらっても良いでしょうか？
ちょうど今朝、私もさくらのレンタルサーバーでConnect-CMSのメール設定したところなので、そっちに例として返信しますね。
そうすれば、今後の参考にもなるでしょうし。

以上

**Comment by aquazaur** [comment]
PHPのバージョンをダウンさせたところ、「メール送信テスト」に成功しました。具体的には 8.1系（8.1.27）、7.4系（7.4.33）なら正常に動作しますが、8.2系を選ぶと 500 エラーとなります。

↓のスクリーンショットは、さくらのレンタルサーバのコントロールパネルでPHPのバージョンを選択する様子です。
<img width="957" alt="スクリーンショット 2024-06-13 15 35 25" src="https://github.com/opensource-workshop/connect-cms/assets/76809352/9954e10c-3203-4191-9cd3-2257173dc00e">

**Comment by akagane99** [comment]
ご連絡ありがとうございました。

Connect1.xはLaravel8.xを使っていまして、Laravel8.xがphp8.2非対応なんです。
ご連絡の通り、php8.1を指定して頂ければと思いますので、本件クローズさせて頂きます。
