### ISSUE TITLE
データベースからファイルをダウンロードしてもダウンロード数がカウントアップしない（PDF以外）

### ISSUE THREAD

**Issue by aquazaur** [opensource-workshop/connect-cms#2061]
## 概要
データベースプラグインで項目としてファイル型を配置します。そして、あるユーザーがファイルを掲載します（※）。
次にwebサイト閲覧者が当該ファイルをダウンロードしたときに、ダウンロード数が0のままです（カウントアップしない）。

※ユーザーが掲載したファイルがPDFの場合は、閲覧者によるダウンロードでダウンロード数がカウントアップされます。

## 実行環境
OS: macOS Sequoia 15.1（最新のやつです）
ブラウザ: バージョン: 130.0.6723.117（Official Build） （arm64）
Connect-CMS: バージョン: 1.19.2
php version: 7.4.33 (モジュールモード)
サーバ：さくらのレンタサーバ

## 再現手順
(1)データベースプラグインを配置し、項目としてファイル型を設けます。
(2)ファイル型の項目設定で、「ダウンロード件数を表示する」として「表示する」を指定します。
(3)権限のあるユーザがファイル型項目にファイルを掲載します。
(4)webサイトの閲覧者がファイルをダウンロードします。

※(2)で「表示しない」を選択している場合でも、ダウンロード数は0のままです（PDFを除く）。

## スクリーンショット
テストしたときの様子です。
<img width="1154" alt="ダウンロードテスト" src="https://github.com/user-attachments/assets/a03a4e8d-92bd-4c2f-b76d-ba7e19acb4dc">

## 
実際に使っている様子です。私の作ったプラグイン(zipファイル：kintone用)がひとつもダウンロードされていないように見えます。マニュアル(PDF)は300〜600もダウンロードされているのに、「みんなマニュアルだけ見て、《つまらないプラグインだな》と感じてzipファイルの方はダウンロードしていないんだな」と思っていました。サイトを見た人にも、人気のないプラグインなんだという印象を与えてしまい、残念な気持ちです。
<img width="584" alt="人気のないzip" src="https://github.com/user-attachments/assets/a48c2d4a-1554-4ad7-a37d-a630d8a23dbb">

PDF以外のファイルであってもダウンロード数をカウントするように改善をお願いいたします。

**Comment by aquazaur** [comment]
マニュアル(PDF)を何百人もの人がダウンロードしているのに、プラグイン(zip)ファイルを１つもダウンロードされてないって不自然だなと感じ、今回初めてテストしてみたという経緯です。

**Comment by akagane99** [comment]
ご連絡ありがとうございます。
不具合でしたので修正対応しました。

* https://github.com/opensource-workshop/connect-cms/pull/2063

**Comment by aquazaur** [comment]
早速のご対応ありがとうございました(^^)
