### ISSUE TITLE
データベースプラグインでPDFファイルをダウンロードすると、ダウンロード数が2だけ増える（PDFファイルのみ）

### ISSUE THREAD

**Issue by aquazaur** [opensource-workshop/connect-cms#2069]
## 概要
データベースプラグインのファイル型の項目にPDFファイルがアップロードされているとします。この状態でwebサイト閲覧者が当該PDFファイルをダウンロードするとダウンロード数が、2だけカウントアップする。

※PDF以外のファイル（画像やzipファイル）の場合は、ダウンロード数が1だけカウントアップされます（正常）。
※ #2061 を修正していただいたことによる副作用かと。

## 実行環境
OS: macOS Sequoia 15.1（最新のやつです）
ブラウザ: バージョン: 131.0.6778.70（Official Build） （arm64）
Connect-CMS: バージョン: 1.21
php version: 7.4.33 (モジュールモード)
サーバ：さくらのレンタサーバ

## 再現手順
(1)データベースプラグインを配置し、項目としてファイル型を設けます。
(2)ファイル型の項目設定で、「ダウンロード件数を表示する」として「表示する」を指定します。
(3)権限のあるユーザがファイル型項目にPDFファイルを掲載します。
(4)webサイトの閲覧者がPDFファイルをダウンロードします。

## スクリーンショット
PDFファイルのダウンロード数だけが実際のダウンロード数より多くなっています。
<img width="602" alt="PDFダウンロード(1)" src="https://github.com/user-attachments/assets/67df2000-e2fa-49af-9190-754085b3a249">

データベースに掲載されているPDFファイルの名前をクリックすると、webブラウザにPDFの中身が表示されます。このタイミングでダウンロード数が +1されます。更に、webブラウザのPDF表示の右上にあるダウンロードボタン（下向き矢印）をクリックすると、PDFがPCローカルにダウンロードされますが、このとき更にConnect-CMSのデータベース側で +1されます。
<img width="1265" alt="PDFダウンロード(2)" src="https://github.com/user-attachments/assets/ded861c0-d9a4-4fd0-a37e-d04aa5383b1a">

**Comment by akagane99** [comment]
前回の修正（ https://github.com/opensource-workshop/connect-cms/pull/2063/files ）はダウンロード回数を数える拡張子が制限されているのを外す修正でした。
なので、おそらくPDFダウンロードの動作は、以前変わりないと思いますよ。

**Comment by aquazaur** [comment]
なるほど。ということは、バージョン1.19.2の時点でPDFファイルをダウンロードすると2ずつカウントアップしていたということですね。実際、バージョン1.19.2のConnect-CMSで試したときのスクリーンショットを以下に示します。各ファイルを1回だけダウンロードしたときの様子です。PDFファイルはダウンロード数が2で、PNGファイルとZIPファイルはともにダウンロード数は0です。繰り返しになりますが、3つのファイルとも、実際のダウンロード回数は1です。

**スクリーンショット１**：バージョン1.19.2のConnect-CMSを使いました。
<img width="757" alt="cc1_19_2" src="https://github.com/user-attachments/assets/1b91a86c-003e-407d-85f8-727a901e8147">

**スクリーンショット２**：各ファイルを1回だけダウンロードしたときの「ダウンロード数」表示
<img width="973" alt="cc1_19_2_DB" src="https://github.com/user-attachments/assets/649cb138-f31a-465c-b7c6-7c965fdbc5ee">

**Comment by aquazaur** [comment]
私としては「PDFのダウンロード数が2倍である」ことがわかっており、かつ、ZIPファイルなどのダウンロード数が把握できる状態であれば、運用上の支障はないです。つまり、バージョン1.21の仕様で個人的にはOKです。

想像ですが、PDFの場合は、webブラウザがサーバに対し二回（プレビューの時と実際にダウンロードする時）のダウンロードリクエストをしているのでサーバ側からその挙動は識別できないのかなと。

画像ファイルの場合はブラウザがプレビュー表示しますが、実際のダウンロードはブラウザに表示された画像をドラッグ＆ドロップでPCに持って来る形となるため、ドラッグ＆ドロップ時にサーバにリクエストが飛ばないのでしょう。

ZIPファイルは、ブラウザによるプレビューというプロセスがなく、直接ダウンロードすることになるので「ダウンロード数」は正確にカウントできるということかなと。

**Comment by akagane99** [comment]
そうですね。サーバへのリクエスト回数＝ダウンロード回数になるかと。

なのでブラウザキャッシュの参照でも、ダウンロード回数がずれることがあるかもです。（PDF表示で１回、ダウンロードで１回しても、ダウンロード数は１のままとか）
参考まで。

情報ありがとうございました。
バグではなさそうなので、issueはクローズさせて頂きます。
