### ISSUE TITLE
[フレーム編集] 公開日時From、Toが限定公開以外でも入力できる

### ISSUE THREAD

**Issue by akagane99** [opensource-workshop/connect-cms#2074]
## 概要

軽微な不具合で、困ってませんが連絡まで。

フレーム編集の初期表示時に、公開日時From、Toが入力可能状態になっていました。
公開日時From、Toは、限定公開のみ入力できるようにしているようで、公開設定＝限定公開を選択後、
他の公開設定にすると、公開日時From、Toが入力不可になりました。

## 該当ソース
resources\views\core\cms_frame_edit.blade.php

vueの修正がよくわからず、対応できませんでした。
vueは2.xのようです。

## 実行環境
OS: windows11
ブラウザ: Edge
Connect-CMS: 2024/11/22 git pull
php version: 7.3.0

## 再現手順

https://github.com/user-attachments/assets/2e6e9f0d-63dc-4d27-8b8c-c29fac20e633

## スクリーンショット

![image](https://github.com/user-attachments/assets/ceb5ff88-1c14-4cd3-b604-70b7d42c2b2f)

**Comment by akagane99** [comment]
> resources\views\core\cms_frame_edit.blade.php
> 
> vueの修正がよくわからず、対応できませんでした。
vueは2.xのようです。

# 調査
vue＋datetimepicker同時使用で不具合が出ていました。
解決は難しそうです。

・vueは正常動作していました。（jsのdatetimepicker定義部分をコメントアウトして動作確認）
・使用しているdatetimepicker（Tempus Dominus Bootstrap4 v5.39.0）で初期にreadonlyを解除しているようです。
・datetimepicker初期値に`ignoreReadonly: true`を設定してもダメでした。
　* https://getdatepicker.com/5-4/Options/#ignorereadonly

```html
<script>
    new Vue({
      el: "#app_{{ $frame->id }}",
      data: {
        // コンテンツ公開区分
        v_content_open_type: '{{ old('content_open_type', $frame->content_open_type) }}'
      }
    })

    $(function () {
        // 公開日時Fromのpicker
        $('#content_open_date_from').datetimepicker({
            locale: 'ja',
            sideBySide: true,
            dayViewHeaderFormat: 'YYYY年 M月',
            format: 'YYYY-MM-DD HH:mm:ss'
        });

        // 公開日時Toのpicker
        $('#content_open_date_to').datetimepicker({
            locale: 'ja',
            sideBySide: true,
            dayViewHeaderFormat: 'YYYY年 M月',
            format: 'YYYY-MM-DD HH:mm:ss'
        });
    });
</script>
```

# 参考
* https://github.com/opensource-workshop/connect-cms/wiki/Datetimepicker

**Comment by masaton0216** [comment]
対応済み
