### ISSUE TITLE
［ブログ］最後の記事だけ、クラス属性が付与されない

### ISSUE THREAD

**Issue by aquazaur** [opensource-workshop/connect-cms#2085]
自社サイトをリニューアルしていて気づきました。
記事が一覧になっているページで、最後の記事だけデザイン（CSS）が適用されない現象が発生しました。例えば、1ページに5件の記事を表示している場合は、5件目の記事にデザインが適用されません。原因を探ったところ、最後の記事の<article>タグに「class="cc_article"」属性がセットされていないためだとわかりました。

確認バージョン：Connect-CMS - version1.21

スクリーンショット：
<img width="1189" alt="blog-article-class" src="https://github.com/user-attachments/assets/2a52d0b6-ea35-4eae-ae87-1387fa66da8e" />

**Comment by akagane99** [comment]
ご連絡ありがとうございます。
修正しました。

詳細
* https://github.com/opensource-workshop/connect-cms/pull/2090
