### ISSUE TITLE
［ブログ］「RSS2.0」アイコンをクリックすると、エラーっぽいものが表示される

### ISSUE THREAD

**Issue by aquazaur** [opensource-workshop/connect-cms#2086]
**現象**
ブログの「RSS2.0」アイコンをクリックすると、エラーっぽいものが表示される。Safariの場合は、Thunderbirdの起動を求められる。

**当方の環境**
OS: macOS Sequoia 15.1.1
Google Chrome: バージョン: 131.0.6778.110（Official Build） （arm64）
Firefox: 133.0 (aarch64)
Safari: バージョン18.1.1
Connect-CMS: version1.21

**スクリーンショット**
Chromeの場合
<img width="1074" alt="blog-RSS1" src="https://github.com/user-attachments/assets/7cf1f7de-431d-4a2e-a59e-7cf256e21635" />
<img width="1044" alt="blog-RSS-Chrome" src="https://github.com/user-attachments/assets/65454477-6c37-4ed0-abb6-629746d7af6a" />

Firefoxの場合
<img width="1019" alt="blog-RSS-Firefox" src="https://github.com/user-attachments/assets/0d25e8ec-6312-4592-850f-6bb5b39a07fd" />

Safariの場合
<img width="1157" alt="blog-RSS-Safari" src="https://github.com/user-attachments/assets/9dde8e3c-6948-40c4-bdd0-bf5211dd0fec" />

**Comment by akagane99** [comment]
どうも記事の中に → (`&rarr;`) があるとRSSがエラーになることが再現できました。
とりあえず連絡まで。

**Comment by akagane99** [comment]
* https://github.com/opensource-workshop/connect-cms/pull/2091

ご連絡ありがとうございました。
修正対応しました。
