### ISSUE TITLE
ページ内検索のバグ？

### ISSUE THREAD

**Issue by akagane99** [opensource-workshop/connect-cms#239]
公式のサイト内検索が、うまく機能してませんでした。
とりあえず報告まで。

・Enter押すと遷移はする。
　・検索結果でない
・虫眼鏡ボタン押しても反応しない。
　⇒ スマホで検索できない。

## ーーー 検索結果出るパターン

１．一度URLに？くっつけてバリデーションエラー出す
　https://connect-cms.jp/plugin/searchs/search/52/117?xsss
２．その後何度か虫眼鏡ボタンを押す
３．検索文字を入れて、虫眼鏡ボタン押す。
　　検索結果表示される。

**Comment by nagasheep** [comment]
修正しました。
<inout type="submit" 
とかになってた。input ->inout
よくボタンが出てたわ。(笑)

**Comment by akagane99** [comment]
そのtypoは気づかなかった！
対応感謝、クローズします。
