### ISSUE TITLE
権限の表現

### ISSUE THREAD

**Issue by nagasheep** [opensource-workshop/connect-cms#245]
管理権限の表現をうまくする。
記事管理者は他の権限を包括する。など。

**Comment by akagane99** [comment]
コンテンツ管理者の下に説明文を追記ずみのため、一旦クローズします。
もし必要なら再オープンで。
![image](https://user-images.githubusercontent.com/2756509/119913602-4c8ad300-bf99-11eb-869d-a49dfba39b27.png)
