### ISSUE TITLE
「フレーム編集」フレームデザインをNoneに設定すればプレビューモードやログアウトした時に表示されないようにして欲しい

### ISSUE THREAD

**Issue by cocoluca** [opensource-workshop/connect-cms#259]

**Comment by akagane99** [comment]
動作確認してみました。

* フレームデザインで表示非表示を制御しなくても、
固定記事であれば、「初期状態を非表示とする。」にチェックONで、ログアウト時に非表示にできました。
* ログイン済み＆プレビューモードでは非表示も見れてました。（ここは改善必要かなぁ？）

## 「初期状態を非表示とする。」にチェックON
![image](https://user-images.githubusercontent.com/2756509/76481205-3f48fd80-6454-11ea-926b-914de6279496.png)

## 設定後、固定記事表示（ログイン済み。プレビューモードON同じ表示）
![image](https://user-images.githubusercontent.com/2756509/76481258-60115300-6454-11ea-9fc8-d47eaca659c8.png)

## ログアウト後（該当の固定記事は見えない）

![image](https://user-images.githubusercontent.com/2756509/76481340-9353e200-6454-11ea-9041-5b4ce0e1d794.png)

**Comment by cocoluca** [comment]
![スクリーンショット 2020-03-12 11 36 15](https://user-images.githubusercontent.com/62084540/76481931-19245d00-6456-11ea-84af-7bb35f0c6c90.png)

記事全部ではなくここだけを消して欲しいのです

**Comment by nagasheep** [comment]
@cocoluca さん、こんにちは。
株式会社オープンソース・ワークショップの永原と申します。

もうちょっと要求を教えてもらって良いです？
その部分、フレームタイトルと言いますが、歯車アイコンのフレーム編集から、フレームタイトルを空にすれば、消えると思いますが、それでご要望は賄えます？

**Comment by cocoluca** [comment]
フレームタイトルは入れないと一覧でどれだかわかななくなってしまうし、レイアウトしている時も便利なので入れたい。
プレビューモードにした時に歯車アイコンは消えますよね？
それと一緒に消えて欲しいんです。
フレームタイトル入れなくても一覧で分かる方法はありますか？

**Comment by nagasheep** [comment]
なるほど。
要望、改善点が見えてきました。（^^）
「フレームタイトルは入れないと一覧でどれだかわかななくなってしまう」
確かに。いまは、一覧でわからないですね。
いま、フレームタイトルと、一覧で出す、データの「名前」を混同しているのが良くないですよね。

「レイアウトしている時も便利なので入れたい。」
なるほど。こういう要望もあるのですね。
理解できる気がします。

おかげで課題が洗い出されました。
ありがとうございます。
良いユーザーインターフェースを考えてみたいです。
とりあえず宿題にさせてください。

今のところは面倒ですが、フレームタイトルを不要になったら消す。くらいで対応をお願いいたします。
