### ISSUE TITLE
「ブログ」サムネイルを入れれるようにして欲しい

### ISSUE THREAD

**Issue by cocoluca** [opensource-workshop/connect-cms#261]

**Comment by nagasheep** [comment]
@cocoluca さん、こんにちは。
株式会社オープンソース・ワークショップの永原です。

「ブログ」にサムネイルを入れるって、どういうことでしょうか？
ちょっと理解しきれなかったので、もう少し詳しく、聞きたいです。

以上、よろしくお願いいたします。

**Comment by cocoluca** [comment]
ブログのタイトルの横にサムネイル画像が表示されると良いなと。

**Comment by nagasheep** [comment]
例えば、こういう感じ？
![image](https://user-images.githubusercontent.com/3079435/76487746-b091ac00-6466-11ea-8658-a7b586eb16a8.png)

**Comment by cocoluca** [comment]
![サムネイル](https://user-images.githubusercontent.com/62084540/76488554-27c83f80-6469-11ea-9cea-62159c3e4d74.png)

こんな感じが欲しいです
アバターではなくて記事のタイトル写真的な。。。

**Comment by nagasheep** [comment]
「記事のタイトル写真」というのは、記事本文の写真とは別に、記事に「サムネイル画像」として追加できるもの。という要望ですね。
ニュースサイトとかで使えそうなレイアウトですね。
要望は理解できたと思います。
すぐは無理だと思いますが、このIssue は残しておいて、できるときにやりたいです。

![image](https://user-images.githubusercontent.com/3079435/76488947-5eeb2080-646a-11ea-991b-e6ab45ceb21f.png)
