### ISSUE TITLE
「管理者メニュー」画像のアップロード一覧が欲しい

### ISSUE THREAD

**Issue by cocoluca** [opensource-workshop/connect-cms#262]

**Comment by akagane99** [comment]
今後作成予定のようです。

管理機能 ＞ ファイル管理の作成
https://github.com/opensource-workshop/connect-cms/issues/182

**Comment by nagasheep** [comment]
管理機能 ＞ アップロードファイル　として実装したので、一旦Closeします。
今後の機能要望は以下のアイデアIssue に書きたいです。
https://github.com/opensource-workshop/connect-cms-ideas
