### ISSUE TITLE
「レイアウト」ヘッダーを100%指定した時の固定記事

### ISSUE THREAD

**Issue by cocoluca** [opensource-workshop/connect-cms#263]
ヘッダーを100%指定した時、固定記事の幅を「６」にして２つ並べると画面の端あわせになってしまう。
![1-1](https://user-images.githubusercontent.com/62084540/76584708-d75fe900-651f-11ea-8faa-222597fc2f1f.png)

これをメインと同じ幅の中に収めたい

![1-2](https://user-images.githubusercontent.com/62084540/76584916-5e14c600-6520-11ea-89ea-354dd22c1e37.png)

**Comment by nagasheep** [comment]
確かに！
ちょっとすぐには対応できなさそうですけど、問題点を認識しました。
なんとかしたいな。
