### ISSUE TITLE
ヘッダーの中のプラグインを固定して他のページと共用したい

### ISSUE THREAD

**Issue by cocoluca** [opensource-workshop/connect-cms#264]
ヘッダー、フッターの共通のプラグインを全ページで入れるのはミスの元になるので固定したい

**Comment by nagasheep** [comment]
これ、可能なはずなのです。
メイン以外のヘッダー、フッター、左、右に配置したプラグインは、基本的に他のページに継承されるはずなんですけど。

**Comment by cocoluca** [comment]
固定記事を追加したり、固定記事が入ってたりすると反映されない。。。ようです。

**Comment by nagasheep** [comment]
なるほど。
・トップのヘッダーに固定記事配置
↓
・基本はそのまま他のページにも反映（継承）
・他のページで、ヘッダーにプラグインを配置 ＞ この時点で、元の内容を上書きして、ここから下の階層は新しい内容を継承

という動きなんです。
伝わります？？

**Comment by cocoluca** [comment]
伝わりましたが、残念な感じです - -

**Comment by nagasheep** [comment]
あら。
あ、ヘッダーの中のひとつだけ、共通にしたい。とか、どういうことかな？

**Comment by cocoluca** [comment]
ヘッダーに追加しても固定したい「固定記事」はそのまんまという感じです。
