### ISSUE TITLE
「デザイン」navbarを透明にしたい

### ISSUE THREAD

**Issue by cocoluca** [opensource-workshop/connect-cms#266]
navbarを透明にしたい。
しかし、スマホモードのnavは背景色ありにしたい。

**Comment by nagasheep** [comment]
navbar を消す。ではなく、透明。なんですね。
透明だけど、リンクとかは生きている感じです？

**Comment by cocoluca** [comment]
そーなんです。透明です。
背景を入れた時に邪魔にならないように。
リンクはスマホモードの時のハンバーガーメニューは欲しいので生きていて欲しいです。

**Comment by akagane99** [comment]
気になったので試してみました。
サイトの背景色に`rgba(255,0,0,0.5)`とか指定すれば出来ました。
連絡まで。

## 表示例

![image](https://user-images.githubusercontent.com/2756509/117592977-9429f600-b175-11eb-8845-fb4b3af4d394.png)

## 設定例：サイトの背景色設定

![image](https://user-images.githubusercontent.com/2756509/117592932-69d83880-b175-11eb-9085-3f1e52e7b828.png)

## 透過色 参考記事

【css】背景色(background-color)のみを透過させ文字などは透過させない方法 | WEBクリエイターの部屋
https://arts-factory.net/rgbabk/
