### ISSUE TITLE
jQueryを使ってなめらかな動きを実装したい

### ISSUE THREAD

**Issue by cocoluca** [opensource-workshop/connect-cms#267]
jQueryでなめらかなスライダーの実装となめらかなpagetopを実装させたいです。

その際、ダウンロードした本体ファイル.jpはどこに配置するのでしょうか？
ユーザ・テーマJavaScript編集 の書き方はどうなるのでしょうか？

**Comment by nagasheep** [comment]
こんにちは。
株式会社オープンソース・ワークショップの永原です。

ダウンロードした本体ファイル.jpはいまはアップロードできないので、テーマ管理でアップロードできるようにしますね。
ユーザ・テーマJavaScript編集 の書き方も、サンプルを作ってみたいと思います。

**Comment by akagane99** [comment]
トップページへボタンの追加、公式フォーラムで対応方法がありました。
https://connect-cms.jp/plugin/bbses/show/106/233/248#frame-233
