### ISSUE TITLE
「ブログ」必須になっている「タイトル」の必須を外したい

### ISSUE THREAD

**Issue by cocoluca** [opensource-workshop/connect-cms#270]
ブログの「タイトル」の必須は外すことはできませんか？
タイトルを入れないでブログを書きたいのです。
新着情報とかには表示させないで記事を書くのにブログを使いたい。

**Comment by nagasheep** [comment]
ブログの「フレーム設定」に「新着に表示しない。」のチェックがあるのです。
※マニュアルが追いついてないので、画面で見てみてください。
このチェックを入れておくと、そのフレームは、新着に表示しなくなります。
この機能でご要望はクリアできます？

**Comment by nagasheep** [comment]
あと、新着プラグイン側にも、全フレームを表示するか、フレームを選択して表示するかの機能があります。
こっちでも良いのかも知れません。

**Comment by cocoluca** [comment]
記事一覧でタイトルを表示させたくないって感じです

**Comment by nagasheep** [comment]
なるほど。記事の本文だけにしたい。ということですね。
タイトルなくすと、新着とか、他に影響するものを検討しないといけないですね。
CSS で消しちゃえません？

**Comment by cocoluca** [comment]
CSSで消します！
ありがとうございました

リンクも新着もいらなかったのでサクッと消すことにします。

**Comment by nagasheep** [comment]
はーい。
