### ISSUE TITLE
「ブログ」閲覧ページ内でカテゴリの並び替えはできない？

### ISSUE THREAD

**Issue by cocoluca** [opensource-workshop/connect-cms#271]
設定ではなく、ボタンクリックで並び替えれる？

**Comment by cocoluca** [comment]
ブログの一覧ページでカテゴリの並び替えはできる？

**Comment by nagasheep** [comment]
まだ、閲覧ページ内での並び替えはないんです。
作りたいなとは思い中。
４月になったら、一度、Connect-CMS勉強会として、要望なども整理した打ち合わせしましょうか？

**Comment by cocoluca** [comment]
気軽に打ち合わせできる世の中にはやくなってもらいたいですね！
