### ISSUE TITLE
『カテゴリ設定』について

### ISSUE THREAD

**Issue by yotaca** [opensource-workshop/connect-cms#275]
『サイト管理』> 『カテゴリ設定』で設定したカテゴリは、それぞれのページに指定できるのでしょか？
『ページ管理』からはカテゴリに関する設定が見当たりません。

ページの親子関係は『ページ管理』からできるようなので、別段カテゴリが必要な気もしませんが、何か『カテゴリ』を設定する意味があるのならご教示願えますか。

**Comment by nagasheep** [comment]
@yotaca さん、こんにちは。
永原です。

『サイト管理』> 『カテゴリ設定』で設定したカテゴリは、ブログなどの「記事」に対して指定できます。
以下はブログのマニュアル
https://connect-cms.jp/manual/user/blog
「記事編集」画面にあるカテゴリに紐づきます。

「ページ」にカテゴリを与える。という発想はなかったです。

また、『サイト管理』> 『カテゴリ設定』は、サイトとして共通のカテゴリ設定です。
各プラグインは、サイトとして共通のカテゴリも使えて、各プラグイン内でも、プラグインデータ毎に、カテゴリを追加できるようにしています。

以上、伝わりました？

**Comment by yotaca** [comment]
ありがとうございます。
カテゴリがサイトの構成に直接関与しないこと理解しました。
想定されたカテゴリの使い方については感覚的に掴み辛いので実際にサイトを構築して確認します。

とりまうちのサイト作りながら、テーマ作成みてみます。

**Comment by nagasheep** [comment]
たいぶ、バージョンアップしてますので、バージョンアップするか、最新ソースからサイト作ってくださーい。
バージョンアップ
git pull
php artisan migrate
https://github.com/opensource-workshop/connect-cms/wiki/Install-%28%E3%82%A4%E3%83%B3%E3%82%B9%E3%83%88%E3%83%BC%E3%83%AB%29

**Comment by yotaca** [comment]
ありがとうございます。
4月1日分でローカルで構築しているので、とりあえずは大丈夫かと思います。
それよりも『Github Desktop』を使ってブランチが分けられなかったので『Originals』でテーマ作り始めます。
また不明点があればアップさせていただきます。
よろしくお願いします。
