### ISSUE TITLE
固定記事プラグインの「ブロック引用」機能

### ISSUE THREAD

**Issue by dreamer9999** [opensource-workshop/connect-cms#276]
当方ローカル（xampp）にて最新版使用させていただいております。
（使わせていただいて気が付くところあればご参考にれんらくさせていただこうと思います。）

固定記事プラグインで「ブロック引用」を文章に適用しても、文章が引用表示形式にならないように思えます。

●ソース表示

![image](https://user-images.githubusercontent.com/3895089/78965568-6587b900-7b38-11ea-893d-235656f29f91.png)

●画面表示
![image](https://user-images.githubusercontent.com/3895089/78965293-95828c80-7b37-11ea-9e6f-01ea4b61a457.png)

**Comment by akagane99** [comment]
再確認しました。
最新版でも同様でした。

**Comment by akagane99** [comment]
# 調査

bootstrap3⇒bootstrap4になって、blockquote は `class="blockquote"`が必要になった。
wysiwygで引用ボタン押下時に`class="blockquote"`を足してあげる。


## bootstrap4のblockquote 表示

`<blockquote class="blockquote">`
![image](https://user-images.githubusercontent.com/2756509/119243237-e91b3280-bb9f-11eb-9c6a-ca7a8e27feb7.png)

## 参考URL

https://getbootstrap.com/docs/4.6/content/typography/#blockquotes

**Comment by akagane99** [comment]
対応しました。

## 対応後

ちょっと文字が大きくなる位。
bootstrap3の時のように左側に灰色線がつかなくなったみたい。
もし表示を見直すなら、別issueで今後検討かなぁと。

![image](https://user-images.githubusercontent.com/2756509/119243351-c5a4b780-bba0-11eb-9338-bf36f01610cc.png)

```html
<p>こんにちは</p>
<blockquote class="blockquote">こんにちは</blockquote>
<p>こんにちは</p>
```

## 修正プラグラム

https://github.com/opensource-workshop/connect-cms/commit/42802dafd855560ad9150933f09c99dbf8394c4e
