### ISSUE TITLE
ブログのテンプレート「タイトルのみ（サイド用）」が機能しない

### ISSUE THREAD

**Issue by dreamer9999** [opensource-workshop/connect-cms#277]
ブログのテンプレート「タイトルのみ（サイド用）」が機能しないように思えます。
新規登録、編集ボタンが表示されないみたいです。

![image](https://user-images.githubusercontent.com/3895089/78965980-94525f00-7b39-11ea-8d99-89b62910ec9f.png)

**Comment by akagane99** [comment]
再確認したところ、機能していたため、どこかのタイミングで修正されたのかも。
問題なかったため、クローズします。

![image](https://user-images.githubusercontent.com/2756509/119916633-df2e7080-bf9f-11eb-974f-b8f2119ae586.png)
