### ISSUE TITLE
メニューテンプレート「マウスオーバードロップダウン（ルートのリンクなし）」にルートが表示されてない

### ISSUE THREAD

**Issue by dreamer9999** [opensource-workshop/connect-cms#278]
メニューテンプレート「マウスオーバードロップダウン（ルートのリンクなし）と（ルートなし）」の動作が同一で違いが無いように思えます。

![image](https://user-images.githubusercontent.com/3895089/78966996-32dfbf80-7b3c-11ea-8449-5df014403946.png)

**Comment by akagane99** [comment]
再確認してみました。

・現状、動きに違いなかったです。
・ルートのリンクなしが、ちょっとデザイン違う感じ。
・ルートのリンクなしで、ルートが表示されてないバグかなぁ？位です。

![image](https://user-images.githubusercontent.com/2756509/119917387-70521700-bfa1-11eb-843b-4f2e60836e81.png)

**Comment by kousei86** [comment]
「ルートのリンクなし」には 〈div class="card-body"〉が付いており、
「ルートなし」には付いていません。
　
そのため、「ルートのリンクなし」は
-------------
.card-body {
    -webkit-box-flex: 1;
    -ms-flex: 1 1 auto;
    flex: 1 1 auto;
    padding: 1.25rem;
}
-------------
のpadding の分だけ広く見えるようです。
　
両者の違いであろう、クラス「menus-mouseover_dropdown_no_rootlink」と
クラス「menus-mouseover_dropdown_no_root」に関わるスタイルの記述が
CSSファイルの中に見当たらないため、同じ見映えになっている気がします。

**Comment by akagane99** [comment]
いろいろ情報ありがとうございました。

> ・ルートのリンクなしが文字通りだと推測すると、ルートの「test」が表示されてないバグかなぁ？位です。

内部で確認したところ、上記バグでした。
今後修正しようと思います。

**Comment by akagane99** [comment]
マウスオーバードロップダウン（ルートのリンクなし）でリンクなしのルートを表示するよう修正しました。
クローズします。

## 画面
### マウスオーバードロップダウン（ルートのリンクなし）

※ ルートの「test」が押せなくて表示される事を確認しました。
![image](https://user-images.githubusercontent.com/2756509/120127147-89ed9b80-c1f9-11eb-8c2f-41e1372dbc32.png)


## 修正プログラム

https://github.com/opensource-workshop/connect-cms/commit/9918aa7f7e8885d450721fc9c01ac246bb4693ce
