### ISSUE TITLE
【フォームプラグイン：バグ】フォームの項目の必須をチェックするとエラーになる

### ISSUE THREAD

**Issue by yotaca** [opensource-workshop/connect-cms#284]
１）フォームプラグインを配置。
２）項目を設定し〝必須項目〟をチェック
３）編集した項目を更新
４）一番下の [xキャンセル] ボタンを押す

エラーが表示されます。

![スクリーンショット 2020-04-21 0 16 56](https://user-images.githubusercontent.com/8961306/79769146-b84a4780-8366-11ea-80be-042e0199bf5e.png)

**Comment by nagasheep** [comment]
@yotaca さん、バグ報告をありがとうございます。
他のも含めて、順次、修正していますね。
以上、まずはお礼まで。

**Comment by masaton0216** [comment]
@yotaca ご連絡をありがとうございます。
この件は、環境によってオートロードでphp標準のLocaleクラスとコネクトのenumクラスがバッティングしている可能性が濃厚ということで認知していたのですが、確証が持てず対応がおざなりになっていました。ご迷惑をおかけして申し訳ございません。

先程、修正をPUSHしました。
https://github.com/opensource-workshop/connect-cms/commit/f7d5e4ec5553f08fec363732d8a7845c6d4c3ca8

当方では、エラーが元々起きず、修正箇所の動確しか出来なかった為、ローカルで事象が解消されたかご確認を頂けますでしょうか？

**Comment by yotaca** [comment]
ありがとうございます。
今夜確認してみます。

**Comment by yotaca** [comment]
フォーム項目を必須にしてもエラーが出なくなりました。
しかし、データベースの並べ替え項目を指定しないとやはりエラーになります。
この件 #285 のほうへつなげておきます。

**Comment by masaton0216** [comment]
本件は解消したのでクローズします。
