### ISSUE TITLE
【データベース・バグ】並べ替え項目を指定しないとエラーになる

### ISSUE THREAD

**Issue by yotaca** [opensource-workshop/connect-cms#285]
１）データベースを作成しデータを入力
２）一覧表示時にスッキリ表示させるために
３）〝検索機能の表示〟〝絞り込み機能の表示〟を〝表示しない〟にチェック
４）〝並べ替え項目の表示〟の項目を全てチェックを外す
５）一番下の [レ変更確定] をクリックする

添付画像のようにエラーが表示される

![スクリーンショット 2020-04-21 0 52 41](https://user-images.githubusercontent.com/8961306/79772680-52ac8a00-836b-11ea-8f10-b1aa5f8656e9.png)

**Comment by yotaca** [comment]
フォームの方は直りましたが、データベースの方はエラー内容もそのままのようです。
#284

![スクリーンショット 2020-04-21 23 21 29](https://user-images.githubusercontent.com/8961306/79877258-fdce4980-8426-11ea-9a9b-825d89f1d125.png)

macos MAMP 5.7
PHP 7.3.1
MySQL 5.7.25

**Comment by masaton0216** [comment]
@yotaca こちらもご連絡ありがとうございます。内容からまた別のエラーのようですね。明日、少し見てみます。

**Comment by masaton0216** [comment]
@yotaca 対応しました。単純なnullチェック漏れでした。お手数をおかけして申し訳ございませんが、最新化して解消されるかご確認お願いできますでしょうか？
https://github.com/opensource-workshop/connect-cms/commit/5044c2e93215304f1dc8bf270f02017eca77eef1

**Comment by yotaca** [comment]
ありがとうございます。
明日確認してみて、連絡させていただきます。

**Comment by yotaca** [comment]
ご苦労様でした。
無事に動作しました。
クローズさせていただきます。
