### ISSUE TITLE
【要望：可能なら、、】データベースのフォーム

### ISSUE THREAD

**Issue by wai8605** [opensource-workshop/connect-cms#286]
芝浦工業大学　建築学部建築学科サイトにある様なデータベースのフォームがプラグインにあれば嬉しいです。
https://www.arch.shibaura-it.ac.jp/
https://www.arch.shibaura-it.ac.jp/shimizu-lab/information?frame_id=1424

**Comment by yotaca** [comment]
現在のデータベースの表示使われている table タグ を div か dl dt dd などに変更すれば css を書き換えるだけでレイアウトを変更することができるかと思います。

この辺を編集すれば行けそうな気がしますけど合ってますか？
resources/views/plugins/user/databeses/default/databases.blade.php

**Comment by nagasheep** [comment]
@yotaca さん、こんにちは。
永原です。

場所、あってますよ。
編集なのですが、そのファイルをそのまま編集しちゃうと、システムを最新にしたら、宇和が枯れちゃいますよね。
なので、まずは別のテンプレートを作ることをお勧めします。

以下にテンプレートの説明を書きました。
https://github.com/opensource-workshop/connect-cms/wiki/Template%EF%BC%88%E3%83%86%E3%83%B3%E3%83%97%E3%83%AC%E3%83%BC%E3%83%88%EF%BC%89

メニューが参考になると思います。

わからなければ言ってくださいね。
良い感じでtable を廃止できれば、yotaka さんのをデフォルトにできると嬉しいな。などと思ったりしています。（^^）

**Comment by yotaca** [comment]
ありがとうございます。
確認しながら作業をすすめてみます。

ただ、Laravel の仕様なのか、書き方が独特なので慣れるまでに時間がかかりそうです。
それとも Laravel を導入すべきなのでしょうか？

**Comment by nagasheep** [comment]
> それとも Laravel を導入すべきなのでしょうか？

ごめんなさい。
ここが理解できなかったです。
Laravel はConnect-CMS を動かすときには、必要なのですが、「導入」の部分がわからなかったです。

**Comment by yotaca** [comment]
外してたらごめんなさい。
開発環境として Laravel を使っているから、テンプレートなどを作成するときも Laravel を使う必要があるかと思い〝導入〟と表現させていただきました。

テンプレートなどはゴリゴリ手書きで書いても問題ないものなのでしょうか？

**Comment by nagasheep** [comment]
永原です。

Laravelって、Webアプリケーションのフレームワークなのです。

インストールした環境の
Connect-CMSのルートフォルダ/vendor/laravel
に入っていると思います。

CakePHP とか、NetCommons2 だと、Maple の部分にあたります。

開発環境は、単なるエディタです。
永原は秀丸のみ！（社内の若い連中はIDE をいろいろ使ってますが(笑)）

**Comment by akagane99** [comment]
listテンプレートで似たようなレイアウトが可能になったため、対応済みとしてクローズします。
https://github.com/opensource-workshop/connect-cms/tree/master/resources/views/plugins/user/databases/list
