### ISSUE TITLE
データベースプラグインで日付型のチェック処理の設定が機能しない

### ISSUE THREAD

**Issue by wai8605** [opensource-workshop/connect-cms#287]
データベースプラグインで日付型のチェック処理の設定が機能しないように思えます。
当方環境：xampp 、（connect-cmsは本日アップデート）

＜作業＞
データベースプラグインで日付型選択後、本日4/22を起点にし

1.詳細の「指定日数以降を許容」を「1」に設定
2.日付入力欄に「2020/4/23」と入力

すると下記エラーが発生しました。（2020/4/22 でも同様にエラー）

＜エラー＞
![DB日付エラー90k](https://user-images.githubusercontent.com/3895089/79975204-915e5380-84d5-11ea-9b76-abe62c5cc430.jpg)

**Comment by masaton0216** [comment]
@wai8605 ご連絡ありがとうございます。バグっぽいですね・・・ｗ
明日以降、手すきの時間に確認させて頂きます。まずはお礼まで。

**Comment by akagane99** [comment]
再確認したところ、症状でなくなっていたので、どこかで直ったようです。
クローズします。
