### ISSUE TITLE
【データベースプラグイン】でファイル型が機能しないかもしれないです

### ISSUE THREAD

**Issue by dreamer9999** [opensource-workshop/connect-cms#288]
データベースプラグインでファイル型が機能しないかもしれないです。
（当方の手順が違っていたらスイマセン、、、）
＜作業＞
1.データベースプラグインでファイル型選択
2.テキストファイルを選択して、「確認画面へ」ボタンを押すと下記エラー発生。
＜エラー＞
![ＤＢファイル添付90k](https://user-images.githubusercontent.com/3895089/79983154-50207080-84e2-11ea-8187-8fa4ddca770c.jpg)

**Comment by masaton0216** [comment]
@wai8605 ご連絡ありがとうございます。こちらもバグっぽいですね・・・ｗ
明日以降、手すきの時間に確認させて頂きます。まずはお礼まで。
