### ISSUE TITLE
Connect-CMSオンライン勉強会【 2020-04-27】

### ISSUE THREAD

**Issue by nagasheep** [opensource-workshop/connect-cms#289]
@yotaca さん
こんにちわ。永原です。
（これでメンションになって、メール飛ぶのかな？）

オンラインで、Connect-CMS 勉強会＆質問会しません？
OSC などのイベントも中止になっていく中、いまの選択肢として、オンラインでの活動はアリかなと思って。
まあ、最初は雑談程度からでも(笑)

OK。一回、やってみようということでしたら、返信ください。
Zoom のパスワード付けたURL 送ります。

以上、まずは思い付きですが。

**Comment by nagasheep** [comment]
永原です。
Zoomのアカウント無くても大丈夫ですよ。
ホスト（永原）がアカウント持ってればOKです。
日程、いつが良いですかね。
うちのメンバー-にも聞いてみます。

**Comment by yotaca** [comment]
了解です。
今の所、27日の月曜日がよさそうです。

**Comment by nagasheep** [comment]
了解です。
では、27日（月）14:00 とかでいかがです？
いま、午前中は子供の勉強見ながら仕事しているので、打ち合わせ的なものは午後にしたくて(笑)

**Comment by yotaca** [comment]
了解。楽しみです。やれることはやっておきますね。

**Comment by nagasheep** [comment]
はーい。
別途、Zoom のURL 送りますね。
まあ、最初なので、ゆるく行きましょうよ(笑)

**Comment by yotaca** [comment]
チェックしました。ありがとうございます。

**Comment by Sasaki-EddyK** [comment]
わたしも参加させてもらっていいですか。ただし、カメラ・マイクもないので拝聴とテキストでの参加になりますが・・・
検討願います。

**Comment by akagane99** [comment]
牟田口も仕事しながら参加しようかと。
あんまり反応できないかもでが

**Comment by nagasheep** [comment]
@Sasaki-EddyK 
もちろんどうぞー。
後でメールの方にZoom にURL とパスワード送りますね。
> カメラ・マイクもない
あら。意外。
スマホやタブレットでも参加できますよ。

**Comment by Sasaki-EddyK** [comment]
ありがとうございます。楽しみにしています。

**Comment by nagasheep** [comment]
2020-04-26 当日のレジメ追記（全部話せるかわかりませんが(笑)）

準備：当日、Googleドキュメントのリンクを共有します。
Googleアカウントのある方は編集権限をリクエストしていただければ、編集を許可するようにします。

1.	永原からご挨拶とConnect-CMSの目的 
o	持続可能なオープンソースCMS経済圏を構築できるかの挑戦
o	フリーライダー問題の解決
o	持続可能で資金が循環する貢献活動の構築
2.	自己紹介 
o	簡単でも良いので、参加者の自己紹介。
o	職場に関しては守秘義務なども考慮していただいて無理のない範囲で。
3.	現状報告 
o	開発の現状報告
4.	ロードマップ 
o	非公開ページ（メンバーシップページ）
o	コアの見直し
o	必須プラグイン開発
5.	他システム・CMSからの移行 
o	NetCommons2からの移行
o	NetCommons3からの移行
o	HTMLサイトの取り込み
o	その他CMSからの移行
6.	コミュニティ活動 
o	当面オンラインで実施
o	テーマ販売
o	コミュニティの法人化
7.	お願い
o	専門的知識からの体型だった貢献
o	ビジネスでの連携
o	開発への参画（方法も含めて議論できれば）
8.	デザイン 
o	Bootstrap
o	フォントアイコン
o	テーマ
o	プラグイン・テンプレート毎のCSS
9.	Connect-CMSのまだ一般公開していない機能の紹介 
o	API連携
o	IoT連携
o	Hook機能（プラグイン開発者向け）
10.	その他 
o	質問や要望
o	その他自由に。

**Comment by nagasheep** [comment]
一旦終了したのでClose
