### ISSUE TITLE
【データベースプラグイン】で登録日等が機能しないかもしれないです

### ISSUE THREAD

**Issue by wai8605** [opensource-workshop/connect-cms#290]
【データベースプラグイン】で登録日等が機能しないかもしれないです。
（登録日等とは登録日（古/新）・更新日（古/新）・ランダム（ｾｯｼｮﾝ/毎回）の６項目）
※登録日等の実際の用途を理解していませんので間違ったことをしているかもしれませんが、、

＜手順＞
項目を設定後、新規登録を行うと、そのたび下記と類似のエラーが出ます。

＜エラー（登録日（古い順））の場合＞
・エラー画面前半
![古い順90k](https://user-images.githubusercontent.com/3895089/79997823-ebbadc80-84f4-11ea-90d0-2090bda4a19b.jpg)
・エラー画面後半
![古い順2_90k](https://user-images.githubusercontent.com/3895089/79997856-f5444480-84f4-11ea-85a4-139be7805d85.jpg)

**Comment by akagane99** [comment]
https://github.com/opensource-workshop/connect-cms/issues/395
上記で対応済み
