### ISSUE TITLE
【要望：データベース】動画・画像のアップロード最大容量と動画の表示画面サイズ指定

### ISSUE THREAD

**Issue by dreamer9999** [opensource-workshop/connect-cms#292]
【データベース】で、動画・画像のアップロード最大容量をどこかに明示してほしいです。
また、動画の表示画面サイズを指定できれば、いいな、と思います。

**Comment by akagane99** [comment]
データベースで、登録・編集で表示するキャプションに、最大アップロードサイズを表示できるように対応しました。

## 画面
### データベースの項目詳細設定

![image](https://user-images.githubusercontent.com/2756509/118811152-a0d1eb00-b8e7-11eb-80a2-3fe45bf2c06c.png)

### データベースの登録・編集画面

![image](https://user-images.githubusercontent.com/2756509/118810985-6ff1b600-b8e7-11eb-9835-3a0a403973ae.png)


## 修正プログラム

https://github.com/opensource-workshop/connect-cms/commit/1d9e6e8d6ff1d402ea232cf269537072fac5c976

**Comment by akagane99** [comment]
対応済のため、クローズします
