### ISSUE TITLE
【データベース】検索機能でエラー

### ISSUE THREAD

**Issue by dreamer9999** [opensource-workshop/connect-cms#293]
本家本元のサイトでは正常に検索が機能しているので、当方の設定間違いかと思いますが、何かの参考になればと思い、当方でのエラーを投稿させていただきます。
（https://connect-cms.jp/plugin/databases/search/62/142）

＜検索画面＞
![検索実際90k](https://user-images.githubusercontent.com/3895089/80049253-56980200-854d-11ea-9c1a-d54fdd393126.png)

＜エラー＞
・前半
![検索1_90k](https://user-images.githubusercontent.com/3895089/80049296-73343a00-854d-11ea-8d15-5211aa104a74.png)
・後半
![検索2_90k](https://user-images.githubusercontent.com/3895089/80049324-82b38300-854d-11ea-85f4-de2e27b750d1.png)

**Comment by nagasheep** [comment]
@wai8605 さん、バグ報告をありがとうございます。
順次、修正しています。
いまのところ、予定としての日程までは立てられない状況です。

以上

**Comment by wai8605** [comment]
プログラムの力量は無いので、素人の1ユーザーの立場から運用してみて、気が付いたところを投稿させていただきたいと思っています。
（素人ゆえ、方向違いの投稿をしてしまったら、スイマセン、、、）
もし、少しでも、connect-cmsのお役に立てれたとしたら、嬉しいです、、、
