### ISSUE TITLE
【要望：新着情報】で選択プラグインをblogのみでなく他のプラグインも選択できるように、、

### ISSUE THREAD

**Issue by dreamer9999** [opensource-workshop/connect-cms#294]
新着情報では現在、選択プラグインがblogのみとなっていますが、固定記事など他のプラグインも選択できるようにするほうが良いかなと思います。
（blogのみにしているのには、私には推し量ることができない技術的な理由があるかもしれませんが、もし可能なら、、、）

**Comment by nagasheep** [comment]
今後、対応していく予定です、他のプラグインも同様です。
ということで、このIssuee は一旦クローズします。
