### ISSUE TITLE
【知識募集】TinyMCEのlistsプラグインで複数書式を選択できるようにする方法

### ISSUE THREAD

**Issue by nagasheep** [opensource-workshop/connect-cms#296]
こんにちは。
株式会社オープンソース・ワークショップの永原です。

TinyMCEのlistsプラグインで複数書式を選択できるようにする方法、誰か教えていただけないでしょうか？
どうもよくわからなくて。
TinyMCE のバージョンは4 です。

**Comment by Sasaki-EddyK** [comment]
ささきです。
/resources/views/plugins/common/wysiwyg.blade.php　の83行目に「advlist」のプラグインを追加すれば、書式選択ができるようになります。

**Comment by nagasheep** [comment]
ささきさん

ありがとうございます。
できました。(^^)/

ということで、Push もしました。

以上、このIssue はClode しますね。
