### ISSUE TITLE
cms_frame_base.blade.php からstyle を消す

### ISSUE THREAD

**Issue by yotaca** [opensource-workshop/connect-cms#301]
うまくブランチが思うように作れないので、こちらに書きます。

style の直書きだと css でのコントロールができないので、bootstrap のクラスを指定お願いします。
resources > views > core > cms_frame_base.blade.php 13 行目

&lt;div class="card-body" style="padding: 0; clear: both;"&gt;
　↓
&lt;div class="card-body clearfix p-0"&gt;

以上

**Comment by nagasheep** [comment]
永原です。
調査＆修正依頼、ありがとうございます。
しかし、ここで永原が修正してしまっては、修正依頼を受け付けて修正する流れができてしまうので、ブランチができるまで、サポートしたいと思います！
とりあえず、以下のページで、Web ブラウザ上でのブランチの作成方法が載っていました。
https://howpon.com/5181
これでダメなら、オンライン会で一緒にやりたいと思いまーす。

**Comment by masaton0216** [comment]
@yotaca さんにブランチ作成の権限がないとか？出先なので確認できないのですが、プルリクの作成は何もブランチからonlyな訳ではないです。
fork（自分のリポジトリとして複製する）して、コネクトのリポジトリにプルリクすることもできます。
https://help.github.com/ja/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

**Comment by yotaca** [comment]
ありがとうございます。
なんとかブランチは作れるのですけど〝修正が反映〟されていないんです。

どうやら、
opensource-workshop/connect-cms の master の更新が
yotaca/connect-cms の master に 反映されないみたいです。

ただいま一度ブランチを削除して試している最中です。

具体的なことを書くと
opensource-workshop/connect-cms の lastest commit は 『nagasheep ヘッダーエリアmd隙間調整』ですが、
yotaca/connect-cms の lastest commit は 『masaton0216 Enum 環境によってphp標準Localeクラスとオートロードでバッティングする為、クラス名変更』のままです。

ファイルの更新を自分の master に反映させるためにとりあえず手動で行っておりますが、
lastest commit が変わってないところを見ると、違うみたいですね。

この辺の画面でなんとかできないものでしょうか？

![スクリーンショット 2020-05-02 21 40 28](https://user-images.githubusercontent.com/8961306/80864454-bd3fbd00-8cbd-11ea-937c-1312f5187ad4.png)

**Comment by yotaca** [comment]
とりあえずこのリクエストは届きましたか？

![スクリーンショット 2020-05-02 23 04 35](https://user-images.githubusercontent.com/8961306/80866389-558f6f00-8cc9-11ea-9e06-1a70806b58af.png)

**Comment by nagasheep** [comment]
yotacaさん、こんにちは。
永原です。
> とりあえずこのリクエストは届きましたか？
Github からのシステム的なリクエストという意味なら、何も届いていません。
永原も、テスト用のGithub アカウントとか作って試してみますね。

**Comment by yotaca** [comment]
この辺が鬼門ですね。
引き続きよろしくお願いいたします。

**Comment by akagane99** [comment]
@yotaca さんこんにちは。

> opensource-workshop/connect-cms の master の更新が
> yotaca/connect-cms の master に 反映されないみたいです。

こちらはご自身で最新化しないと、forkしたリポジトリは最新にはならないんです。
この動きはgitの仕様なんです。
ネットで下記記事がありましたので、見てみてください。

forkしたリポジトリを更新する方法 - Qiita
https://qiita.com/taoki11111/items/6582dafeb971f66d1f79

プルリクエストが「opensource-workshop/connect-cms」に来たかは、下記リンク or 「opensource-workshop/connect-cms」の「Pull request」タブで確認できます。参考まで。
https://github.com/opensource-workshop/connect-cms/pulls

**Comment by nagasheep** [comment]
永原です。

以下のページに。Webページ上で直接、コードを修正し、Pull Request までする方法を記載しました。
これでどうでしょうか？
https://github.com/opensource-workshop/connect-cms/wiki/Pull-Request%EF%BC%88Web%E7%94%BB%E9%9D%A2%E4%B8%8A%EF%BC%89

永原のテストで、class を追加しちゃいましたが、style はまだ、削除していません。

**Comment by yotaca** [comment]
git のコマンドを触っているうちに、ローカルで追加したファイルが消えてしまいました。
Timemachineでファイルを復元しましたけど、ローカルのディリクトリを認識してくれなくなりました。
とりあえず一度ファイルを避難させて再インストール覚悟でリセットしてみます。

追伸：class に "p-0" を追加してください。

**Comment by masaton0216** [comment]
@yotaca git＋GitHubは最初は調べてても言葉の立ち位置がどの辺なのかわかりづらいかと思ったのでスライドで表現したPR（プルリクエスト）開発のイメージです。
私の知ってる範囲だと２パターン（フォークして自分のリポからPR飛ばす、本家リポ内でブランチ切ってPR飛ばす）あります。
ローカルに関してはワーキングツリーやステージング等、もう少し複層的なのですが、そこは今回は省略しています。大枠でイメージ把握の足しになれば幸いです。
[GitHub－PR開発イメージ.pptx](https://github.com/opensource-workshop/connect-cms/files/4570142/GitHub.PR.pptx)

**Comment by yotaca** [comment]
ごめんなさい。また操作間違ったみたいです。
返事しようとして、close してしまいました。

**Comment by yotaca** [comment]
git を使うときは、
自分のリポジトリの master ではなくブランチを分けて作業するのは、
元のmaster の変更内容を反映しやすいからですか？

それとも、必須ですか？
