### ISSUE TITLE
GitHub の使い方など

### ISSUE THREAD

**Issue by yotaca** [opensource-workshop/connect-cms#304]
ごめんなさい。
返事しようとしたのですが、誤ってclose してしまいました。

@masaton0216 
スライドまで作っていただき、ありがとうございます。

git を使うとき、
自分のリポジトリの master ではなくブランチを分けて作業するのは、
元のmaster の変更内容を反映しやすいからですか？
それとも、必須ですか？

**Comment by yotaca** [comment]
なんとかローカルを復旧することができました。
ここでいくつか困っております。

１）master (#297) メンバーシップページへのファイルアップロード等
２）master (#297) ページ参照時の制御＆メニュー制御

この２つのうちどちらかを反映させるとエラーになります。

db のレイアウトを整えるためにニューブランチ『hnmskins_db_layout』を作成しました。
さっそく、ブランチを切り替えたて作業を開始したのですがやはりエラーになります。

エラーの見方がわかればなんとかなるかと思いますが、まだかかりそうです。

こう行った場合のヒントがあれば教えていただけますでしょうか。

**Comment by masaton0216** [comment]
@yotaca 
新しいbrunchにmasterの最新を取り込もう（マージ）としたがエラーになっている、という状況でしょうか？エラーの内容ここに貼れますか？
また、マージですがgitのmergeコマンド使ってやってますか？masterの更新内容見ながら手でcommitしても別のcommitと見なされるので、競合（conflict）します。
https://bake0937.hatenablog.com/entry/2017/11/07/081616

**Comment by masaton0216** [comment]
@yotaca ブランチを分けるのは、masterブランチは安定動作が保証されるべきブランチだからです。（リリースタグを切ったりすべきなのですが、そこまで運用ポリシーが決めきれていない為、ご不便をおかけします。）
Connectは既に商用環境で稼働しているところがある為、ノーレビューのcommitをmasterにいきなりpushするのはリスキーなことかと思われます。

**Comment by yotaca** [comment]
上流からのマージですけど github 上で
opensource-workshop/connect-cms master の更新内容が 
yotaka/connect-cms master へ反映されないので 仕方なく元ファイルをダウンロードさせてました。

[Able to merge.] These branches can be automatically merged.

こう記載してあったの自動でマージしてくれると思ったのですが違うみたいですね。
お手数をかけますが、
opensource-workshop/connect-cms master から
yotaka/connect-cms master へ反映させる手順を教えていただけますか。

**Comment by masaton0216** [comment]
@yotaca 手順はこちらの記事が参考になるかと思います。先日のパワポの3枚目のイメージです。
https://qiita.com/taoki11111/items/6582dafeb971f66d1f79

**Comment by yotaca** [comment]
ありがとうございます。
git の更新はアプリ使うよりも、コマンドラインの方が確実みたいですね。
おかげで無事にローカルまで更新できたようです。

ただ、ブラウザでアクセスすると、エラーで『Base table or view not found: 1146 Table 'hnm_connectcms.groups'』と表示されました。
どうやら、2020_04_11_075532_create_groups.php が実行されてないようです。

気になって他のファイルも見たところ、4/2以降のデータベースのテーブルが作成されていませんでした。
これらのテーブルはどのタイミングで作成されるのでしょう？

もしくは手動でテーブルを作成しても大丈夫なのでしょうか？

**Comment by yotaca** [comment]
laravel の仕様だと思って調べてこちらのページを参考にして作業しました。
https://readouble.com/laravel/7.x/ja/migrations.html

# php artisan migrate

In Connection.php line 664:
SQLSTATE[HY000] [2002] No such file or directory (SQL: select * from information_schema.tables where table_schema = hnm_connectcms and table_name = migrations)                                                                 

In Connector.php line 67:
SQLSTATE[HY000] [2002] No such file or directory

どうやら接続がうまくいっていないようです。

**Comment by yotaca** [comment]
config / database.php の 55行目に unix_socket を追加してなんとかテーブルを追加することができました。
'unix_socket' => '/hoge/hoge/mysql.sock', //この行を追加

$ php artisan migrate

ただし登録していたデータベース（プラグイン）のデータが全て跳びました。
サイドメニューでエラーが出ているのでまたファイルを辿って修正します。

今日は力尽きたのでもう休みます。

**Comment by yotaca** [comment]
とりまエラー内容だけ送ります。

Method Illuminate\View\View::__toString() must not throw an exception, caught ErrorException: Call to a member function getFolderOpenFont() on null (View: /Users/yotaka/www/html/github/connect-cms/resources/views/plugins/user/menus/opencurrenttree/menus.blade.php)

![スクリーンショット 2020-05-05 5 33 08](https://user-images.githubusercontent.com/8961306/81010936-06e10100-8e92-11ea-946b-6965a4b12d06.png)

**Comment by yotaca** [comment]
エラー個所がわかりました。
/resources/views/plugins/user/menus/opencurrenttree/menus.blade.php

37行目{!!$menu->getFolderCloseFont()!!}
39行目{!!$menu->getFolderOpenFont()!!}

おそらくアイコンフォントの指定だと思うのですが、これ以上追いかけられそうにありません。
とりあえず当方では違うメニューテンプレートを使用して作業を続けます。

他の方の環境でもエラーがでているようでしたら別スレ立てます。

**Comment by nagasheep** [comment]
こんにちは。
永原です。

ごめんなさい、これは普通にバグですね。
修正します。

とりあえずの対処方法は以下にこのバグ用の別スレッド立てて書きました。
https://github.com/opensource-workshop/connect-cms/issues/306

**Comment by yotaca** [comment]
@nagasheep 
ずっとファイルがちゃんと更新されなかったのでそのからみのエラーかと思ってました。
今回、役に立てて何よりです。
まだまだ、迷惑かけるかとおもいますがよろしくお願いします。

**Comment by nagasheep** [comment]
まだまだバグも多くて申し訳ないです。<m(__)m>
Connect-CMS のアップデート方法も慣れていかなきゃいけないですよね。
以下のページに、アップデート方法を書いています。
https://github.com/opensource-workshop/connect-cms/wiki/Update-%28%E3%82%A2%E3%83%83%E3%83%97%E3%83%87%E3%83%BC%E3%83%88%29

**Comment by masaton0216** [comment]
@yotaca 遅くまでお疲れ様でした。LaravelはDDLもプログラムコードとして保持する思想です。なのでプログラムを最新化したら、ご推察のmigrateコマンドも実行必須です。
`php artisan migrate`

migrationsテーブルにどこまでmigrateを実行したのか履歴を保持しており、最新化ソースとの差分だけ実行します。

但し、このmigrateコマンドも色々と種類があって、中には既存データを吹き飛ばして差分関係なくゼロから再構築するようなコマンドもあります。
`php artisan migrate:fresh`

gitの部分もLaravelの部分の躓きも事始めあるあるな内容なので、ある意味、いい感じで慣れていけてると思います。

バグも見つけて頂きありがとうございました。

**Comment by masaton0216** [comment]
@yotaca 1点気になってるのが、下記の追加です。
`unix_socket`
環境構成が違うせいかなと思いますが、永原も井上もそこの追加はなしで動いているので、これもcommitに含まれているとしたらプルリクエスト頂いた段階で取り込みOKな内容か精査する必要があると考えています。

**Comment by nagasheep** [comment]
永原です。

https://github.com/opensource-workshop/connect-cms/issues/306
のバグに関しては修正してPush しました。
教えていただき、ありがとうございました。

unix_socket の件は、まず、@yotaca さんと我々は環境が違うんだろうなと思っています。
永原は、Windows ＋ XAMPP 及びLinux（CenteOS、Amazon Linux：どちらもRedhat系）で動作させていますが、unix_socket の設定は特にやっていません。
OS というより、MySQL の設定かも知れないですね。
もういえば、Windows ＋ XAMPP はMariaDB でした。
とりあえず、こっちの環境の報告だけ。

以上

**Comment by yotaca** [comment]
unix_socket ですが、環境の影響だと思います。

詳細を書くと　macos ではデフォルトで PHP5.6 が動いております。
素直にこのPHPのバージョンを上げていけばいいのですが、如何せんアップグレード時にエラーが出る可能性があります。

そこで、対応方法として２つ考えられます。
1.MAMP で PHP7.3 を指定する。
2. Homebrew などで別途 PHP7.3 をインストールして各設定を変更する。

私の場合は設定変更がやりやすい MAMP を使っております。
ほとんどのCMSなどはこれで PHP7.3 が使用できるのですが、
今回のような コマンドラインでは PHP5.6 が優先して動作してしまいます。

そこで、MAMP の PHP7.3 を使うように設定を書き換えて使用しておりますが、
設定の全てを書き換えた訳ではないらしく、unix_socket を明示しないといけない場面があるようです。

個人的な意見ですが unix_socket については tips としてマニュアルに記載してあれば良いのではないでしょうか。

git はまだ掛かると思いますが、
laravel については調べ方がなんとなく掴めてきました。

正直なところローカルで作成したサイトをサーバーにあげるのが大変な気がしてます。

これからもサポートよろしくお願いします。
