### ISSUE TITLE
ブログの表示条件設定

### ISSUE THREAD

**Issue by cocoluca** [opensource-workshop/connect-cms#307]
ブログの「表示条件設定」で「指定年」は複数設定できないなでしょうか？
例えば、「2020年」と「2019年以前」に表示を分けたい場合はどうしたら良いのでしょうか？

**Comment by nagasheep** [comment]
永原です。

ブログの表示設定で、複数年を指定することは考えていなかったですね。
複数年というだけなら、年をカンマ区切りで指定するなどもアリかなと思えますね。
「2019年以前」はカンマ区切りでは難しいですね。
「>=2019」とか「<2020」などの指定方法を検討する必要がありますね。
これはこれで有用な機能かなと思います。
実装はちょっと後になりそうです。
