### ISSUE TITLE
Opac（蔵書管理）のエラー

### ISSUE THREAD

**Issue by dreamer9999** [opensource-workshop/connect-cms#309]
当方環境、アップデート済です
Opacプラグインで新規蔵書登録する際、エラーが出ましたので、ご参考までに投稿させていただきます。（当方の操作間違いの場合はご容赦ください）
※なお、使用ISBN9784764905757の書名は「ネットコモンズ公式マニュアル」です。

■当方作業

![opac登録画面](https://user-images.githubusercontent.com/3895089/81069849-69cbaa00-8f1d-11ea-85b2-c7e96110ca53.png)

■エラー画面前半

![opac](https://user-images.githubusercontent.com/3895089/81069919-8536b500-8f1d-11ea-904a-7efcbf5f251c.png)

■エラー画面後半

![opac2](https://user-images.githubusercontent.com/3895089/81069986-9aabdf00-8f1d-11ea-85df-1bc6966ae574.png)

**Comment by akagane99** [comment]
再確認しました。
直っていましたのでクローズします。
