### ISSUE TITLE
【要望】横幅一杯のページレイアウト

### ISSUE THREAD

**Issue by wai8605** [opensource-workshop/connect-cms#310]
もし可能でしたら、ページ管理で、下記サンプルのような横幅一杯のページレイアウトがあれば嬉しいです。

（サンプル）eddykさんがつくられたサイト
https://demo-nc3.eddy-k.jp/page_20190505014447

**Comment by yotaca** [comment]
スクロールの速度を変更するスクリプトはともかく、
レイアウト自体は、専用のテンプレートを作成すればそれほど難しくないと思います。

個人的には、テーマやプラグインの配布方法が確立されれば、優先度を上げてみたいです。

**Comment by nagasheep** [comment]
永原です。
横幅いっぱいのレイアウトは実現できています。
以下のページで説明しています。
https://connect-cms.jp/manual/common/frame-setting/width100
この例ではヘッダーのみ横幅いっぱいですが、メインエリア、フッターも同じように設定可能です。

**Comment by wai8605** [comment]
スイマセン、横幅いっぱいのレイアウトの説明を見逃していました。

その説明でわからないところありましたので下記の質問させていただきたいです。


＜画像を横幅いっぱいのレイアウトにする時の作業手順＞

①固定記事プラグインに画像をアップロードする。
（下記例：固定記事プラグインに画像をアップロードしたときのソースコードの例）

img src="/file/43" width="500" height="329" class="img-fluid" alt=""

②説明の通り、この固定記事プラグインのフレーム幅100％に設定し、また、説明にあるclass名をそのまま使うとして、class名を「eyecatch」と登録する。

③「テーマのCSS例」を実際の画像jpgに変更して記載
.eyecatch {
  padding: 0;
  background: url("test_bg2.jpg") no-repeat;
  background-size: cover;
  margin-bottom: 50px;
}

ここで質問ですが、
・「テーマのCSS例」はどこに記載するのか、
（public/css/connect.cssかな？もしそうなら、アップグレードするたびに書き換える？）
・アップロードした画像img src="/file/43" に対して、url("test_bg2.jpg")の対応関係がわからないです、、、

以上、初歩的な知識の欠如、また、変なこといってる質問哉もしれませんが、素人に免じてご容赦いただければ幸いです。

**Comment by yotaca** [comment]
固定記事プラグインにそのまま画像を配置しただけでは、見本のレイアウトは再現できないのではないでしょうか？
＊タグの挙動、style の指定方法、z-index の明確化、position や位置の指定方法などからそう感じてます。
配置画像を背景画像に使うような専用のテンプレートを新規作成すればそれほど難しくはありません。
ただ、この案件は default のレイアウトが固定された後のオプションと考えた方がよろしいかと。

**Comment by wai8605** [comment]
邪道かもしれませんが、固定記事プラグインに画像を配置するとき、横幅を1200PXとか、必ず画面をオーバーするような値で画像を設置すると、元の画像とおりに調整されて見た目には横一杯の画面ができました。
※果たして、この様な運用が許されるかはわかりませんが、、、

（ソースコード）
img src="/file/54" width="1200" height="524" class="img-fluid" alt=""

（実際の画面）
![横一杯](https://user-images.githubusercontent.com/3895089/81168715-7827cd80-8fd2-11ea-911f-0357f56cf113.png)

**Comment by Sasaki-EddyK** [comment]
固定記事に画像を載せてしまったら文字など簡単に上に載せれないので画像はあくまでもバックグラウンドに使用すべきと思います。CCMSではページにテーマを指定し、フレームにそのテーマに記述したclassを指定。テーマは管理画面のテーマ管理で独自テーマのCSSとjavascriptを編集できます。
よくできていますね。
wai8605さんのこの画像をcssのバックグラウンドで記述すれば、固定記事では上に載せる文言のみ記載すれば期待されるものができるのではと思います。

ただ、CCMSではテーマは独自で作れるので、装飾なしのテンプレート（プラグインの出力様式）の充実が必要なのかなあと勝手に考えてしまいます。（すみません）

**Comment by wai8605** [comment]
https://github.com/opensource-workshop/connect-cms/wiki/Theme（テーマ）
上記記事、yotaca様、Eddyk様のお話しなどを参考にさせていただいて、再度挑戦してみました。

ローカル環境、connect-cms/public/themes/Users/Sample下にて、
・Sampleフォルダの中身は既存のDefaluts/Blueの中身をそのまま複写
・themes.ini はtheme_name = Sampleに変更、
・themes.cssにCSSの例（.eyecatch)を追記、
（https://connect-cms.jp/manual/common/frame-setting/width100）

![横一杯2](https://user-images.githubusercontent.com/3895089/81250830-e1542300-905c-11ea-8e7c-9649d8ab4e67.png)


①管理画面のテーマ管理でユーザーテーマSampleを設定、画像を設定。
②サイト管理 ＞ レイアウト設定で100％を設定
③ページ管理で該当ページにテーマSampleを指定
④固定記事プラグインを追加し、フレーム編集にてclass名eyecatchを指定

上記実行しましたが、横一杯の画像設定できませんでした。

素人には、まだ敷居が高い気がしてます。（私だけかも？）
後日、再挑戦したいとおもっています。

**Comment by yotaca** [comment]
z-index でレイヤーを下層に移動させたり、ポジションで位置決めしないと難しいかもしれません。

また、z-index についても bootstrap 内でのルールがあり、この CMS 内でもルールがあると思うので、好きなレイヤーを指定できないと思います。

レイヤーをいじるデザインは腰を据えて行わないと、汎用性が失われるので今の段階で組み込むのは現実的ではないと思います。

もし、急ぎでやりたいのであれば固定記事に下記スタイルを指定してみてはいかがでしょう？

&lt;style&gt;&lt;!--
body{
background-image: url(/file/00);
}
--&gt;&lt;/style&gt;

url は配置画像のソースです。
このままでは勝手にリピートしますので、他の調整などは任意で行ってみてください。

**Comment by wai8605** [comment]
yotacaさん、ありがとうございます。
特に急いでるわけでないので、時期を待ちます、、

**Comment by Sasaki-EddyK** [comment]
特にFTPなど必要なくテーマ管理でテーマが作成できます。テーマ名は全角でも問題ありません。ディレクトリ名がwai8605さんでの「Sample」となります。
そこでCSS・画像の登録を行います。

CSSは
.img-box {
	min-height: 300px;
	margin: 0;
	background: url(/themes/Users/ディレクトリ名/images/登録した画像ファイル名) 50% 0 no-repeat fixed;
		background-position-x: 50%;
		background-position-y: 0px;
		background-size: cover;
		background-attachment: fixed;
}

ページの設定でテーマを指定、フレームの設定でクラスに「img-box」を指定、「フレーム表示設定」は特に100%を指定しなくても大丈夫です。
上に載せるコンテンツは他コンテンツと同じ幅になります。

結果
![背景1](https://user-images.githubusercontent.com/33592430/81307539-bea52700-90bb-11ea-92e7-5e68df018b7a.jpg)
の様になりました。

このようにテーマ作成に関してはとても簡単にできるようになっているのですね。
すばらしいCMSですね。

**Comment by wai8605** [comment]
Sasaki-EddyK さんの通り実行しましたら、完成しました。
ありがとうございました。

＜完成品＞
![横一杯完成_小](https://user-images.githubusercontent.com/3895089/81465192-169a7580-9203-11ea-8a3a-becad0e72285.jpg)

ただ気になることがありました。
テーマチェンジャープラグインで、ヘッダを黒色に設定すると、画像が消えます。
履歴を削除すると、上記＜完成品＞が再び現れます（テーマチェンジャーのヘッダの黒色にはならない、、、テーマがらみでテーマチェンジャープラグインとの両立はできない？ということなのでしょうか、）

＜テーマチェンジャープラグインで、ヘッダを黒色に設定＞
![横一杯完成_消える](https://user-images.githubusercontent.com/3895089/81465285-f61eeb00-9203-11ea-9243-7e1c6dccf7b8.png)


今振り返ると、初心者のわたくしにとっては
https://connect-cms.jp/manual/common/frame-setting/width100
でのマニュアルは、テーマ管理、ページ管理でのテーマ項目記載の説明が無くてとまどい、勝手にヘンなことをやっていたんだな、と思う次第です。（プロの方は、わかるのですね、、）
プロの方々は、本体開発途で細かいところまでは手が回らないかと思います。
もし、私でも、初心者観点からの、マニュアル作成、操作確認など、今後、少しでもお役に立てることができるとしたら幸いです。

**Comment by wai8605** [comment]
「テーマチェンジャープラグインで、ヘッダを黒色に設定すると、画像が消えます。」は私の設定間違いでした。
テーマチェンジャープラグインでヘッダの色と共に、テーマをユーザーテーマに設定すれば、問題ありませんでした。
お騒がせしました、、、
