### ISSUE TITLE
【プラグイン：データベース】項目ごとに class をつけたい

### ISSUE THREAD

**Issue by yotaca** [opensource-workshop/connect-cms#311]
いま、データベースプラグインの表示をいじっております。

bootstrap4 でいうところの〝card〟形式で表示させたり、リスト表示させたりしようと思っています。
これを実現するにあたって、現在は擬似クラス nth-child(n)で作成しておりますが、再現性が乏しいので項目ごとに class を指定した方がいいと思ってます。

さて、ここで問題なのはDBを触ることになると思います。
しかし、前回の更新でdb吹っ飛ばしたてしまい自信がないので、よかったらだれか、migrationsファイルを作成していただけませんか？

**Comment by nagasheep** [comment]
永原です。

なるほど。
項目毎のClass設定、良いですね。
migrations ファイルを作っておいたら、PHP ソースのカスタマイズ、してもらえる感じです？
（とっても嬉しいです！）
migrations ファイルは準備します。

**Comment by yotaca** [comment]
今やっている最中なのでわりと早くお見せできると思います。
よろしくお願いします。

**Comment by nagasheep** [comment]
Class名（classname）を追加したmigration ファイルをPush しました。

永原の開発環境では問題なく反映できました。
git pull
php artisan migrate
で反映してください。

いまから１時間ほど、反応できません。

以上、よろしくお願いいたします。

**Comment by yotaca** [comment]
ありがとうございます。だいぶ慣れてきました。
フォームにもクラス名を入れるところを作る必要がありますね。
一休みしてからかかります。

**Comment by nagasheep** [comment]
永原です。

> フォームにもクラス名を入れるところを作る必要がありますね。
問合せフォームなどのフォームプラグインということですよね。

こっちも、デザイン的に何かできる。ということなのですよね？
データベースプラグインの場合は、レイアウトや項目毎の装飾などでClass 名が必要かなとは思ったのですが、フォームプラグインの場合、使い方がまだ、想定できなくて。
お手数ですが、そこのところ、教えてくださーい。

**Comment by yotaca** [comment]
あっ、そちらのフォームではなくて、データベースの登録、編集フォームです。

具体的には『databases_edit_row_add.blade.php』に
&lt;input class="form-control" type="text" name="column_class" value="{{ old('column_class') }}"&gt;
こんなコードを追加しないといけないかと思ってます。

あと、width が styleで指定されているので、css のクラスを追加した方がいいかもしれません。
単位も px ではなく、rem の方が bootstrap っぽいと思います。

ところで、データベースが終わったあとで『フォーム』も見てみます。

**Comment by nagasheep** [comment]
永原です。

> 具体的には『databases_edit_row_add.blade.php』に
> <input class="form-control" type="text" name="column_class" value="{{ old('column_class') }}">
> こんなコードを追加しないといけないかと思ってます。

そうですね。
画面用のBlade テンプレートのファイルは上記のようなコードが必要ですね。
あと、Plugin のPHP コードでデータベースの追加・更新部分のコードの追加。

Plugin のPHP コードは以下です。
app/Plugins/User/Databases/DatabasesPlugin.php

以上

**Comment by yotaca** [comment]
了解です。
ボチボチはじめます。

**Comment by yotaca** [comment]
とりあえずプラグインの編集フォームが動作するファイルを作成しました。
かなり手探りですが、こんな感じで大丈夫でしょうか？

今からレイアウト作成を行います。

**Comment by nagasheep** [comment]
永原です。

> とりあえずプラグインの編集フォームが動作するファイルを作成しました。
> かなり手探りですが、こんな感じで大丈夫でしょうか？

ありがとうございます。
これ、作成していただいたファイルを見た方が良いのですよね？
どのファイル見れば良いか、教えてもらえれば見ますね。

以上、よろしくお願いいたします。

**Comment by nagasheep** [comment]
Pull Request を見れば良い感じですね。
ありがとうございます。
見ますね。

**Comment by yotaca** [comment]
デザインの方が残ってますので、このまま開けておきます。

**Comment by yotaca** [comment]
詳細画面にクラス名の入力フォームを移動させてPullRequest 送りました。
ご確認ください。

**Comment by yotaca** [comment]
データベースのレイアウトを整えている途中です。
デフォルトレイアウトの進捗です。ご確認ください。

１）md で 表形式とコラム形式を切り替えております。
２）抽出、ソート、検索を１〜２行で並べました。
３）[新規登録]のボタンの位置が少し違う気がしますが、とりあえず図の通りに配置しました。
４）ここに来て気がついたのですが、〝編集〟と〝新規〟が同じアイコンなので違和感ありますね。

詳細画面ができたら一覧画面のバリエーションをいくつか作成します。
特に、縦並びメニューに配置した時のバリエーションは欲しいですね。

![スクリーンショット 2020-05-12 11 17 32](https://user-images.githubusercontent.com/8961306/81631273-7337a380-9442-11ea-861f-f58898583f90.png)
![スクリーンショット 2020-05-12 11 17 13](https://user-images.githubusercontent.com/8961306/81631287-79c61b00-9442-11ea-9822-6aea9c6c0c09.png)
![スクリーンショット 2020-05-12 11 16 20](https://user-images.githubusercontent.com/8961306/81631315-86e30a00-9442-11ea-86bb-5628d6e93a94.png)
![スクリーンショット 2020-05-12 11 16 46](https://user-images.githubusercontent.com/8961306/81631324-89ddfa80-9442-11ea-9710-556120919ea7.png)

**Comment by Sasaki-EddyK** [comment]
カッコよいですね。
確認ですが、「md で 表形式とコラム形式を切り替え」ですが資料的なコンテンツの場合、mdに関係なく表形式で見たい場合があると思います。
ついては、mdに関係なくテンプレートで表示形式が切替できればいいなあと思いますがいかがでしょうか。
例えば「default」は表形式とし、「card」といったテンプレートを追加しコラム形式に表示するのはいかがでしょうか。
https://www.kk.shibaura-it.ac.jp/information
といったようなページもデザインはともかく「database」プラグインですぐにできると思うのですが・・・
すみません。ご検討のほどよろしくお願いします。

ところで、「設定」画面での「編集」ボタンは何のボタンでしょうか。わたしのCCMSでは「新規登録」ボタンしか現れないのですが・・・

**Comment by yotaca** [comment]
ご意見ありがとうございます。
laravel での開発に慣れてなく、かなり苦戦して時間が掛かっております。
まだテンプレートを調整している最中です。ご容赦ください。

見本画像は table タグ を div class=d-table に置き換えた程度なので、table の表示を踏襲しております。

私の感覚としてはこんなイメージでテンプレートを作成しております。
・デフォルトテンプレート：xs〜sm（カード）md〜xl（表）
・リストテンプレート：xs〜xl（リスト）
・tableテンプレート：xs〜xl（表）
・カードテンプレート：xs〜xl（カード）
・メニューリスト：xs〜xl（タイトルのみ）

このうち、リスト、table、カードについては同じソースで CSS の切り替えだけで表示を変えるように考えています。

別スレで上げてますが、まだデザインやアイコンなどが整理されていないために
見間違えてしまったんだと思いますが、ボタンは〝編集〟ではなく〝新規作成〟です。
＊PC のスクショでご確認ください。

ここで使用するアイコンは エディットではなく、プラスの方がいいと思いますが、
その件は別スレにてお話しできればと思います。

**Comment by Sasaki-EddyK** [comment]
「編集」ボタンの表示は上の固定記事のもので見間違えていました。スミマセンでした。
テンプレートですが、楽しみにしています。

**Comment by yotaca** [comment]
なんとかデータベースのレイアウトができました。
ベースのレイアウトなので、配色は無彩色です。

■メニュー用のレイアウトも作成しました。

■デフォルト
![デフォルト](https://user-images.githubusercontent.com/8961306/82224637-0e5adc80-995f-11ea-9d67-5ccf8bd3160a.png)

■テーブル
![テーブル](https://user-images.githubusercontent.com/8961306/82224653-13b82700-995f-11ea-98f8-8bc6071ebd5c.png)

■リスト写真あり。
![リスト写真付](https://user-images.githubusercontent.com/8961306/82224661-16b31780-995f-11ea-9050-61175f56f545.png)

■リスト（写真がない場合）
![リスト写真なし](https://user-images.githubusercontent.com/8961306/82224664-17e44480-995f-11ea-8290-09d63c8ed344.png)

■カード
![カード](https://user-images.githubusercontent.com/8961306/82224656-14e95400-995f-11ea-9a20-35eb5c955bc1.png)

ファイルを整理してプルリクエストいたします。
詳細はそのときまとめます。

スタイルの記載ですが、一応デフォルトCSSに追加してますけど、
今後はプラグイン用のスタイルシートの配置をちゃんと考えないといけませんね。
もしくは何かしら想定されて見えますでしょうか？

**Comment by nagasheep** [comment]
永原です。

すごーい！カッコ良いです。
一つ気になったのが、緑の「詳細＞」ボタンが枠からはみ出たり文字にかぶってそうです。

**Comment by yotaca** [comment]
@nagasheep 
ありがとうございます。

[詳細]ボタン悩ましいです。
データによって右置きか左置きか１行下に作った方がいいのか右にはみ出した方がいいのか迷ってます。
そのまま画像アップしたのも、その辺の意見が聞きたかったんです。

とりあえず、初期設定は下に１行作って右寄せにしておきますね。
午後からファイル揃えます。

**Comment by nagasheep** [comment]
> [詳細]ボタン悩ましいです。

なるほど。
機能面から考えるのもアリかも知れませんね。
・項目設定で、タイトル項目を決める。
・タイトル項目はリンクが付き、クリックすると詳細に行く。
とか。
別スレッドで書いた、勉強会（打合せ？）でも議題にしましょうよ。

**Comment by yotaca** [comment]
昼からプルリクしますけど、メニューボタンはかなりイレギュラーなことしてます。
表示させたいページとフレームを項目に追加して、classname に番号を追加して呼び出してます。
（めんどくさくなった原因です）

勉強会に間に合うようにプルリク準備しますね。

**Comment by nagasheep** [comment]
「メニューボタン」というのは、画像の一番左の、左エリアに入れている（？）、データベース・プラグインのことですね？
「メニュー用のレイアウト」って書いてるものと同じですよね。
ここもデータベース・プラグインなのですね。
気づかなかったです（^^）

**Comment by yotaca** [comment]
『メニュー用レイアウト』の使い方がわからなかったのと、画像入りが欲しかったので追加しました。
といいつつ、一番時間とりましたけど。

**Comment by yotaca** [comment]
#343
カスタマイズしやすいように、データベースプラグインのテンプレート書き換えました。
メニュー用テンプレートのリンク先ページIDとフレームIDを表示設定で編集できるようにしました。
ご確認ください。
