### ISSUE TITLE
【UI：アイコン、ボタン】一貫性について

### ISSUE THREAD

**Issue by yotaca** [opensource-workshop/connect-cms#314]
データベースのフォームを作成していて気になったのですが、

『DB選択』画面の『設定変更』ボタンのアイコンが〝fa-edit〟なのですが、
このアイコンは他の箇所の〝（コンテンツ）編集〟でも使用されているます。

一般的に〝設定〟を変更する場合には〝fa-cog〟や〝fa-wrench〟だと思います。
〝フレーム設定（？）〟では〝cog〟が使用されていますので一貫性にかけるかと思いました。

あとボタンのタイトルも考慮した方がいいかと思います。
データベースプラグインのデータを更新を終了するときに [キャンセル] を押すのはちょっと抵抗を感じます。
ここは [戻る] の方が自然かもしれません。

たまたまデータベースの作業をして気がついたのですけど、他にも似たような箇所があるかもしれません。
全体を見渡して使用されるアイコンなどの一貫性を考慮した方がいいかと思います。

**Comment by nagasheep** [comment]
永原です。

@yotaca さん、ありがとうございます。
そうなんですよ。
いろいろ、統一＆見直ししなきゃいけないんですよ。(笑)

アイコン、ボタンの文言、削除時の動き、画面POST時の動き、入力エラーの場合の動き、閉じるとキャンセルの区別など。
この１年、機能の実装を急ぐ必要があって、見直ししたいと思いつつ、機能が膨れてしまってます。わはははは。
今年は、整理したいなー。
どうすればうまく整理できるんだろう。
お知恵を拝借したいです。

ある程度はメモ程度に以下にまとめていたんですけどね。
https://github.com/opensource-workshop/connect-cms/wiki/Font-Icon
https://github.com/opensource-workshop/connect-cms/wiki/Button%EF%BC%88%E3%83%9C%E3%82%BF%E3%83%B3%EF%BC%89

**Comment by yotaca** [comment]
@nagasheep ソースとか眺めてるとそんな印象を受けます。

UI のデモ画面を作成しておいて、その都度ソースをコピペできるようにしておくと迷わなくてもいいかもしれません。
DB のテンプレ作ったあと、追加のテンプレを作成しながらでよければ〝たたき台〟作成します。

これからこのCMSをメインにしたいので、気になるところをできるだけ無くしたいですし。

個人的には、メインで開発される方が connect-market （コネケ？）作ってくれるとモチベもあがります。

**Comment by nagasheep** [comment]
> UI のデモ画面を作成しておいて、その都度ソースをコピペできるようにしておくと迷わなくてもいいかもしれません。
> DB のテンプレ作ったあと、追加のテンプレを作成しながらでよければ〝たたき台〟作成します。

ありがとうございます！感謝。待ちます。

> これからこのCMSをメインにしたいので気になるところをできるだけ無くしたいです。

責任重大だ。頑張ります！

> 個人的にメインで開発される方が connect-market （コネケ？）とか作ってくれるとモチベもあがります。

これ、急ぎましょう。
具体的にどうしましょうかね。
別スレッドで考えましょう。

**Comment by yotaca** [comment]
CMSのポイントの１つは〝電話で説明できる UI かどうか〟だと思ってます。
「その星のボタンを押せば投稿できます」
「鉛筆マークで編集できますよ」

わたしがクライアントに説明するときに気になってる部分なので
この段階から参加できるのは願ったりかなったりです。

コネケ期待してます。

**Comment by akagane99** [comment]
・アイコン、ボタンの文言を変更する時は、一気にやりたいなぁ。
・下記はボタンの参考メモ

#### ボタン参考

・新規登録（⇒ + アイコンに変更）
![image](https://user-images.githubusercontent.com/2756509/86121651-5863e000-bb11-11ea-9264-640325daf249.png)

・編集（いまのまま）
![image](https://user-images.githubusercontent.com/2756509/86121746-89441500-bb11-11ea-8c94-e2dad70a3dc0.png)

**Comment by yotaca** [comment]
app.css を読み込んだあ後、ほぼ同じ内容の css で上書きしてるので、そこから調整したいなぁ。
『指定フォントの見直し、スタイルシートの整理、アイコンフォントの位置変更』
https://github.com/opensource-workshop/connect-cms/pull/364#issue-440558925

**Comment by yotaca** [comment]
sass を使ってスタイルシートを作成すると、レイアウトに齟齬が生じる可能性が発生したので、一旦クローズいたします。
