### ISSUE TITLE
Connect Market について

### ISSUE THREAD

**Issue by nagasheep** [opensource-workshop/connect-cms#315]
2020-04-27 の勉強会でも話した内容ですが、もう少し具体的に書いてみました。
他にこんなことができるよ。などあれば、教えてください。

--- Connect-CMS ユーザ会の立ち上げ

・公式サイトでConnect-CMS ユーザ会のページ作成
・会員リストの掲載
・会員は書面で申し込んでいただく。
（反社会的勢力や怪しい会員登録への対処）
・いずれは法人化（NPO or 一般社団法人）を目指す。

--- Connect-CMS の勉強会

随時だと、どうしても予定が途切れがちになるので、定例化しても良いかも。
月一くらいを想定。平日の昼？平日の夜？土曜日？
Connect-Night として、平日の夜にオンラインでもアリかも。
（夜なら永原は飲みながらの参加かな（^-^））

--- テーマ販売

テーマの販売をするのに、良い方法って、何かあります？（誰か知ってます？）
このEC サービス使えばよいよ。とか。

ユーザー会として、テーマの動作確認をすることと、販売サイトの運営で手数料を取れれば良い感じなのですが。
その費用などでイベントをするとかにつなげたいです。

--- プラグイン販売

テーマ販売と同じですね。

以上

**Comment by yotaca** [comment]
■ユーザー会　→法人化
この辺は、NC で運営の経験のある方にお任せしたいかな。

■勉強会
平日の夜、月１ペースがちょうど良さそうなきがします。
個人的には月、水、木 ８〜９時が理想です。まぁコロナ次第ですけど。

■テーマ、プラグイン販売
無理を承知で書きます。
Chrome などのブラウザの〝機能拡張〟みたいにクリックするとそのままインストールするようなシステムだとかっこいいですよね。
ですがテーマはともかく、プラグインの動作チェックとか大変そうですよね。

■マイルストン
なかなか決められないかもしれませんが、月ごとのマイルストンがあると勉強会などのネタになると思います。
また自分ではソースが書けなくても、マニュアル作成や、動作チェックはできるとか、操作レビューなどができるとか、各自できる事が見えてくるのではないでしょうか。

**Comment by nagasheep** [comment]
> ■マイルストン

Github にマイルストン機能がありますね。
ちょっとやってみました。
https://github.com/opensource-workshop/connect-cms/milestones
一回やってみましょう。

**Comment by yotaca** [comment]
issues をそのままマイルストンに反映されるんですね。
わかりやすくていいですね。
今度から意識してタイトルをつけた方がよさげですね。

**Comment by akagane99** [comment]
Themes online shopping（テーマ販売） 
https://github.com/opensource-workshop/connect-cms/issues/77
