### ISSUE TITLE
【要望】iframeプラグインの追加

### ISSUE THREAD

**Issue by dreamer9999** [opensource-workshop/connect-cms#317]
NetCommnsのプラグインで、iframeプラグインがありますが、同様なプラグインをconnect-cmsにも追加していただきたいです。
iframeプラグインは、何かと使い勝手はあると思うのですが、いかがなものでしょうか、、、

**Comment by nagasheep** [comment]
いまのところ、iFrame プラグインの予定はありません。
以下にやり取りの記録があります。
https://connect-cms.jp/plugin/bbses/show/106/233/9#frame-233
