### ISSUE TITLE
コアにmiddleware機能の導入

### ISSUE THREAD

**Issue by nagasheep** [opensource-workshop/connect-cms#318]
コントローラで実施している各種チェックなどをmiddlewareに移すことで処理を分かりやすくする。

**Comment by akagane99** [comment]
## 調査

・app/Http/Middleware/ConnectInit.php で middleware 導入済み
https://github.com/opensource-workshop/connect-cms/blob/master/app/Http/Middleware/ConnectInit.php

・app/Http/Kernel.php で ConnectInit を全体に適用
https://github.com/opensource-workshop/connect-cms/blob/be8566cf81152e026e9a7e8ae2a5f1f56bda411a/app/Http/Kernel.php#L41

## 今後案

・共通でもつ値にも、一般プラグインと管理プラグインで要不要があるため、
　一般プラグインと管理プラグインでmiddlewareを分けた方がいいかも。
・middlewareの適用は、app/Http/Kernel.php　以外にもコントローラーで挿入可能らしい。

とりあえずここまで

**Comment by akagane99** [comment]
* https://github.com/opensource-workshop/connect-cms/issues/908

上記で対応済みのため、クローズします。
