### ISSUE TITLE
【共通】フレーム設定を編集中、何のプラグインを設定しているかわからない

### ISSUE THREAD

**Issue by masaton0216** [opensource-workshop/connect-cms#327]
クライアントから意見があったのですが、すぐに取り掛かれず対応イメージ未定ですが、とりあえず備忘として。
>(ご提案)
Connect-CMSの操作に不慣れな人の場合、どのプラグインを編集しているのか判断が難しいかと思います。
フレームの設定画面などを開いた時に、使用プラグインがわかるような画面？(プロパティタブ？)アイコン？などがあると、より便利かと思います。
(例えば他のページを真似てページを作る場合も、元のページに配置されているプラグインがわからないと、ページ作成のハードルが一段上がるかと思います。いろいろ触って覚えようタイプの人には不要な機能ですが、いじって壊したらどうしよう・・・タイプの人はちょっとした親切かと思います。)

**Comment by akagane99** [comment]
## 案 - 固定記事の例
// ＰＣ
![image](https://user-images.githubusercontent.com/2756509/81769608-ff1bff00-9518-11ea-88ba-4562a6e9ed26.png)

// スマートフォン
![image](https://user-images.githubusercontent.com/2756509/81769651-1a870a00-9519-11ea-9927-85168c7cabad.png)

こことかに`label`でプラグイン名を灰色表示、とかかなぁ。

**Comment by Sasaki-EddyK** [comment]
勝手なイメージで記載しますがお許しください。
フレームとコンテンツとの関係を考えれば、フレーム設定の画面で中におくプラグインを変更できてもよいのではと思うのですがいかがでしょうか。
（初めからコンテンツを決めて配置するのであれば必要性もないかも知れませんが）
もちろん、フレームにプラグイン名を表示するのはよい案だと思います。

**Comment by masaton0216** [comment]
- フレーム枠にプラグイン名を表示するよう対応
https://github.com/opensource-workshop/connect-cms/commit/052c2b3badc0c645f1341f09dbed9c2266fe3208

- イメージ
![image](https://user-images.githubusercontent.com/13323806/87912636-b2b8e680-caa8-11ea-9eb3-9f6023e01042.png)

- フレームとコンテンツを切り離す対応は別途Issueを起票してもらえますでしょうか？@Sasaki-EddyK
