### ISSUE TITLE
ページ登録の「権限設定画面へ」がtarget「新規ウィンドウ」となっている

### ISSUE THREAD

**Issue by Sasaki-EddyK** [opensource-workshop/connect-cms#330]
ページ登録の「権限設定画面へ」がtarget「新規ウィンドウ」となっているせいで、ブラウザのタブが増えていきます。「権限設定」をいろいろと試していたら知らない間にブラウザのタブがconnect-cmsでいっぱいになっていました。
これは誤り、それとも意図的なものでしょうか。

**Comment by nagasheep** [comment]
永原です。
最初、その方が良いかなと思ったんですが、良くないですよね。
昨日か一昨日の修正で、新規ウインドウを止める修正が入っていると思います。

**Comment by Sasaki-EddyK** [comment]
そうだったんですね。すみません。
ポップアップ画面ではと思ったのですが、未だポップアップ画面の制御がないような・・・
クローズさせていただきます。
