### ISSUE TITLE
フレームに対するテンプレート名のクラス追加を検討願えないでしょうか

### ISSUE THREAD

**Issue by Sasaki-EddyK** [opensource-workshop/connect-cms#336]
現在テンプレートを作成していて同じページで同じプラグインを複数配置しテンプレートによる見え方の差異を確認しています。
その中で、特定のテンプレートのみ一般的な要素に対して様式を追加・変更しようとした場合、表示ブレードのソースにテンプレート独自のセレクタ名を付けなければなりません。
フレームのタグにクラスとしてテンプレート名があれば「子孫セレクタ」として指定ができるのでいいのかなあと考えます。いかがでしょうか。
独自のテンプレートを作成しているので、独自のセレクタ名で作ればといわれれば、そうなのですが・・・
ご検討のほど、よろしくお願いします。

また、同じような話になるのですが、データベースを複数配置し、同じデータを選択している場合、ページング機能は複数のフレームで同じページ切り替えになるのですね。
同じページ内で同じデータを選択することもないと思うので問題でもないと思いますが、フレームで独立していると思っていたので、気にすることはないと思いますがわたし的にちょっと気になったので、ご報告まで・・・

**Comment by nagasheep** [comment]
永原です。

> フレームのタグにクラスとしてテンプレート名があれば「子孫セレクタ」として指定ができるのでいいのかなあと考えます。いかがでしょうか。

もうちょっと具体的に、ココにこう出力されたら良いのに。って教えていただいても良いです？
フレームの話は別スレッドで返答していましたよね。
まだ開発できていないのです<m(__)m>
もしよかったら、ソースコード作成の参加もお待ちしていまーす（^^）

**Comment by Sasaki-EddyK** [comment]
resources\views\core\cms_frame.blade.phpの36・38行目に「{{$plugin_name}}」と同じように「{{$template_name}}」といったものがあれば、CSSに
.template-card .card {
	margin-bottom: 0.75rem;
}
.template-card .d-table {
	width: 100%;
	margin-bottom: 0.75rem;
}
といった、「.template-card」を親として「.card」に対してmargin-bottomを追加できます。
テンプレート独自でセレクタ名（例えば「.card_tmp_card」）を付ければできないことはないのですが、frameにテンプレート名のクラスがあれば、テンプレート名の修飾子として記述できるのでいいのではと考えました。

以前言っていたベースのカスタマイズとは、ちょっと違う話です。

はい、ソースコードの開発にもお手伝いできる部分はさせてもらいたいのですが、何分gitの使用方法が未だ勉強できていないもので・・・
また、Laravelについて表示系はおおよそ理解できたのではと思っているのですが、更新系ロジックはまだどのようにして更新しているかは理解できていません。

また、勉強会があれば参加させてもらいます。

**Comment by masaton0216** [comment]
@Sasaki-EddyK ご提案頂いているところを長らく放置してしまってすいません。
フレームのクラスに「プラグイン名＋半角ハイフン＋テンプレート名」クラスを追加しました。
例）下記はデータベースプラグインでテンプレート「table」を指定している状態で「databases-table」というクラス名になっています。
![image](https://user-images.githubusercontent.com/13323806/86355892-4ff0de00-bca6-11ea-90dd-c65e6991f798.png)

**Comment by akagane99** [comment]
https://github.com/opensource-workshop/connect-cms/issues/336#issuecomment-652963287
上記で対応済みのため、クローズします。
