### ISSUE TITLE
ひとつのページで複数のdatabaseを配置した時の挙動がおかしい

### ISSUE THREAD

**Issue by Sasaki-EddyK** [opensource-workshop/connect-cms#338]
既知の問題であればcloseしてください。
databaseプラグインでひとつのページで複数のdatabaseを設置した場合、各操作が異なるフレームのdatabaseに対しても反映してしまうことが判明しました。
同じデータを選択している場合でページングだけであればよいかなあと思っていましたが、異なるデータでも発生しています。
もし、どうのような単位で更新するか、どのようなphpで更新しているかなど教えてもらえるのであれば、時間はかかると思いますが修正させてもらうのですが・・・

**Comment by masaton0216** [comment]
@Sasaki-EddyK ご連絡ありがとうございます。単一ページに複数のページャー設置するところは、おそらくどのプラグインも考慮は出来てないと思います。
現象としてはコレになると思うので、
https://qiita.com/sano1202/items/371a59ea46cb66993b8b
ペジネートにパラメータで固有名を渡してあげれば直るかと思います。ページャー表示されるのはパッと思いつくのはブログとデータベースですが、他にもあるかもしれません。少しお時間頂ければこちらで調査、修正させて頂きます。

**Comment by Sasaki-EddyK** [comment]
ご連絡ありがとうございます。
それでは、よろしくお願いします。

**Comment by masaton0216** [comment]
# 対応予定箇所 ※チェックありは対応済み
- [x] ブログ コンテンツ（記事）一覧
- [x] ブログ 設定一覧
- [x] 固定記事 設定一覧
- [x] データベース コンテンツ一覧
- [x] データベース 設定一覧
- [ ] データベース検索 コンテンツ一覧
- [ ] FAQ コンテンツ一覧
- [ ] FAQ 設定一覧
- [ ] フォーム 設定一覧
- [ ] ナレッジ 設定一覧

**Comment by masaton0216** [comment]
@Sasaki-EddyK クライアントからもこの件についてツッコミがあったので、ひとまずページャーのみ対応しました。同一ページ同一プラグイン配置はあまりテストできてないところもあり、他操作でも不具合は出るかもしれません。他におかしな挙動をするような操作があれば別途ご教示ください。

**Comment by akagane99** [comment]
対応済みのようなので、一旦クローズします。
