### ISSUE TITLE
【Laravel】変数や配列の挙動が分かりにくい

### ISSUE THREAD

**Issue by yotaca** [opensource-workshop/connect-cms#341]
ほぼ愚痴かもしれませんが、detabaseプラグインをさわっていて一番困ったのは、変数がグローバルなのか、ローカルなのかがつかみにくかった。
@php 〜 @endphp で囲った中で宣言したの変数が他で使えたり使えなかったり。
一度エラーが出てデバッグ画面が表示されても、修正していないファイルだったりでどうしようもなかった。
結局、かなり広い範囲で@php～@endphp で囲むことになったりしたので、laraver の良さがいかされていない気がします。
あと、functionの宣言が面倒そうで、ソースの再利用がしにくいのも辛かった。

正直慣れるにはまだまだ時間がかかりそうです。

**Comment by nagasheep** [comment]
永原です。

> ほぼ愚痴かもしれませんが、detabaseプラグインをさわっていて一番困ったのは、変数がグローバルののか、ローカルなのかなつかみにくかった。
> @phpで囲った中で宣言したの変数が他のかしょで使えたり使えなかったり。
> 一度エラーが出てデバッグ画面が表示されても修正していないファイルが表示されていてどうしようもなかった。

この辺、勉強会のネタにしましょうか。
永原の作りが悪い部分もあるかと思うので、そこは申し訳ない！<m(__)m>

**Comment by yotaca** [comment]
よたかです。
おはようございます。
Laravel 5 のネタは結構出てきますが、７ はまだまだ情報が少ないみたいですよね。
感覚的にblade ファイルは拡張子こそphp だけど、phpコマンドも使える別のファイルだと思いました。

作りの良し悪しというか、基本的な考え方が違うんだなぁ〜って感じました。

私が書く時は、必要なパラメータをローカル配列に保存しておいて、あとから一気に書き出す感じです。

永原さんのファイルは、組み立て終わった部分はすぐに書き出して、続きを組み立ててる感じ。
そちらの方がメモリ食わずに速い気がしますし、グローバルも汚しそうにないですよね。
この辺は今まで作って来たものの差なんだろうななんて感じてました。

今回の プラグイン の組み立ては各項目の入れ替えが必要だったので、そこで一番苦戦しまいた。
１番最初に出てきた〝image〟をサムネ扱い
１番最初に出てきた〝テキスト〟を項目のタイトル扱い

そして１番のストレスは、エラーが出てきたときにデバグ画面が表示されるのですけど、完全にエラーを修正しないとプラグインの設定が触れない。
画像を指定した時はちゃんと表示されるのに画像がないとエラーになるので、画像のあるなしを判定をどこに配置すればいいのか判断したいけど、エラーは他のファイルなのでファイルをもう一度見直さないといけない。
他にはPHPとしては完結してるのに、他のファイルがエラーが起きているみたいだし、何を求められているのかわからない。

勉強会はもちろんですけど、全体的な組み立てのすり合わせをお願いしたいです。

**Comment by nagasheep** [comment]
永原です。

> 勉強会はもちろんですけど、全体的な組み立てのすり合わせをお願いしたいです。

「全体的な組み立てのすり合わせ」良いですよ。
具体的にどういう内容をすり合わせすればよいかも含めて、時間決めましょう。
今週なら、水・木・金・土がOK。（木の12:00-13:00 はNG）
いつにします？
決めたら、また公開して、参加したい人はどうぞ。ってしましょう。

内容的には、以下のようなものが必要かなと想定します。
・Connect-CMS の動き方（index.php から画面出力までのファイルの実行の順番）
・各プラグインの画面の呼び出し方
・各プラグインから画面への変数の渡し方

以上、よろしくお願いいたします。

**Comment by yotaca** [comment]
@nagasheep 
さっそくありがとうございます。
できたら17:00 〜 21:00 の間がありがたいです。

**Comment by nagasheep** [comment]
夜でもOK。（永原はビール飲みながらかもしれませんが(笑)）
日はいつが良いです？
以下のスレッドでお願いします。
https://github.com/opensource-workshop/connect-cms/issues/342
