### ISSUE TITLE
Connect-CMSオンライン勉強会【 2020-05-22（金）22:00～】

### ISSUE THREAD

**Issue by nagasheep** [opensource-workshop/connect-cms#342]
・Connect-CMS の動き方（index.php から画面出力までのファイルの実行の順番）
・各プラグインの画面の呼び出し方
・各プラグインから画面への変数の渡し方（スーパークラス部分も説明）
・データベースプラグインの詳細ボタン（リンク）の位置

@yotaca 他にもあれば、追記してもらえれば助かります。

**Comment by masaton0216** [comment]
開催時間によりますが参加したいです。
夕方以降であれば、子供の絡みがあるので遅ければ遅いほどありがたいです。

**Comment by yotaca** [comment]
内容的にかぶっているかもしれませんが、
object がうまく設定できなかったし、既存の object がうまく扱えなかった。
class や function を新規で作成する方法もちゃんと知りたい。

PHP とは離れますが、css の読み込む順 の 明示
scss での作成について

この辺で引っかかっております。

参考になるかわかりませんが、私が作るテーマの場合下記の順番で読み込んでおります。
yotaca.com/bootstrap/431/dist/css/bootstrap.min.css 生のbootstrap css
yotaca.com/skins/hnmboot4/css/hnmboot4.css テーマ用のCSS （デフォルトカラー含む）
yotaca.com/skins/hnmboot4/css/colors/grn.css 色変更のCSS （レイアウトは変更しておりません）
場合によっては、クライアント別カスタムCSS

今回の作ってみて感じたのはこの下に読み込むのがよいかと思います。
プラグイン専用の CSS
プラグインの色変更のCSS

いかがでしょうか？

**Comment by yotaca** [comment]
告知できるように木曜日か金曜日がいいと思います。

名古屋は金曜日の夜、外出する人が結構いるみたいですけど、
東京、大阪はまだ巣ごもりですよね。

**Comment by nagasheep** [comment]
@masaton0216 @yotaca 
具体的に何時が良いです？
永原は22:00 ～とかでもOKよ。

選択肢
・16:00～
・17:00～
・18:00～
・19:00～
・20:00～
・21:00～
・22:00～

**Comment by masaton0216** [comment]
今回、私はプラグインのところは復習的なところなので、時間はよたかさんの要望を第一にしてもらってよいです。22時～も平気ですｗ

**Comment by nagasheep** [comment]
@yotaca 時間、確定してくださーい。お任せします。

**Comment by akagane99** [comment]
(金)は子守してるので、時間あったら参加しますー。（時間お任せします）

**Comment by yotaca** [comment]
じゃ、22日（金）22:00〜 でもよろしいですか？
オンライン飲み会的な時間ですが、気軽に意見を言い合える雰囲気が欲しいのでむしろいいかも。

みなさまよろしくお願いします。

**Comment by Sasaki-EddyK** [comment]
参加させていただきます。自由人なので日時はいつでも結構です。

**Comment by akagane99** [comment]
> じゃ、22日（金）22:00〜 でもよろしいですか？

了解です。お酒用意しとこうっと。

**Comment by nagasheep** [comment]
はーい。
22日（金）22:00〜 でお願いします。
飲み物とつまみを用意しておきます（^^）

**Comment by yotaca** [comment]
お疲れ様でした〜！

プラグインの作成について大変勉強になりました。
database プラグイン menu テンプレート 楽しみにしております。
フレームを越えてリンクを設定する場合にframeidをどこで設定するべきか？

■長澤のスケジュール
css の構成を考慮してheaderの中を触ります。
　プラグインのcssの配置場所。
　プラグインごとのクラス命名について。
scss でカラー変更ができるようにしたい。
　laravel ライブラリーがあれば使えるかも。
管理系のメニュー、アイコンなどの提案
全体のテンプレートを新たに作成

とりあえずこのくらいでしょうか。

追伸： http://yotaca.com/ 無事に復旧しました。
