### ISSUE TITLE
【レンサバで動作】CPI ACE01 と coreserver 

### ISSUE THREAD

**Issue by yotaca** [opensource-workshop/connect-cms#348]
レンタルサーバーでの公開を見据えて設置テストをしました。

１）マニュアル通りでのインストールはできませんでした。
■CPI ACE01
　SSH で php コマンドが使えません。
■coreserver 
　SSH で php -v で確認すると、7.1 でした。

　結果、ローカルで動作しているサイトのコピーをそのままコピーして動作確認。

２） CPI ACE01 での設置
・connect-cmsフォルダ を全て非公開部分に配置
・public 以下のファイルを全て html ディリクトリ（公開ディリクトリ）に〝コピー〟
・.env を編集
　　DB_HOST=127.0.0.1 （CPI サーバーは localhost では接続できない）
　　DB_DATABASE= DB名
　　DB_USERNAME= ユーザー名

注意）非公開エリアの〝connect-cms〟に 〝public〟ディリクトリ を設置しないと、画像とスタイルシートが読み込まれず、〝管理メニュー〟〝サイト管理〟でエラーが出ます。

３）coreserver での設置
・connect-cms を全て非公開部分に配置
・.env を編集しておく
・サーバーの〝コントロールパネル〟〝設定するドメイン〟〝サイト設定〟 でドキュメントルートを
　/public_html/connectcms/public へ変更しておく。

・直接アクセスを防ぐため、/public_html/connectcms/.htaccess に deny from all と記載して配置する。

４）要望
・PHP コマンドを使わずにインストールできるようにならないか？
・公開ディリクトリの名称はサーバーによってバラツキ（public_html、html、public など）があるので、変わっても対応できるようにして欲しい。

**Comment by akagane99** [comment]
レンサバの動作確認ありがとうございます。

Connect-CMSはlaraveフレームワーク5.5系を使っていて、php7.2以上からなんです。
https://github.com/opensource-workshop/connect-cms/wiki/Install-%28%E3%82%A4%E3%83%B3%E3%82%B9%E3%83%88%E3%83%BC%E3%83%AB%29

なのでphp7.2以上が入ってないレンサバは動かないと思います。

> ・PHP コマンドを使わずにインストールできるようにならないか？
> ・公開ディリクトリの名称はサーバーによってバラツキ（public_html、html、public など）があるので、変わっても対応できるようにして欲しい。

ここらへんはlaravel依存ですね。
レンサバでlaravel動かす方法があれば、できるかと。
私も知らないので、上記で何か情報あったら教えてください。

**Comment by yotaca** [comment]
■PHP について
apache で使えるのは php7.4 まで使えますし、わたしも php7.3 で使えるように指定しています。
ところが、ssh で接続して確認すると、version が 7.1 なんです。

[hnm@000 ~]$ php -v
PHP 7.1.33 (cgi-fcgi) (built: Feb 18 2020 07:16:02)
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.33, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans

つまりレンサバのスペックに書かれているバージョンとコマンドで動作するバージョンは必ずしも一致しないようなんです。

■ドキュメントルートについて
もう少しまとめて書こうと思ってますけど〝公開ディリクトリの名称〟が違っても動作はするようなんです。
ただcss が読み込めなかったり管理画面でエラーになるんです。
なんとなく感じるんですけど、

public から〝外のファイル〟を呼び出して、戻ってくるのは大丈夫みたいですけど、
public 以外のディリクトリにあるファイルから public 内のファイルを 呼び出す時にエラーになっているようなんです。
それで、公開ディリクトリ 以外に public を配置したところエラーがなくなりました。

わかりにくいと思いますので、後から綺麗にまとめてアップします。

**Comment by akagane99** [comment]
> ■PHP について

これphpの標準の動きなんです。
cli と apacheとでは設定によって、別々のphpバージョン動かせるんです。

phpのエイリアスを張っておくと、cliでphpバージョン変えられる？
ここらへん疎くて💦

ネット記事でバリューサーバーのざっくり手順メモがありましたので、貼っておきます。
https://qiita.com/sola-msr/items/b64b31bcb0dfc1fce377#バリューサーバーで動かすおまけ

> ■ドキュメントルートについて

違うディレクトリでやりたい場合は、cliあればシンボリックリンクで対応できるみたいです。（やった事ないっす。）
https://qiita.com/sola-msr/items/b64b31bcb0dfc1fce377#１２リポジトリとpublicとでシンボリックリンクを張る

> わかりにくいと思いますので、後から綺麗にまとめてアップします。

ありがとうです。

## 他のレンサバ

https://nori-life.com/rental-server-to-use-laravel/

上記ネット記事によると、`さくらのレンタルサーバー`、`XSERVER`でlaravel配置できるようです。
参考程度で。

**Comment by yotaca** [comment]
現在のディリクトリをまとめました。

.env
┬html （cpi の公開ディリクトリ）
│   ├index.php
│   │
│   ├bootstrap4
│   ├fontawesome
│   ├fonts（もういらない？）
│   │
│   ├images
│   ├css このディリクトリを積極的に使ってもいいのでは？
│   ├js このディリクトリを積極的に使ってもいいのでは？
│   │
│   ├tempusdominus-bootstrap-4
│   ├themes
│   ├uploads
│   │
│   ├mix-manifest.json（ここの設定をいじればsass が使えそう）
│   ├robots.txt
│   ├web.config
│   │
│   └favicon.ico
│ 
├public（laravel の公開ディリクトリ）
│  ＊無駄だと思いますが、ここに配置しないとエラーが出ます。
│   シンボルリンクでもいいのかもしれませんが、一般的な対処方法ではないかと
│
│＊これ以下のファイルが public/* のファイルを参照させなければ、
│ public は必要ないかと思います。
├app
├bootstrap
├config
├connectcms
├database
├resources
├routes
├storage
├vendor
│
├artisan
├composer.json
├composer.lock
├package-lock.json
├package.json
├phpcs.xml
├phpunit.xml
├route.txt
├server.php
└webpack.mix.js

**Comment by akagane99** [comment]
投稿被りました💦
https://github.com/opensource-workshop/connect-cms/issues/348#issuecomment-633786101

上記って、ドキュメントルート配下のディレクトリ構成だったりします？
.envは見れなかったので大丈夫だと思いますが、ちょっと怖いかな。

世の中、公開しちゃってるサイトもあるようです。
https://qiita.com/sola-msr/items/b64b31bcb0dfc1fce377#１０環境ごとの設定をenvに書き込む

**Comment by yotaca** [comment]
KDDI CPI ACE01 は html と同じ階層に配置しても動作しますが、
coreserver はユーザーが変わるのでドキュメントルート配下でないと動作しません。
＊サーバー設定画面にユーザーとグループを変更するボタンがあります。

とりあえずコピペして動くみたいなので、
composer のインストーラーでなくてもいいような気がしてます。

ただ migrations はどうにも動作しないとは思いますけど。

**Comment by akagane99** [comment]
migrations できないのって、KDDI CPI ACE01の話ですよね。

CPIのスタッフブログによると、laravelのmigrations、コマンドから実行できるみたい。（ブログではphp7.1でしたが）
Laravel入門シリーズでブログ書いてあるので、参考になるかと。
https://knowledge.cpi.ad.jp/howto-cpi/laravel-migration/

**Comment by yotaca** [comment]
確認しました。ありがとうございます。

紹介していただいた記事に沿ってインストールしてみました。
https://knowledge.cpi.ad.jp/howto-cpi/laravelInstall/

見事に〝.env〟が見えてました……orz

素の Larval を見た感じ、ファイルの構成はどうしようもない感じですね。
現状ではこんな感じでシンボルリンクを配置するのが現実的みたいです。
public -> html

もう少し検証してみます。

追伸：php-7.3 でphp コマンドが使えるのがわかって助かりました。

**Comment by yotaca** [comment]
本来の配置とは違いますが、下記の通り配置してみました。
少し入れギュラーかもしれませんが、とりあえず意図通り動いているのでこのまま様子をみます。


┬  html （cpi の公開ディリクトリ）
│   ├ index.php
│   ├ bootstrap4
│   ├ fontawesome
│   ├ fonts（もういらない？）
│   ├ images
│   ├ css このディリクトリを積極的に使ってもいいのでは？
│   ├ js このディリクトリを積極的に使ってもいいのでは？
│   ├ tempusdominus-bootstrap-4
│   ├ themes
│   ├ uploads
│   ├ mix-manifest.json（ここの設定をいじればsass が使えそう）
│   ├ robots.txt
│   ├ web.config
│   └ favicon.ico
│ 
└ connnect-cms 非公開のエリアに コア（？）をディリクトリごとまとめておく
　　├ .env
　　├ public -> ../html シンボルリンク
　　├ app
　　├ bootstrap
　　├ config
　　├ connectcms
　　├ database
　　├ resources
　　├ routes
　　├ storage
　　├ vendor
　　├ artisan
　　├ composer.json
　　├ composer.lock
　　├ package-lock.json
　　├ package.json
　　├ phpcs.xml
　　├ phpunit.xml
　　├ route.txt
　　├ server.php
　　└ webpack.mix.js

**Comment by masaton0216** [comment]
@yotaca ご調査を頂きありがとうございます。別でLaravel開発をしているのですが、それらで得られた知見を共有します。レンサバで動かす、という本Issuesの趣旨からは少し外れてしまいますので、そこはすいません。

- Laravel標準のディレクトリ構成を変えると、viewファイル（*.blade.php）等で使えるLaravelのヘルパー関数（mix()やasset()等）が使えなくなってしまうのでは？と懸念しております。ディレクトリを変える場合はこの辺りも検証する必要があるのかなと考えてます。asset()を使ってる箇所は例えば下記があります。すべてのviewファイルで共通に参照しているファイルです。

https://github.com/opensource-workshop/connect-cms/blob/master/resources/views/layouts/app.blade.php#L66

- mix-manifest.jsonはjsとcssファイルをバージョニング参照する際のハッシュの定義ファイルです。後述のコンパイルコマンド叩くと自動で生成されるファイルなので、これを直接編集する必要はないものかと思います。一昔前のフロント開発だとjsやcss改修後にview系のファイルからの参照箇所に`funcsion.js?20150425`みたいにリリース日付等をクエリストリング付でリリースすることでブラウザキャッシュによる旧jsファイル参照によるユーザ側からの「動かねーよ、リリースされてねーよ」問題を解決していたのですが、原理的にはこれと同じことをやってます。

- jsとcssのフロント開発はコンパイルやminify化も含めて色々なソフトがありますが、LaravelではLaravel-mixという何かのラッパーライブラリが存在しています。この何かが実はwebpackなのですが、これとLaravelの橋渡しをしているのがLaravel-mixです。そしてコンパイルコマンド叩いた時のコンパイル元ファイル（左）と吐き出し先（右）を定義したものが下記です。
https://github.com/opensource-workshop/connect-cms/blob/master/webpack.mix.js

- コンパイル系のコマンドはなんだ？というところが下記になります。これらを実行するにはランタイム環境としてnpm(node.js)をインストールする必要があります。
`npm run hot ※ローカル用。コーディング時用。ローカルで叩いておくとプロセスが常駐してくれてjsやcssファイル等の編集＆保存時、自動でコンパイルしてpublic配下にデプロイ（ホットリロード）までしてくれます`
`npm run dev ※ある程度、開発が進んだ用。debugモードで動かしたい時とか用`
`npm run prod ※プロダクション（本番）環境用。minify化圧縮されます。テストが終わったらこのコマンド叩いた版のpublicディレクトリ配下をmasterリポジトリにコミットします。`

**Comment by masaton0216** [comment]
@yotaca 追伸ですが、sassは多分、下記ファイルに記述してコンパイルすればいけるのかなーと睨んでます。sassの知見が全然ないので推測レベルです。どっちがどういう役割のファイルなのか等も調べる必要がありますね。
https://github.com/opensource-workshop/connect-cms/tree/master/resources/assets/sass

**Comment by yotaca** [comment]
ありがとうございます。
わからない部分も多々ありますが、もっとしっかり読み直して反映させていただきます。
今やっているのが終わったら、scss 触りますので参考にさせていただきます。

ところで、ディリクトリをいじってみて最初は読みこめなかったcssがあったみたいなんですけど、pubiic （シンボルリンク）を配置したらとりあえず読みこめたみたいなので、このまま動作を確認していこうと思います。

**Comment by yotaca** [comment]
これですね。
https://qiita.com/mk185/items/1508ac6172c73db7808b
app.css を書き換えたら見事に書き換えてくれました。
使えそうなので、もう少しつめます。

**Comment by wai8605** [comment]
レンタルサーバーのcolorfulboxに、connect-cmsをマニュアル通りでインストールできました。
（レンタルサーバーのcolorfulboxにはlaravelのクイックインストール機能があります、レンタルサーバーのmixhostにもlaravelのクイックインストール機能があるので、おそらくmixhostでもconnect-cmsをインストールできるのではないかと思います）
