### ISSUE TITLE
【バグ？】フォームを表示しようとするとエラーになる

### ISSUE THREAD

**Issue by yotaca** [opensource-workshop/connect-cms#354]
プルリクエストをする前に、ローカルにmasterをマージしたのですが、結果フォーム画面を表示させるとエラーが出るようになりました。
他の方も同様のエラーがでてませんでしょうか？

![スクリーンショット 2020-05-31 6 44 17](https://user-images.githubusercontent.com/8961306/83339561-2e4cb180-a30a-11ea-8d64-130482fef1ea.png)

/resources/views/plugins/user/forms/default/forms_input_textarea.blade.php
&lt;textarea&gt; 〜 &lt;/textarea&gt; の中を空にすると表示はされます。
どうやら $request が存在しないようです。

&lt;textarea&gt; 〜 &lt;/textarea&gt; の中を空にして表示させ入力するとエラーで登録できません。

![スクリーンショット 2020-05-31 6 53 42](https://user-images.githubusercontent.com/8961306/83339719-889a4200-a30b-11ea-92f8-91a7aa095463.png)

以上、原因などを教えていただけると助かります。

**Comment by masaton0216** [comment]
@yotaca ご連絡ありがとうございます。こちらで最新化した状態で少しあれこれ触ってみましたが再現しませんでした。バグかどうかはまだ判定できませんが、最新化が原因ではなく既存で発生するものなのかもしれません。DBのダンプ頂くこと可能でしょうか？

**Comment by yotaca** [comment]
@masaton0216 
レスありがとうございます。下記リンクからダウンロードできるようにしておきました。
http://nagasawa.red/hanare/index.php/s/B7CAf7LmNpyBs7F
ご確認ください。

**Comment by masaton0216** [comment]
@yotaca 該当エラーが出るフォームはどのページにありますか？
お問い合わせフォームに遷移しようとすると「ページがありません」と出ました。

**Comment by yotaca** [comment]
@masaton0216 
ありがとうございます。
[はなまちについて] > [お問い合わせ]

固定リンクは下記の通りです。
/corporate/contact

**Comment by masaton0216** [comment]
![image](https://user-images.githubusercontent.com/13323806/83483387-8091fc00-a4dd-11ea-8692-b5f935863296.png)
@yotaca 頂いたDBダンプ＋master最新版で確認画面まで遷移可能でした。この後、送信ボタンを押して問題なくメールまで送信できました。再現手順等ございますか？

**Comment by yotaca** [comment]
@masaton0216 
確認ありがとうございます。

いつもは PHP 7.4.2 で動作させていました。
先のエラー画面はその時のものです。

試しに、PHP 7.2.22 にしたら確認画面まで進めました。
送信時にはエラーになりましたが、メール送信の設定をやってないからかもしれません。
エラー画面添付しておきます。

PHP 7.3.9 でも PHP 7.2.22 と同じ結果でしたので、
とりあえず PHP 7.3 で作業を続けます。

![スクリーンショット 2020-06-02 18 55 15](https://user-images.githubusercontent.com/8961306/83507316-5e12d980-a503-11ea-8536-79e24fa2b5e2.png)
