### ISSUE TITLE
スマートフォンでwygiwygの画像をアップロードさせるボタンが反応しない事がある

### ISSUE THREAD

**Issue by akagane99** [opensource-workshop/connect-cms#359]
iphone＋Safariだと「画像を参照」ボタンを押しても反応が悪く、たまに反応してくれる位。
android＋Chromeだと、反応しませんでした。
私だけ？
android＋Chromeでファイル添付のボタンは反応したので、「画像を参照」ボタンの問題っぽいです。
とりあえず報告まで。

### iphone+safari
<img src="https://user-images.githubusercontent.com/2756509/83878690-80ad2880-a777-11ea-92a4-6c30a54ab853.jpeg" width="320px">

### android(9)＋Chrome
<img src="https://user-images.githubusercontent.com/2756509/83879279-5c9e1700-a778-11ea-8402-ddbf99f8171a.png" width="320px">

#### android＋Chromeでファイル添付のボタン
<img src="https://user-images.githubusercontent.com/2756509/83880478-295c8780-a77a-11ea-8643-2acf4d34020e.png" width="320px">

**Comment by yotaca** [comment]
iPhone + safari で試しましたが私も [画像を参照] ボタンが反応しませんでした。

**Comment by akagane99** [comment]
確認ありがとうございました。
やっぱtinymceでのボタンの作りがよくなさそう。ソース見てみます。

**Comment by akagane99** [comment]
このアップロード画面、公式機能でした。

画像のアップロードインターフェース、TinyMCE 4.6.5で追加された標準機能。（2017年8月6日）
https://www.tiny.cloud/blog/new-local-upload-simplifies-adding-images-tinymce/
　メモ
　日本語：画像を参照
　英語：Browse for an image

　connect-cmsのtinymce4.9.3
　https://github.com/opensource-workshop/connect-cms/blob/master/public/js/tinymce/tinymce.min.js

githubのtinymce公式で本件のissueあがってるけど、回答ついてないなぁ。ううーん。
https://github.com/tinymce/tinymce/issues/4656

**Comment by akagane99** [comment]
tinymceの画像アップロードプラグインで、下記に別のプラグイン jbimages がconnect-cmsにあったけど、使ってないプラグインかなぁ。
https://github.com/opensource-workshop/connect-cms/tree/master/public/js/tinymce/plugins/jbimages

**Comment by akagane99** [comment]
> iphone＋Safariだと「画像を参照」ボタンを押しても反応が悪く、たまに反応してくれる位。

iphone＋Safariをデバックしたらわかりました
下記赤丸の箇所（「画像を参照」ボタンの下線あたり）を押すと、画像アップロードのウィンドウ出てきました。

ここのタグが下記のようになっており、どうやら`<input type="file">`が平たく潰れているようです。
```html
<button>画像を参照</button>
<input type="file">
```

![83878690-80ad2880-a777-11ea-92a4-6c30a54ab853](https://user-images.githubusercontent.com/2756509/86849085-1971f380-c0ea-11ea-8b0e-419782605da9.jpeg)

ここを直せるかどうかは、wygwyigの公式機能の箇所で、わかってないです。
参考まで。

**Comment by akagane99** [comment]
## 継続調査メモ

https://github.com/tinymce/tinymce/blob/4.9.10/src/plugins/image/main/ts/ui/UploadTab.ts#L78
> type: 'browsebutton',

から
https://github.com/tinymce/tinymce/blob/4.9.10/src/ui/main/ts/BrowseButton.ts
を呼び出しかなぁ。

https://github.com/tinymce/tinymce/blob/4.9.10/src/ui/main/ts/BrowseButton.ts
から
https://github.com/tinymce/tinymce/commits/4.x/src/ui/main/ts/BrowseButton.ts
で変更なし。

とりあえずここまで。

**Comment by akagane99** [comment]
tinymce5系のデモの画像アップロードは、押せるようになっていたので、
tinymce5系にアップデートすれば解消しそう。

tinymce5系のデモ
https://www.tiny.cloud/docs/demo/full-featured/

![DBE9037A-40FB-48D1-9A52-464CCEFA3B9A](https://user-images.githubusercontent.com/2756509/86929970-6b119100-c171-11ea-8736-a7a755939663.png)

とりあえずここまで。

**Comment by akagane99** [comment]
#843 対応により問題解消しました。
クローズします。
