### ISSUE TITLE
【テーマ】スタイルシートのポリシーなど

### ISSUE THREAD

**Issue by yotaca** [opensource-workshop/connect-cms#360]
css をほぐして確認し、SCSS の構成についてはおおよそ理解できました。

１）現状の app.css、bootstrap.css、themes.css は同じなので、整理した方がよさそう。
　案１）laravel に従うなら、app.css に集約させる
　案２）css ファイルをわかりやすく整理するなら、bootstrap.css は別途読み込んで、差分を app.css で読み込ませる。
　fontawesome、tempusdominus-bootstrap-4、connect.css、プラグインごとのスタイルを別に読むので、
　カスタマイズごとに app.blade.php を触ることになるかもしれません。

２）SCSS の位置と編集方法など
　laravel デフォルトの〝resource/assets/sass/〟に配置するのがスマートです。
　
　全体的に、スタイルシートが散らばっている印象を受けるので、
　ヘッダー部分にコメントを書き込んたものをつなげておきます。
　参考にしてください、

　とりあえず、データベースプラグインは SCSS で書いてみました。
　追ってアップします。

**Comment by yotaca** [comment]
&lt;!-- Styles --&gt;
&lt;link href="/bootstrap4/css/bootstrap.min.css" rel="stylesheet" type='text/css'&gt; &lt;-- 追加
&lt;link href="/css/app.min.css" rel="stylesheet" type='text/css'&gt; &lt;-- 変更

１）bootstrap.min.css と app.css はほぼ同じなので、app.css で差分を上書きさせる。
　＊bootstrap のバージョンアップに対応しやすくなる。
２）sans-serif の指定は iOS デフォルトフォント〝-apple-system〟を外さない方がいい。
３）google Font のリンクはコメントされているので、sans-serif に〝Raleway〟を指定しない方がよい。

４）外国語対応を想定するなら、app.min.css で日本向けの設定にする。
　＊他国語については、追加時に都度作成する。

&lt;!-- Fonts --&gt;
&lt;link href="/fontawesome/css/all.min.css" rel='stylesheet' type='text/css'&gt;
＊できれば all.min.css だけ、/css/ に移動させたい。

&lt;!-- Scripts --&gt;
&lt;script src="/js/app.js"&gt;&lt;/script&gt;

&lt;!-- tempusdominus-bootstrap-4 --&gt;
&lt;link href="/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css" rel="stylesheet" type='text/css'&gt;
＊tempusdominus-bootstrap-4.min.css は公式で〝min〟ではなかったので、min に加工する。
＊できれば tempusdominus-bootstrap-4.min.css だけ /css/ に移動させたい。

&lt;script src="/js/moment.js/moment.min.js"&gt;&lt;/script&gt;
&lt;script src="/js/moment.js/locale/ja.js"&gt;&lt;/script&gt;
&lt;script src="/js/tempusdominus-bootstrap-4/tempusdominus-bootstrap-4.min.js"&gt;&lt;/script&gt;

&lt;!-- Connect-CMS Global CSS --&gt;
&lt;link href="/css/connect.min.css" rel="stylesheet" type='text/css'&gt;
＊ min に加工する。
＊ デフォルトプラグインのスタイルはここに追加する。

&lt;!-- Themes CSS --&gt;
&lt;link href="/themes/Defaults/Default/themes.css" rel="stylesheet" type='text/css'&gt;
＊ 内容はほぼ bootstrap.css と同じなので、app.css の意味があまりない。
＊ デフォルトテーマのスタイルは、カラーやパターンなど一部を変更させるだけにとどめた方がよい。
＊ カスタムテーマのスタイルもここで読み込める。
＊レイアウトを変更するのは難しいので、カラーチェンジャー とした方が妥当かもしれません。

&lt;!-- Themes JS --&gt;

&lt;!-- Connect-CMS Page CSS --&gt;
&lt;link href="/file/css/[ ページ ID ].css" rel='stylesheet' type='text/css'&gt;
&lt;!-- Context --&gt;
&lt;script&gt;&lt;/script&gt;

**Comment by yotaca** [comment]
ここを読んで app.css が sass でコントロールできるのが解りました。 
https://qiita.com/mk185/items/1508ac6172c73db7808b

少し触ったのですが、思い通りに動きそうなので @import 使わなくても良さそうです。
追って報告します。

**Comment by yotaca** [comment]
こちらのページを参考にして、データベースプラグインの SCSS を書いてみました。
https://qiita.com/mk185/items/1508ac6172c73db7808b

スタイルとテーマのポリシーについて、決めなければいけないことがいくつかあるかと思います。

**Comment by yotaca** [comment]
フォントについて少しまとめました

ゴシック系については、りのつか氏 の『font-familyについて本気で考えてみた』を参考にしました。
https://qiita.com/tsuka-rinorino/items/b30e03ce10aa38ac2a10
ただし、win10 游ゴシック についてフォントの組み替えを行なっていません。

等幅系はプログラミングフォントとして評価が高い『源ノ角ゴシック Code JP』を最優先に設定してます。デフォルトではありませんがコードを読む人ならインストールしているという希望的な設定です。

明朝系の欧文は Laravelで指定してある『Georgia』は数字の高さが合っていない〝オールドスタイル〟が表示される可能性があるので『Times New Roman』を指定しています。

現状、apple + chrome の相性が悪いので、apple のフォント設定が煩雑になってますが、今後解消される可能性もあるので注意していく必要があります。

日本語名を指定しないと表示されないような古いブラウザは切ってます。（IE7など）

Linux用 については『IPAフォント』や『Takaoフォント』でも構わないと思いますが『Noto Sans』が入ってなければデフォルトで表示されるので、それほど気にしなくても良いかと思います。
現在はそれほどシェアもありませんし。

以下、SCSS に設定しているものを転記しておきます。

`$font-family-sans-serif:
    -apple-system, //Apple デフォルト欧文フォント
    BlinkMacSystemFont, //Chrome, Opera デフォルト欧文フォント
    'Segoe UI', //win7〜 欧文フォント
    Roboto, //アンドロイド 欧文フォント
    'Hiragino Sans', //macOS, iOS11〜 日本語フォント
    'Noto Sans CJK JP', //Linux(Ubuntu), win(Note) 日本語フォント
    'Yu Gothic', //Win7〜 日本語フォント
    sans-serif, //デフォルトゴシック
    'Apple Color Emoji', //Apple 絵文字
    'Segoe UI Emoji', //Win7〜 絵文字
    'Segoe UI Symbol', //Win7〜 絵文字
    'Noto Sans Emoji' //アンドロイド 絵文字
    !default;

$font-family-monospace:
    'Source Han Code JP N', // 源ノ角ゴシック Code JP プログラミング用フォント
    Consolas, // win10 欧文フォント
    Courier, // apple + Chrome, Opera 欧文フォント
    'Hiragino Sans', // apple + Chrome, Opera 日本語フォント
    'Noto Sans Mono CJK JP Regular', // Linux(Ubuntu), win(Note) 日本語フォント
    monospace !default;

$font-family-serif:
    'Times New Roman', //欧文フォント
    YuMincho, // macos 追加インストールされている場合に表示される
    'Hiragino Mincho ProN', // apple + Chrome, Opera 日本語フォント
    'Yu Mincho', // Win7〜 日本語フォント
    'Noto Serif CJK JP', // Linux(Ubuntu), win(Note) 日本語フォント
    serif !default;`

**Comment by yotaca** [comment]
/vendor/ 以下のあるのは、bootstrap3 のような気がします。
変数名が微妙に違うので違和感はあったのですけど、こちらのファイルにこんな感じの記載がありました。
/vendor/laravel/framework/src/illuminate/Foundation/Console/Presets/Bootstrap.php
28行目『'bootstrap-sass' => '^3.3.7'』

node-modules の bootstrap4 を指定して読み込んでいるので、現状は bootstrap4 で間違いないとは思いますが、なにかのはずみで置き換わる可能性があるかもしれません。
不必要なファイルを削除した方がいいのかもしれませんが、私には判断がつきません。

他のモジュールは大丈夫なのでしょうか？

/public/fonts/vendor/ に置いてあるフォントが glyphicons だったので、よく考えれば default が  bootstrap3 なのは最初に疑うべきでした。

とりあえず、最初から変数を整理します。

**Comment by yotaca** [comment]
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="サイト詳細サイト詳細サイト詳細サイト詳細">
    <meta name="_page_id" content="1">
    <meta name="csrf-token" content="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx">
    <title>サイトタイトル</title>

    
    <link href="http://connect-cms/css/app.css" rel="stylesheet">
    ＊app.css に デフォルトブートストラップ、フォントアイコン、カレンダースタイル、デフォルトプラグインスタイル をまとめました。

    
    <script src="http://connect-cms/js/app.js"></script>
    <script src="http://connect-cms/js/moment.js/moment.min.js"></script>
    <script src="http://connect-cms/js/moment.js/locale/ja.js"></script>
    <script src="http://connect-cms/js/tempusdominus-bootstrap-4/tempusdominus-bootstrap-4.min.js"></script>

    
    <link href="http://connect-cms/css/connect.css" rel="stylesheet">
    ＊sass で変更できない時はここに書き足します。

    
    <link href="http://connect-cms/file/css/1.css" rel="stylesheet">

    
    <script></script>
</head>

**Comment by akagane99** [comment]
> /vendor/ 以下のあるのは、bootstrap3 のような気がします。
変数名が微妙に違うので違和感はあったのですけど、こちらのファイルにこんな感じの記載がありました。
/vendor/laravel/framework/src/illuminate/Foundation/Console/Presets/Bootstrap.php
28行目『'bootstrap-sass' => '^3.3.7'』

> node-modules の bootstrap4 を指定して読み込んでいるので、現状は bootstrap4 で間違いないとは思いますが、なにかのはずみで置き換わる可能性があるかもしれません。

お、これなんでしょうね？
多分無視して大丈夫かと思います。

Laravel5.5の標準はbootstrap3なんす。後付けでbootstrap4 対応させました。
`/vendor/laravel/framework/src/illuminate/Foundation/Console/` 配下は、laravelの`artisan`系のコマンドが転がってそうです。
https://github.com/laravel/framework/tree/5.5/src/Illuminate/Foundation/Console
`artisan`系のコマンドでなんかinstallとかできるなら参照されそうです。（ここよく知らない）

yotacaさんもおっしゃる通り Connect-CMSは `node-modules の bootstrap4 ` を使っていて、`/vendor/laravel/framework/src/illuminate/Foundation/Console/Presets/Bootstrap.php` を参照される事はないので、無視して大丈夫と思ってます。

**Comment by yotaca** [comment]
状況が見えていないのでサスペンドしておきます。
