### ISSUE TITLE
【データベース】登録・編集画面に確認画面が残ってる

### ISSUE THREAD

**Issue by akagane99** [opensource-workshop/connect-cms#374]
フォームプラグインベースのため、登録・編集時に確認画面機能がついちゃってる。
フォームでは確認画面必要だけど、データベースではブログの登録時と同様に不要なので、取り除く。

後々、確認画面をはぶく方向。

**Comment by yotaca** [comment]
確認画面があるとこととないとこがあるので、不思議に思っていたのですが、これ意図しない確認画面だったんですね。
納得です。

**Comment by akagane99** [comment]
とりあえず確認画面はある方向で進めるため、一旦クローズします。
必要になったら再オープンする感じで。
