### ISSUE TITLE
【データベース】defaultテンプレートのデザインを表形式から単票形式に変更

### ISSUE THREAD

**Issue by akagane99** [opensource-workshop/connect-cms#375]
* 新default(単票形式)
    * 現在のデータベースプラグインのdefaultテンプレートは表形式だけど、default（初期）のテンプレートは単票形式(※)がいいだろう。
    * 新default(単票形式)追加に合わせて、**設定に「行グループ」「列グループ」を追加**して、項目の横並びに対応
    * 「行グループ」「列グループ」追加に伴い、**機能してない 項目の型「まとめ行」を廃止**します。
        * （「まとめ行」は、フォームプラグインを基に作成されたデータベースプラグインの名残で残ってただけ。）
* 現defaultテンプレートは、tableテンプレートにリネーム
* 現tableテンプレートは、table_responsiveテンプレートにリネーム
* **既にデータベースプラグインのdefaultテンプレートを利用中の方は影響でます。** 以前の表示にしたい場合、フォーム編集のテンプレートから、`table`に変更してください。

## database テンプレート修正案

| 現database テンプレート | 修正後テンプレート | 修正後詳細画面 | 修正後行グループ・列グループ対応 | 詳細表示するページ ID・フレーム ID設定
| ---------------------------- | ----------------------- | ----------------- | -------------------------------- | --------------------------------
|                                    | default（新default） | default詳細画面       |  対応済み                               |  使わない
| default                        | table                          | default詳細画面       | 未対応                              |  使わない
|  single_sheet              | single_sheet      | single_sheet詳細画面       | 未対応                              |  使わない
| card                           | card                   | single_sheet詳細画面       | 未対応                              |  使わない
| list                             | list                      | single_sheet 詳細画面       | 未対応                              |  使わない
| menu                        | menu                  | single_sheet 詳細画面       | 未対応                              |  使う
| table                         | table_responsive | single_sheet 詳細画面       | 未対応                              |  使わない

### (※)単票形式の画面1 - PC幅表示 (行グループ・列グループ設定済み)
![image](https://user-images.githubusercontent.com/2756509/86304321-80565f00-bc49-11ea-9e88-149cbce8f097.png)
### (※)単票形式の画面2 - スマートフォン幅表示  (行グループ・列グループ設定済み)
![image](https://user-images.githubusercontent.com/2756509/86304332-84827c80-bc49-11ea-9abd-1aec6f68f800.png)
### (※)単票形式の画面3 -  PC・スマートフォン幅表示 (行グループ・列グループ未設定の場合)
![image](https://user-images.githubusercontent.com/2756509/86304336-877d6d00-bc49-11ea-9614-97e8ce43fcd7.png)

## 関連issue

【データベース】defaultテンプレートのUIと一覧表示の見直し(既に稼働しているサイトに影響ありのため) · Issue #366

**Comment by yotaca** [comment]
各テンプレートにテンプレート名でクラスを指定しています。
それらも変更対象になると思うので、スタイルシートも全面書き換える必要が出てきます。

現在 scss で書いてますけど、おそらくcss に直接書かれますよね。

どうしましょう。
プラグインのスタイルシートは app.css から切り離しますか？

**Comment by akagane99** [comment]
> 各テンプレートにテンプレート名でクラスを指定しています。
> それらも変更対象になると思うので、スタイルシートも全面書き換える必要が出てきます。

クラスって、`db-default`とか`db-tabel`であってます？
ほんとだ、テンプレートにそったクラス切ってありますね。気づいてなかった💦

> 現在 scss で書いてますけど、おそらくcss に直接書かれますよね。

css なんもいじってないんです。
上記の単票形式は bootstrap4 の class だけで実現できました。

> どうしましょう。
プラグインのスタイルシートは app.css から切り離しますか？

とりあえずそのままでー。

`db-default`とか`db-tabel`のsassって、どこかにあるんでしたっけ？
牟田口よくわかっておらず💦

**Comment by yotaca** [comment]
app.css では一番下あたりにまとめて記載しています。
sass のファイルは、
/resources/assets/sass/_plugin_database.scss がそれにあたります。

class名について、表示に関してはそこまで重要ではありません。
今後、カスタマイズする時のために class が基準になるように準備しているんです。
edy-k さんもどこかで〝class名で分けて欲しい〟みたいな要望を出されていたと思います。

どっちにせよ、クラス名とテンプレート名が違うとディベロパーが混乱するかもしれません。

これからのこともあるので、sass使うかどうか決めるタイミングかもしれません。
sass を使うのであれば、開発時のルールは必須になってくると思います。

**Comment by akagane99** [comment]
ありがとうございます！
https://github.com/opensource-workshop/connect-cms/blob/master/resources/assets/sass/_plugin-database.scss

おおお、がっつり書いてる。

> class名について、表示に関してはそこまで重要ではありません。
今後、カスタマイズする時のために class が基準になるように準備しているんです。
edy-k さんもどこかで〝class名で分けて欲しい〟みたいな要望を出されていたと思います。

となると `[$プラグイン名]-[$テンプレート名]` みたいなルールで、空クラスをテンプレートの埋め込んどけば、他の開発者が使いやすいかなぁ。

> これからのこともあるので、sass使うかどうか決めるタイミングかもしれません。
sass を使うのであれば、開発時のルールは必須になってくると思います。

💦💦💦
ごもっとも。

sass を使うのであれば、開発時のルールってどんなものをイメージしてます？
sassファイルの置き場とか、ファイル名とか、クラスの命名規則とかかなぁ。

とりあえず、DBテンプレ名とsassのクラスがずれてる件をissueにあげときます。

**Comment by yotaca** [comment]
開発者（プログラマー）は決まった箇所 css ファイルに追記していって、
コーダーが、その css をほぐしながら、scss ファイルを書いていく感じがいいと思います。

db のテンプレート書きながら気が付いたのですが、bootstrap のデフォルトクラスだけでレイアウトすると、
ディベロッパーがカスタマイズしにくくなります。

例えば、col-12 col-md-6 で指定してあった場合、３列表示させようと思ったら新たにテンプレートを作成する必要が出てきます。
しかし、専用クラスで指定したばあい、ページ毎のcssに、詳細指定（と言ったと思う）を入れればスタイルシートだけで片付きます。

ディベロッパーにしてみると、読み解きにくい 〝bleadファイル〟を触らないので工数を大きく減らせます。

いま具体的には示せませんけど、大体のイメージは伝わりましたでしょうか？

**Comment by yotaca** [comment]
あれ？　もしかして一般的な案件では、先にコーダーがデモの html を作成して、
プログラマはそれに合わせてソース組んでたりしませんか？

先に html 書いておけばプログラマさんは scss ファイルの位置とか気にしなくても済みますよね。
もしかしたら、その辺が違うからやりにくさを感じるのかもしれません。

**Comment by akagane99** [comment]
> あれ？　もしかして一般的な案件では、先にコーダーがデモの html を作成して、
プログラマはそれに合わせてソース組んでたりしませんか？

おお？一人プロジェクトが多いっすw
なのでhtml作らず、直でプログラムしてます。

コーダーさんは、htmlを組むデザイナーのイメージであってますかね？
うちいないなぁ💦

デザイナーさんと組むときは、ベースとなるCMSが先にあってそれに合わせてcss組んでもらう感じですね。

今回はベースとなるCMSをいじれる立場なんですが、デザイナーさんやコーダーさんの視点がないもんで、どう作ったら最なのか、わかってないのです。

> db のテンプレート書きながら気が付いたのですが、bootstrap のデフォルトクラスだけでレイアウトすると、
ディベロッパーがカスタマイズしにくくなります。

どうするのがいいのかなぁ。
bootstrap のデフォルトクラスだけ作るのが、まずそうな感じですかね？
テンプレート毎の追加の空クラスあったら、ちょっとはいいのかなぁ。

bootstrap のデフォルトクラスと追加のクラスを、どの程度使うかのいい塩梅なのか、知りたいかなぁ。そこらへん探っていきたいです。

今回単票で使ったのは、col-12 col-md-6 とか細かいことやってなくって。
col か col-sm位なんです。これなら大丈夫なんかなぁ。

https://github.com/opensource-workshop/connect-cms/blob/d702513e9d6ff9f04c9da15df61daac58ee3e947/resources/views/plugins/user/databases/new_default/databases.blade.php

**Comment by yotaca** [comment]
私もほとんど1人で片付けてますけど、デザイナさんにお願いするときはこんな感じです。
１）デザイナさんにイラレで納品してもらう。
２）使用する CMS を考慮して HTML組んむ。
３）CMS のプラグインなどに手をつける。

私はデザイナさんに CMS のことを意識せずにデザインして欲しいので html まで手をつけて欲しくないんです。


コーダーって呼び方は日本独自のものらしく、html を書く人に最適な呼び方として広まっています。
https://persol-tech-s.co.jp/hatalabo/it_engineer/283.html

私自身が一番得意なのはこの部分です。


bootstrap で全てを作るとカスタマイズの幅が狭くなると思います。
具体例を挙げると、データベースプラグインのテーマ〝card〟と〝list〟はほぼ同じ html を書き出してます。
違うのは、最初の class の部分だけです。

scss で書いた該当部分を抜き出しました。
オリジナルクラスを作成しておけば同じ html コードであっても、違う幅を指定することが 可能です。

もし、bootstrap の col-12 col-md-6 と書いていたら、同じコードで違うレイアウトを表示させるのはかなり難しいと思います。

カスタマイズする時に『フレームに任意のclass名』を付けることができれば、コーダーは bleadファイルを一切触らなくても違うレイアウトにすることが可能になります。
『フレームに対するテンプレート名のクラス追加を検討願えないでしょうか』 https://github.com/opensource-workshop/connect-cms/issues/336

===============
// データベース：リスト
.db-list .db-adata{
        width: 100%;
    }
@media (min-width: map-get($grid-breakpoints, 'md')) {
    .db-list .db-adata{
        //左右二分割用
        width: calc(50% - 0.5rem);
    }
    }

// データベース：カード
.db-card .db-adata{
        width: 100%;
    }
@media (min-width: map-get($grid-breakpoints, 'md')) {
    .db-card .db-adata{
        width: calc(50% - 0.5rem);
        margin-right: 0.5rem;
    }
    }
@media (min-width: map-get($grid-breakpoints, 'lg')) {
    .db-card .db-adata{
        width: calc(33% - 1rem);
        margin-right: 1rem;
    }
    }
@media (min-width: map-get($grid-breakpoints, 'xl')) {
    .db-card .db-adata{
        width: calc(25% - 1rem);
    }
    }
===============

個人的な見解ですが、bootstrap を使うのは大まかなレイアウトと共通のアイテム（ボタン、ボックス、メニューなど）に留めた方が bootstrap らしさをなくすことができて、デザインに幅を持たせることが可能になります。

同じ html なのに、css を切り替えるだけでテーマが変わるシステムとかとてもワクワクしてしまいます。
この辺に萌える自分が〝コーダー〟なんだなぁと思います。

**Comment by yotaca** [comment]
> 今回単票で使ったのは、col-12 col-md-6 とか細かいことやってなくって。
> col か col-sm位なんです。これなら大丈夫なんかなぁ。

default で単票表示ならば構わないと思います。

現在、ローカルにマージできなくてなにも確認できてません。
一度全部クリアにしたいくらいです。

**Comment by masaton0216** [comment]
@yotaca クラス追加であれば邪魔にならんだろうと考え、ひとまず追加してみました。
下記に対応後のクラスイメージありますので、要望に沿ってるかご確認頂けますか？
https://github.com/opensource-workshop/connect-cms/issues/336

**Comment by yotaca** [comment]
> @yotaca クラス追加であれば邪魔にならんだろうと考え、ひとまず追加してみました。
> 下記に対応後のクラスイメージありますので、要望に沿ってるかご確認頂けますか？
> #336

お疲れさまです。
ムタさんに後処理任せちゃって恐縮しております。

ところで、フレームにつけるclass名は自動で生成するものではなく、任意のものが必要だと思います。
っとここまで書いたところで確認してみたら、すでにフレームに class名 を設定できるようになってますね。

ローカルがぐちゃぐちゃでまともに動いてないのでちゃんと確認できないのですが、この class名 がちゃんとつけば問題はないかと思います。

![スクリーンショット 2020-07-02 21 11 55](https://user-images.githubusercontent.com/8961306/86357608-0bb30d00-bca9-11ea-8b92-d3afbbbc1163.png)

**Comment by masaton0216** [comment]
@yotaca はい、既にその機能はあるんです。それを踏まえた上での先述の要望（フレームに対するテンプレ名クラス追加）かと思い追加してみました。
ちなみにウチの案件でデザイナにお願いする時は、任意のクラス名にフックしてスタイル適用してもらってます。

**Comment by yotaca** [comment]
@masaton0216 だったら、大丈夫だと思います。

個人的にコード触ったりするのはデザイナの仕事じゃないと思ってるので、あまりやらせたくないんです。
コードよりも、色とか、バランスとか、その人の持ってる感性の部分を提供して欲しいんです。
ライターとしての能力が備わっていればもうなにも言うことはありません。

前職が印刷会社の製版部門だったのでそんな風に考えるようになったんだと思います。

**Comment by akagane99** [comment]
> っとここまで書いたところで確認してみたら、すでにフレームに class名 を設定できるようになってますね。

知らないかった！
教えてくれてありがとうです。

問題なさそう & 単票形式に変更済みなので、issueクローズしちゃいますねー。
