### ISSUE TITLE
【データベース・フォーム】設定画面＞項目設定の詳細ボタンは緑色がいいかも

### ISSUE THREAD

**Issue by akagane99** [opensource-workshop/connect-cms#381]
・登録「＋」、更新「💾」は、実際に登録・更新処理が走るので、青色
・登録画面等に遷移するボタン「新規登録」「詳細」「編集」は、緑色
・データベース・フォームの設定画面＞項目設定の「詳細」ボタンは、詳細編集画面に遷移するので、緑色　かと思う。

今後直したいなぁと。

## データベース 設定画面＞項目設定の詳細ボタン
![image](https://user-images.githubusercontent.com/2756509/86416136-24044580-bd04-11ea-89b7-25cd9d42ffce.png)

## フォーム 設定画面＞項目設定の詳細ボタン

![image](https://user-images.githubusercontent.com/2756509/86416187-41d1aa80-bd04-11ea-87a4-e331e60f346d.png)

## 参考：データベース 設定画面＞項目設定の詳細変更画面

![image](https://user-images.githubusercontent.com/2756509/86416384-b573b780-bd04-11ea-9f36-ebf4d33bb4f7.png)

**Comment by yotaca** [comment]
更新ボタンの話がでてるので、前から感じてたことを書いておきます。
最近は〝フロッピーディスク〟= 保存 のイメージを持つ方が少ない上に、アイコンが〝南京錠〟に見えます。
〝更新〟は他に合わせてチェックマークの方が良いかもしれません。

ここでは出てませんが〝キャンセル〟も〝戻る〟の方がイメージが掴みやすいかも。

**Comment by akagane99** [comment]
ご意見参考にさせてもらいます。
UI見直しはもうちょっと先かなぁ。

全体見直しに派生すると、今はちょっと手が出せないなぁ。
余裕でてきたら、やる感じで。

**Comment by akagane99** [comment]
メモ

## データベース 設定画面＞項目設定＞複数選択型＞詳細にもボタンあり

![image](https://user-images.githubusercontent.com/2756509/86594281-b68d3900-bfd1-11ea-8c1f-a6c1db9d8ecb.png)

**Comment by akagane99** [comment]
* database plugin対応済み
  * [change: database plugin, 項目設定の詳細ボタンは画面遷移のため、btn-primary⇒btn-success（青⇒緑色）に変更](https://github.com/opensource-workshop/connect-cms/pull/515/commits/9cdc1fd4f69ae4e34420c60b885dff85c3ef34ac)
  * [change: database plugin, DB選択一覧画面の設定変更ボタンは画面遷移ボタンのため、btn-primary⇒btn-successに変更
change: database plugin, DB選択一覧画面のダウンロードボタンは実行ボタンのため、btn-success⇒btn-primaryに変更](https://github.com/opensource-workshop/connect-cms/pull/515/commits/a1c24a213988380a78c31c6fed31a6c4d4ec4a31)
* forms plugin対応済み

**Comment by akagane99** [comment]
上記対応したため、クローズします。
