### ISSUE TITLE
【データベース】メールアドレス型の表示方法追加の検討

### ISSUE THREAD

**Issue by akagane99** [opensource-workshop/connect-cms#393]
とりあえず検討のみ。
実装はまだ先。

### 表示方法を選択できるように
* 表示タイプ１：＠のみ~~画像~~`<i class="fas fa-at"></i>`(絵文字フォントの@)に変換
* 表示タイプ２： 見た目は普通のメールアドレス、クリックするとmailtoの動作
    * けれどもシステム内部では、Javascriptの [DecryptStringメソッド](https://biz-collections.com/support/webpages/html/onlinemanual/browser/crs/pac/sec/sec2m5.htm) を使って登録時にメールアドレスを暗号化。表示時にJavaScriptで複合化、かなぁ。

**Comment by yotaca** [comment]
@akagane99 
〝＠〟を `<i class="fas fa-at"></i>`にするのはどうですか？

**Comment by akagane99** [comment]
＠フォントあるんだ！？
賛成！

**Comment by yotaca** [comment]
あとは、やったことないけど文字を埋め込んだ svg ファイルを直書きという手もあるかもです。

**Comment by yotaca** [comment]
ふと思ったのですがメアド回収ロボットを回避するのなら、オリジナルクラスを作っておいた方がいいかもしれません。
'<b class="tnk"></b>' とかだと知られにくいかも。

クラスをアクセスごとに変えられるともっと強力になるかもしれません。
