### ISSUE TITLE
【サイト管理・バグ】サイト名が サイト管理＞サイト基本設定 以外適用されない

### ISSUE THREAD

**Issue by masaton0216** [opensource-workshop/connect-cms#409]
![image](https://user-images.githubusercontent.com/13323806/87109109-c2614f80-c29e-11ea-8558-31d2bdc3eddf.png)
![image](https://user-images.githubusercontent.com/13323806/87109116-c5f4d680-c29e-11ea-9e6b-3d3e87257666.png)

- サイト管理のページと各コンテンツページは適用したサイト名が表示される
- ページ管理等、他の管理系ページはおそらくサーバ側のenvファイルの値が出てると予想

**Comment by akagane99** [comment]
・サイト管理＞サイト基本設定　のみ　`設定したサイト名`　表示される。
・サイト管理＞mata情報　等　サイト管理でも　`設定したサイト名`　表示されない。

**Comment by akagane99** [comment]
> ・サイト管理＞mata情報　等　サイト管理でも　設定したサイト名　表示されない。

`.env`の`APP_NAME` の設定値が表示されてました。

**Comment by akagane99** [comment]
下記箇所で、サイト名を表示していました。

[resources/views/layouts/app.blade.php](https://github.com/opensource-workshop/connect-cms/blob/master/resources/views/layouts/app.blade.php)
```html
@if(isset($configs))
    <title>@if(isset($page)){{$page->page_name}} | @endif{{$configs['base_site_name']}}</title>
@else
    <title>@if(isset($page)){{$page->page_name}} | @endif{{config('app.name', 'Connect-CMS')}}</title>
@endif
```

・通常画面では、`$page->page_name`で表示してそう
・サイト管理＞サイト基本設定では、`$configs['base_site_name']` で表示してそう
・サイト管理＞サイト基本設定以外では、`config('app.name', 'Connect-CMS')` が表示されてそう。

**Comment by akagane99** [comment]
対応しました。

・マイページでサイト名が表示される事を確認
・管理画面でサイト名が表示される事を確認
・通常画面でサイト名が表示される事、タイトルが表示される事を確認

resources/views/layouts/app.blade.php　で表示していた下記ロジックを
```php
        @if(isset($configs))
            {{$configs['base_site_name']}}
        @else
            {{ config('app.name', 'Connect-CMS') }}
        @endif
```



app/Http/Middleware/ConnectInit.phpの　handleメソッドに移植して、全ビュー間のデータ共有する `\View::share()` 
でセットしました。

[app/Http/Middleware/ConnectInit.php](https://github.com/opensource-workshop/connect-cms/blob/master/app/Http/Middleware/ConnectInit.php#L42)
```php
        /* --- 共通で使用するDB --- */

        // Connect-CMS の各種設定
        // bugfix:【サイト管理・バグ】サイト名が サイト管理＞サイト基本設定 以外適用されない対応
        // $request->attributes->add(['configs' => Configs::get()]);
        $configs = Configs::get();

        // requestにセット
        $request->attributes->add(['configs' => $configs]);

        // *** 全ビュー間のデータ共有
        // サイト名
        if (isset($configs)) {
            $base_site_name = $configs->firstWhere('name', 'base_site_name');
            $configs_base_site_name = $base_site_name->value;
        } else {
            $configs_base_site_name = config('app.name', 'Connect-CMS');
        }
        \View::share('configs_base_site_name', $configs_base_site_name);
```

## 修正プログラム
https://github.com/opensource-workshop/connect-cms/pull/767/files
