### ISSUE TITLE
【機能追加】スライダープラグイン

### ISSUE THREAD

**Issue by masaton0216** [opensource-workshop/connect-cms#446]
- 画像の複数アップ、削除機能
- インジケータとコントローラのデザイン調整機能

**Comment by akagane99** [comment]
カルーセル＝スライダーかな？

**Comment by masaton0216** [comment]
この辺を使うイメージ
https://getbootstrap.jp/docs/4.1/components/carousel/

**Comment by akagane99** [comment]
スライダーだね、了解ー。

**Comment by akagane99** [comment]
## 参考画面
### 表示画面
![image](https://user-images.githubusercontent.com/2756509/93545669-f42c1c00-f99b-11ea-8896-13d1cf93202e.png)

### スライド編集画面
![image](https://user-images.githubusercontent.com/2756509/93545700-0b6b0980-f99c-11ea-9e18-37301ab752de.png)

### スライド設定画面
![image](https://user-images.githubusercontent.com/2756509/93545719-16be3500-f99c-11ea-9f5c-719533990ace.png)

**Comment by nagasheep** [comment]
アイデアIssue に移したので、こちらはCloseします。
https://github.com/opensource-workshop/connect-cms-ideas/issues/8
