### ISSUE TITLE
【フォームプラグイン】ファイル型の追加

### ISSUE THREAD

**Issue by masaton0216** [opensource-workshop/connect-cms#489]
- 管理者宛の設定メールがあればそちらに添付する。
- データをサーバに残さない設定の場合、サーバにファイルは保存しない。

**Comment by akagane99** [comment]
対応しました。

・フォームにファイル型を追加しました。
・フォームにファイル型があり、メール通知する場合、メールにファイルを添付できます。
・フォーム設定で「データ登録しない」場合、登録したファイルは削除されます。
・フォーム設定の「メールの添付ファイル制御」で、ファイルを通知メールに添付するか制御できます。
・登録されたファイルを確認するため、登録一覧画面を追加しました。
・フォームに重複登録される事を想定して、登録一覧＞編集で登録データを削除扱いにできるようにしました。

## 画面

### 登録画面（ファイル型）

![image](https://user-images.githubusercontent.com/2756509/97278301-f3c94f80-187c-11eb-8698-56cd9beb29f8.png)

### 確認画面（ファイル型）

![image](https://user-images.githubusercontent.com/2756509/97278874-9da8dc00-187d-11eb-9afe-5174686737d3.png)

### 項目設定（ファイル型の追加）

![image](https://user-images.githubusercontent.com/2756509/97277875-5ff78380-187c-11eb-87ab-3c32545f72a4.png)

### フォーム設定（メールの添付ファイル制御）
![image](https://user-images.githubusercontent.com/2756509/97279056-d34dc500-187d-11eb-969e-1be852958d60.png)

### 登録一覧
![image](https://user-images.githubusercontent.com/2756509/97276219-405f5b80-187a-11eb-93a1-362e9f811f7b.png)

### 登録一覧＞編集画面
![image](https://user-images.githubusercontent.com/2756509/97276402-7997cb80-187a-11eb-9a7a-596a90ef51b4.png)



## 主なcommits

* add: フォーム、ファイル型追加
* add: フォーム、登録一覧画面、登録一覧からの編集画面の追加 
* add: フォーム設定、メールの添付ファイル制御を追加 …
* add: フォーム、ファイル型でメール添付できる機能追加
* change: フォームのenum, FormColumnTypeをEnumsBaseを継承するように修正
* change: フォームのCSVダウンロード、基本ないが、forms_input_colsにデータが無い場合にも対応(登録一覧の表示は、forms_input_colsがない場合にも対応していた)
* change: フォーム、フォーム未選択時のメッセージの共通化
