### ISSUE TITLE
migrate でエラーが出ました

### ISSUE THREAD

**Issue by yotaca** [opensource-workshop/connect-cms#494]
しばらくほっておいたのがまずかったのですが、まとめてmergeしたところ、migrate でエラーが出ました。

In Connection.php line 664:
SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '0000-00-00 00:00:00' for column 'posted_at' at row 1 (SQL: alter table `databa  
  ses_inputs` add `posted_at` datetime not null comment '公開日時' after `status`) 

In PDOStatement.php line 129:
SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '0000-00-00 00:00:00' for column 'posted_at' at row 1  

In PDOStatement.php line 127:
SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '0000-00-00 00:00:00' for column 'posted_at' at row 1

MySQLの設定で許可されたりできなかったりするのであれば '1000-01-01 00:00:00' みたいなデータを入れた方がいいような気がします。
いかがでしょうか？

**Comment by yotaca** [comment]
0000-00-00 00:00:00 がどこで設定されているのか知りたかったので、検索したのですがヒットしませんでした。
もしかしたら、ローカルので空欄の場合は 0000-00-00 00:00:00 を入れるように設定れているものなのでしょうか？

**Comment by akagane99** [comment]
すみません、昨日マージした機能のバグです。
今修正しました。

https://github.com/opensource-workshop/connect-cms/commit/7cee321170e8e2e36935e1b1fbab5a5c22665bc8

再度git pullして

https://github.com/opensource-workshop/connect-cms/issues/490

**Comment by akagane99** [comment]
修正済みため、クローズします。
