### ISSUE TITLE
【データベース】表示設定・表示件数が数値以外も受け付ける

### ISSUE THREAD

**Issue by syunke** [opensource-workshop/connect-cms#506]
表示設定・表示件数のバリデーションがされていないためか、数値以外も受け付ける
![image](https://user-images.githubusercontent.com/14014459/91212938-ddebc100-e74b-11ea-9b6a-74571e90c353.png)

**Comment by akagane99** [comment]
ご連絡感謝。今後直しますね

**Comment by akagane99** [comment]
https://github.com/opensource-workshop/connect-cms/commit/9a24d13026eb222a37e2a3729e99769abfb350b2

丁度データベースプラグインをいじっていましたので、上記で修正しました。
（数値チェックのバリデーションが抜けていたので追加しました。）

## 修正後画面
![image](https://user-images.githubusercontent.com/2756509/91242176-b0ba0580-e781-11ea-9359-b62efe7c740b.png)
