### ISSUE TITLE
ブログのtwitter連結

### ISSUE THREAD

**Issue by nagasheep** [opensource-workshop/connect-cms#51]
・ブログの投稿をtwitterにポスト
・twitterの投稿をブログに取り込み

**Comment by akagane99** [comment]
line連携、転記

> 共有系（GoogleとかLINEとか）の仕組み興味あっても、調べられてなかったんですが、
LINEの共有ボタンってGAのコード埋め込みのような感じで簡単にできるんですね。

> ![image](https://user-images.githubusercontent.com/2756509/87018793-b2009480-c20c-11ea-8e09-2be02c8bc8dd.png)

> コードの生成は↓
https://social-plugins.line.me/ja/how_to_install#lineitbutton
