### ISSUE TITLE
【コア】artisan make:pluginコマンドがほしい

### ISSUE THREAD

**Issue by masaton0216** [opensource-workshop/connect-cms#511]
- コマンド実行時にプラグイン名を入力
- 動作する最小構成のアプリを生成
-- コントローラ（XxxPlugin.php）
-- view（xxx.blade.php）
-- （yes/no選択制）model（Xxx.php）
-- （yes/no選択制）migration（create_xxx_table.php）

**Comment by nagasheep** [comment]
賛成。欲しいね。
