### ISSUE TITLE
災害時モード

### ISSUE THREAD

**Issue by nagasheep** [opensource-workshop/connect-cms#529]
処理を最小限にして、アクセスの急増に耐えるようなものが欲しい。

**Comment by akagane99** [comment]
別の切り口だと、静的HTML出力できれば、ある程度対応できるのかなぁと妄想。

**Comment by nagasheep** [comment]
静的HTMLか。

複数校を想定した場合で考えてみた。

1校のみを技術的な観点からだけ考えれば、
・緊急時モードをON
・最低限、必要な情報だけのページになる。
・CMSでは、DB読む前の段階で、HTMLページにリダイレクト
（Apache のドキュメントルートの設定修正とかは現実、やってられないし）
という感じかな。

問題点は、
・各校で切り替え作業を行うとした場合、やってもらえるのか。
かな。

**Comment by akagane99** [comment]
重複issue
https://github.com/opensource-workshop/connect-cms/issues/90

**Comment by akagane99** [comment]
## 参考事例：町田市ホームページ

### PC表示
![www city machida tokyo jp_(Laptop with MDPI screen)](https://user-images.githubusercontent.com/2756509/96356011-da5d3080-1123-11eb-864b-0ea36e6714cc.png)

### スマートフォン表示
![www city machida tokyo jp_(iPhone 6_7_8)](https://user-images.githubusercontent.com/2756509/96356012-dcbf8a80-1123-11eb-8b8f-426c7d0cd28d.png)


### 防災訓練メール
```
町田市総合防災訓練の実施に伴いホームページを非常時用トップページに切り替えます
----
本日午前9時から10時30分まで町田市総合防災訓練を実施します。
これに伴い、「町田市ホームページ」を、災害時に必要な内容に情報をしぼった「非常時用トップページ」に切り替えます。
通常のトップページは画面右上のボタンで表示を切り替えてご覧ください。

※「町田市メール配信サービス」「町田市公式LINE」にご登録いただいている全ての方に送信しています。
```

### URL

https://www.city.machida.tokyo.jp/

**Comment by akagane99** [comment]
転記
https://github.com/opensource-workshop/connect-cms/issues/90
> 災害種別毎のテンプレート
避難所フォーマット
