### ISSUE TITLE
ユーザーの状態を持つ

### ISSUE THREAD

**Issue by nagasheep** [opensource-workshop/connect-cms#535]

**Comment by nagasheep** [comment]
ログイン不可の対応

**Comment by akagane99** [comment]
利用不可で対応済み
![CC6D8CFB-165E-4408-A1DE-35A3B7BD890C](https://user-images.githubusercontent.com/2756509/132421537-bedb702d-ff6a-4cef-9fb5-6012801dd1a1.jpeg)
