### ISSUE TITLE
【データベース・バグ】DBが選択されていない状態で「表示設定」タブを選択するとエラーとなる

### ISSUE THREAD

**Issue by syunke** [opensource-workshop/connect-cms#537]
DBが全く作成されていない状態や、DBが選択されていない状態で「表示設定」タブを選択すると
 Error:500 internal server error.となる。

**Comment by akagane99** [comment]
ご連絡感謝です。今後修正します。

**Comment by akagane99** [comment]
https://github.com/opensource-workshop/connect-cms/commit/8cf8e292fba18e5b188ddec505241dc8cb38889f

上記で対応しました。
