### ISSUE TITLE
【OPAC・バグ】OPAC新規作成で貸出設定と貸出冊数が無選択で登録確定できてしまう

### ISSUE THREAD

**Issue by syunke** [opensource-workshop/connect-cms#551]
OPAC新規作成より、貸出設定と貸出冊数が無選択で登録確定できてしまう。
結果 Error:500 internal server error.となる。
またOPAC設定(歯車)に入れなくなるので注意（削除もできなくなってしまう）。
![2bc5bf88c832234b5963a95682697b7b](https://user-images.githubusercontent.com/14014459/92987492-ce1afd80-f4fd-11ea-918b-c8aee893f3e2.png)

**Comment by akagane99** [comment]
ご連絡ありがとうございました。
修正対応しましたので、クローズします。

## 修正プログラム

https://github.com/opensource-workshop/connect-cms/commit/53373260592d9b6e90ce904173690e59dce898ab
