### ISSUE TITLE
【データベース・バグ】型が選択型の時に登録時エラーとなる

### ISSUE THREAD

**Issue by syunke** [opensource-workshop/connect-cms#579]
データベースの型が、単一選択型や複数選択型、リストボクスなどの選択型の場合に確認画面を押すとバリデーションエラーとなり登録ができない。
![](https://i.gyazo.com/e72eaf7d4c0d0a4b920b10ae2852e659.png)
ただし、新規作成されて項目で初めての選択肢は登録ができる。
２回目の選択肢より選択ができなくなる。
エラーの文を見ると、２回目の登録から後ろに「○○”」のようにダブルクオーテーションが付きダブルクオーテーションのある場合には登録ができない。
なお、都道府県を追加の場合は、エラー文が
「青森県”」のように県名の後にダブルクオーテーションが付く県は登録できずエラートなる。
「福井県」のように後ろにダブルクオーテーションが付かない県は登録できる。

**Comment by akagane99** [comment]
下記環境で、選択肢に「単１"」を設定して登録したけど、不具合再現できませんでした。
なんだろう？

## 環境
win10
新edge
Connec-CMS本日最新版

## 再現手順

1. データベースの選択肢に、「単１"」を登録
1. データベースに新規登録ボタンで、上記選択肢を選ぶ
1. 確認画面を表示
1. 登録できた

**Comment by syunke** [comment]
今の状況では、問題なく動きました。
closeしていただけないでしょうか。

環境なのか原因がわからなかったのですが今後も、
確認していきたいと思います。
お騒がせいたしました。

![](https://i.gyazo.com/c93663809d722ce082b1b053ed67bd0c.png)


OS:windows10
ブラウザ:Google Chrome
xampp
php7.4.9

**Comment by akagane99** [comment]
確認おそくなってすみません & 再確認ありがとうございました。
クローズします。
