### ISSUE TITLE
【要望】ルーム等が「準備中」だった時に分かりやすくして欲しい

### ISSUE THREAD

**Issue by osws-makino** [opensource-workshop/connect-cms#608]
## 概要
【NC3の使いにくいさからconnect-CMSには実装して欲しい事】

NC3はどのルームが現在準備中なのか分かりにくい（管理＞ルーム管理、の一覧でしか分からない）
　⇒NC2の場合、メニューのページ名の横に（準備中）と赤字で記載されていた。
　⇒なので、そのページへの構築権限がある人が見た時に、メニュー等に（準備中）等と分かりやすく表記して欲しい。アイコンや色で意味をあらわすんでも可

**Comment by akagane99** [comment]
Connect-CMSはルームって概念がないので、どこに該当するんだろう？

**Comment by osws-makino** [comment]
そもそも、connect-CMSには「準備中にする」的な概念は存在しなかったり？？

**Comment by akagane99** [comment]
ん？
ルーム等が具体的に何に該当するかわかんないので、そのステータスになに持ってるかわかんないのです。

**Comment by osws-makino** [comment]
ええと……要は「当該ページが『準備中』に相当するステータスに出来る時、当該ページが『準備中』ステータスである事を、分かりやすくして欲しい」って感じです。
「当該ページ」が「ルーム」であるか否か、connect-CMSが「ルームという概念を持つ」かどうかはこの際気にしてないです。
（そもそも、NC2・NC3の時、「ページ」自体に「準備中」というステータスを持たせられなかったのも、どうなんだろうと思っていましたし）

今『準備中』というステータスがない仕様であれば、不要な機能ですねー。
今後実装予定があるのであれば、意識してくれると嬉しい機能ですねー。

**Comment by akagane99** [comment]
ルーム等＝ページって事かなぁ。

ページであれば、「メンバーシップ」ってのがあって、ページ管理の一覧で鍵アイコン（＝メンバーシップ）が、開いたり・閉まったりアイコンが表示されてました。
https://connect-cms.jp/manual/manager/page

でもここの鍵アイコンは、メンバーシップのページかどうかの表示だから違うかぁ。

NC2/3のルーム『準備中』は、まとまったページの非公開設定かと思うので、今んとこConnect-CMSには無さそうな機能かと思います。

> 今後実装予定があるのであれば、意識してくれると嬉しい機能ですねー。

そうですねー。

**Comment by nagasheep** [comment]
NCでいうところの「準備中」ページとは、
・意図としては、作り途中を示しておくためのもの。
・機能としては、ユーザーの持つ基本の権限が「システム管理者」もしくは「管理者」にのみ、閲覧できるページ。
・表示としては、ページ名の横に赤字で（準備中）と表示する。
というところかな。

**Comment by nagasheep** [comment]
Connect-CMS で、機能だけなら、「管理者グループ」作って、メンバー設定。「メンバーシップページ」にして、「管理者グループ」のみ許可する。ってしとけば、とりあえず、できることはできる。
（公開するときにメンバーシップページから公開に変更）

でも、作り途中のページ。をわかりやすくしておくのは、使いやすさになると思うので、良い方法を考えたいですね。

**Comment by osws-makino** [comment]
そうですね。ほぼそんな感じです。
ありがとうございます。

その点で１つ要望を上げるとすると
＞・機能としては、ユーザーの持つ基本の権限が「システム管理者」もしくは「管理者」にのみ、閲覧できるページ。
この部分です。
見える権限を「システム管理者」「管理者」ではなく、編集権限を持っている人（※投稿権限ではなく、フレーム配置ができる権限）以上、という風にして欲しい。

これ、NC3は、そのページにルーム管理者権限を持っていたとしても、本来の権限が「管理者」以上じゃないと見えないという、なんだかとってもバグに近い仕様をしている事によって、サポートが大変だった事がある為です。

**Comment by osws-makino** [comment]
＞でも、作り途中のページ。をわかりやすくしておく

これ、是非お願いしたいところです。
その為に「NC2、NC3ではここが使いにくかった」という意見は出しますので。
（ただ、connect-CMSの方の仕様をあまりしらないので、今回のようにズレた意見を言ってしまうかもしれませんが）

**Comment by nagasheep** [comment]
> 見える権限を「システム管理者」「管理者」ではなく、編集権限を持っている人（※投稿権限ではなく、フレーム配置ができる権限）以上、という風にして欲しい。

権限を条件とするか、そもそも、見えるユーザを指定するか。も、話し合ってみたいですね。
いまのところ、Connect-CMSでは見えるユーザを指定する。の方式です。

**Comment by osws-makino** [comment]
あー。なるほど。そうですねー。その観点も必要ですね。
色々サポートをしている上で実感しているのは「ユーザー単位」です。
そのサイトを更新する人の人数が多くなればなるほど、（サイトの規模ば大きくなればなるほど）、「権限で振り分けるのやめて―」と思う事が多いので。

あと必要なのは、「準備中ステータスにできる人」と「見えるユーザーを誰が指定できるのか」を考慮する事かと。
ここが少しズレただけで、使いにくいものになってしまったりするので。

**Comment by nagasheep** [comment]
このネタだけで、1回、Zoom 会議しても良いかな。
いつすべきか、タイミングにちょっと悩むけど。

**Comment by osws-makino** [comment]
そうですね。
少なくとも今ではないのかもしれないですね。
