### ISSUE TITLE
【フォーム】メールアドレス型に特定ドメインのみ受け付けるバリデーションの追加

### ISSUE THREAD

**Issue by masaton0216** [opensource-workshop/connect-cms#647]

**Comment by akagane99** [comment]
本日追加した正規表現チェックを、メールアドレス型にも対応させることでも、対応可能だねぇ。
https://github.com/opensource-workshop/connect-cms/commit/9dcbef4ac4127fa8023dee6df6d0b0febcde0b3e

**Comment by akagane99** [comment]
対応しました。

## 修正プログラム
https://github.com/opensource-workshop/connect-cms/commit/024a6264e687563d67150d811bebbc168d077319

**Comment by masaton0216** [comment]
@akagane99 正規表現の例はプレースホルダじゃない方が個人的にはいいな。私みたいに正規表現すぐ忘れる頭の人は見ながらやりたいｗ なんならコピペで使えるレベルで（大盛り要求

**Comment by akagane99** [comment]
確かに正規表現のサンプルあると便利だよね。

正規表現を考えるのがむずいので、直してええんやで。
https://github.com/opensource-workshop/connect-cms/blob/master/resources/views/plugins/user/forms/default/forms_edit_row_detail.blade.php#L340

**Comment by akagane99** [comment]
https://github.com/opensource-workshop/connect-cms/issues/647#issuecomment-710014810
> 正規表現の例はプレースホルダじゃない方が個人的にはいいな。私みたいに正規表現すぐ忘れる頭の人は見ながらやりたいｗ なんならコピペで使えるレベルで（大盛り要求

対応しました。
https://github.com/opensource-workshop/connect-cms/commit/8c03c1bcaef5d593068e20eb14b44cea46e6fbb3
> ※ （設定例：電話番号ハイフンあり）/0\d{1,4}-\d{1,4}-\d{4}/
※ （設定例：指定ドメインのメールアドレスのみ）/@example\.com$/
