### ISSUE TITLE
リファクタリング 不要そうなbootstrapファイルの削除

### ISSUE THREAD

**Issue by masaton0216** [opensource-workshop/connect-cms#648]
- プログラムから参照してなさげに見えるので削除を検討中
https://github.com/opensource-workshop/connect-cms/tree/master/public/bootstrap4

- Connectはnpm経由のbootstrap読んでるので影響ない筈。
https://github.com/opensource-workshop/connect-cms/blob/master/resources/views/layouts/app.blade.php#L66

- 削除を検討しているディレクトリ毎、削除してブラウザをスーパーリロード、数ページ確認したが影響はなさそう。

- しばらくこのIssue置いといて特にご意見なければ削除しようと思います。

**Comment by akagane99** [comment]
bootstrap4のjsも読み込まないと機能しないはずなんだけど、どっかでjsは読み込んでるのかなぁ。
https://github.com/opensource-workshop/connect-cms/tree/master/public/bootstrap4/js

**Comment by masaton0216** [comment]
この辺はwebpackの仕様を理解しないとチンプンカンプンかと思います。
webpackは色々とやってくれるようですが、とりあえず今は「jsとcssのコンパイラ」と思って頂いていいです。

- webpackのコンパイル定義
>コンパイル（npm run devとかnpm run prodコマンド実行）時のread/output定義を記載しているのが下記です。
https://github.com/opensource-workshop/connect-cms/blob/master/webpack.mix.js#L14-L15
要はresourcesディレクトリ配下をpublic配下に書き出しています。
それぞれapp.jsとapp.scssを参照して、これに記載されているものをコンパイルしてpublic配下に書き出してくれます。

で、それぞれの定義を読み解いていきます。
- app.jsのコンパイル定義
>app.jsでは下記２つをコンパイル時に読んでいます。
・（同階層の）bootstrap.js
・vue
https://github.com/opensource-workshop/connect-cms/blob/master/resources/assets/js/app.js#L8-L10

- app.scssのコンパイル定義
>app.scssでは下記３点をコンパイル時に読んでいます。
・（同階層の）_variables.scss
・node_modules\bootstrap\scss\bootstrap.scss
・（同階層の）_plugin-database.scss
※ちなみにアンスコ付ファイルはパーシャルファイルと呼ぶらしく、SCSSの分割ファイル定義時のお作法のようです。（これは知らんかった）
https://github.com/opensource-workshop/connect-cms/blob/master/resources/assets/sass/app.scss#L5-L12

と、ここまでの定義を読み解くと下記はどうも読んでなさそうな気配がしてきます。
https://github.com/opensource-workshop/connect-cms/tree/master/public/bootstrap4/css
但し、ファイルから直接読んでなければ、ですが。
この直接読んでないよねgrep調査をしてどこからも読まれてなければ消してOKかと考えてます。
