### ISSUE TITLE
【フォーム】投稿したフォームデータに採番された番号を持ってない

### ISSUE THREAD

**Issue by akagane99** [opensource-workshop/connect-cms#659]
例えばフォーム運用時に、投稿した相手から電話で問合せがあっても、採番番号からデータと特定できない事が考えられる。

## 仕様案

・Connect-CMSの場合は、新たに任意の採番をつけれるようになったため、forms_inputsにDBカラムの追加する。
　・採番は採番プレフィックスがつくため、数字のみとは限らない。
・ダウンロードで採番ONなら、採番を出力する。

## 参考

・NC2の場合、フォームデータID（data_id＝受付ID）が採番だった。
　CSV出力で「受付ID」として出力されていた。

#### 例：登録フォーム登録後

![image](https://user-images.githubusercontent.com/2756509/97097278-2ffc8480-16b2-11eb-9654-0d1758e7cd5f.png)

#### 例：CSV出力

受付ID | 応援メッセージ | お名前 | 都道府県 | 新規項目4 | 登録日時
-- | -- | -- | -- | -- | --
14 | 1 | 2 | 青森県 |   | 2020/10/25 11:06
13 | 2 | 3 | 北海道 | 新しい選択肢1 | 2020/10/25 10:21

**Comment by masaton0216** [comment]
対応済み
