### ISSUE TITLE
【フォーム】確認画面にて、長い項目名だと折り返されない為答えの文字に被ってしまう

### ISSUE THREAD

**Issue by osws-makino** [opensource-workshop/connect-cms#680]
## 概要
確認画面にて、長い項目名だと折り返されない為答えの文字に被ってしまう。

## スクリーンショット
![image](https://user-images.githubusercontent.com/34463938/101877389-45c9f880-3bd1-11eb-8bd4-c5f3f8c5eb92.png)

## 原因
項目名のtdに折り返しナシのCSSが定義されている為

【ソース】
```
<div class="form-group container-fluid row">
    <label class="col-sm-4 control-label text-nowrap">①事業報告「令和元年度埼玉県養護教諭育成支援事業」報告について</label>
    <div class="col-sm-8">
        <input name="forms_columns_value[12]" type="hidden" value="① 大変参考になった">① 大変参考になった
    </div>
</div>
```
【CSS】
```
.text-nowrap {
  white-space: nowrap !important;
}
```

**Comment by akagane99** [comment]
連絡ありがとう。
修正しました。

## 修正プログラム
https://github.com/opensource-workshop/connect-cms/commit/3f605625a3d0ec3184e90ee9d2c9f9672da5eae2
