### ISSUE TITLE
【ユーザ管理】システム管理者権限が一人もいなくなる場合のエラーチェック

### ISSUE THREAD

**Issue by nagasheep** [opensource-workshop/connect-cms#699]
システム管理者権限が一人もいなくなると、データベースの修正が必要になるので、チェックすること。

**Comment by akagane99** [comment]
関連
* https://github.com/opensource-workshop/connect-cms/issues/1356

**Comment by akagane99** [comment]
* https://github.com/opensource-workshop/connect-cms/pull/1682

上記で対応済みです。
