### ISSUE TITLE
【ユーザ登録】ユーザ自動登録で、設定で個人情報保護に同意を求めない場合でも登録ができない

### ISSUE THREAD

**Issue by akagane99** [opensource-workshop/connect-cms#716]
## 概要

・同意を求める設定にすると登録できる。
・ユーザー登録時の入力チェックにバグあり。今後修正する。

## 実行環境
OS: windows10
ブラウザ: 新Edge
Connect-CMS: 2021/01/26 git pull
php version: 7.3.0

**Comment by nagasheep** [comment]
すまない。永原のバグだね。
見まーす。

--
-------------------------------------------------------------
つながる未来へ Connect-CMS
https://connect-cms.jp/
-------------------------------------------------------------
株式会社オープンソース・ワークショップ
永原 篤
e-mail nagahara@opensource-workshop.jp
url http://opensource-workshop.jp
twitter http://twitter.com/nagasheep
電話 03-5534-8088
携帯 090-1699-2746
-------------------------------------------------------------

2021年1月26日(火) 7:04 Mitsuru Mutaguchi <notifications@github.com>:

**Comment by akagane99** [comment]
ユーザーの追加項目対応と同時にやるんで、そっとしておいてー

**Comment by nagasheep** [comment]
了解です。サンキュー。
configテーブルで、個人情報保護のチェックありなら、必須チェック。の処理が抜けてたのよね。
失礼。

--
-------------------------------------------------------------
つながる未来へ Connect-CMS
https://connect-cms.jp/
-------------------------------------------------------------
株式会社オープンソース・ワークショップ
永原 篤
e-mail nagahara@opensource-workshop.jp
url http://opensource-workshop.jp
twitter http://twitter.com/nagasheep
電話 03-5534-8088
携帯 090-1699-2746
-------------------------------------------------------------

2021年1月26日(火) 8:27 Mitsuru Mutaguchi <notifications@github.com>:

**Comment by akagane99** [comment]
> configテーブルで、個人情報保護のチェックありなら、必須チェック。の処理が抜けてたのよね。

はい、おっしゃる通りでした。
対応します。

**Comment by akagane99** [comment]
こちらのissueで対応済み。
https://github.com/opensource-workshop/connect-cms/issues/706#issuecomment-767990019
