### ISSUE TITLE
【管理機能－ページ管理】ページ毎に設定できるデザイン用の「クラス名」の用途がわかりづらい

### ISSUE THREAD

**Issue by masaton0216** [opensource-workshop/connect-cms#734]
## 概要
- ページ詳細のデザイン用とうたっている「クラス名」は設定しても該当ページのソース表示で表示されない。（そもそもそういった機能ではなさそう）
- スマホメニューかメニュー絡みで表示するような用途を想定しているようだが、だとすれば補足説明も含め設定できる画面、及び、位置的に機能が想定しづらい。
- 現機能を調査した上で適切な表現（位置やテキスト、項目名等）に改める
- 加えて、ページ単位に設定できるデザイン用のクラス設定項目は欲しいところ。

## スクリーンショット
![image](https://user-images.githubusercontent.com/13323806/108820168-2141c200-75ff-11eb-9cc2-5c873704c95a.png)

**Comment by akagane99** [comment]
関連issue
* https://github.com/opensource-workshop/connect-cms/issues/1106

**Comment by akagane99** [comment]
転記メモ

> スマホメニューかメニュー絡みで表示するような用途を想定しているようだ

ソースから以下のメニューのテンプレートで使っていることが判明。
breadcrumbs
dropdown
dropdown_hamburger
mouseover_dropdown
mouseover_dropdown_hamburger
mouseover_dropdown_no_root
mouseover_dropdown_no_rootlink
mouseover_dropdown_no_rootlink_for_icon
tab
tab_flat

**Comment by akagane99** [comment]
対応しました。
