### ISSUE TITLE
ラジオでON・OFF時、左側はOFFで統一する

### ISSUE THREAD

**Issue by akagane99** [opensource-workshop/connect-cms#737]
今後の見直し参考に。
表示の統一。
【サイト管理】サイト基本設定は統一されてない

![image](https://user-images.githubusercontent.com/2756509/109240371-b8369600-781a-11eb-8559-104fb9c5518b.png)

**Comment by akagane99** [comment]
データベース＞表示設定は、左側はON

![image](https://user-images.githubusercontent.com/2756509/109240684-4874db00-781b-11eb-88d7-268c306f41dd.png)

**Comment by nagasheep** [comment]
これって、どっちにするか。は、まだ決めてないんだっけ。

参考に、「キャンセル」「保存」は左をキャンセルで統一したはず。

OFF、ON の左右はどっちだろうと思ってググったら、以下の記事が納得な感じでした。
（左がOFF、右がON）
https://lglink.blog.fc2.com/blog-entry-47.html

掲示板の表示設定をカスタマイズしていて、この件にひっかっかったので、左をOFF で進めときます。

**Comment by akagane99** [comment]
さっき気づいた。まだ決まってなかったかと。
（左がOFF、右がON）納得、了解です。

**Comment by akagane99** [comment]
とりあえず wiki に追記しました。
https://github.com/opensource-workshop/connect-cms/wiki/Button%EF%BC%88%E3%83%9C%E3%82%BF%E3%83%B3%EF%BC%89#radio-button

**Comment by akagane99** [comment]
対応済み
