### ISSUE TITLE
【エラー通知】Slack通知とかメール通知とか

### ISSUE THREAD

**Issue by masaton0216** [opensource-workshop/connect-cms#744]
- システムエラーを保守業者に飛ばす設定機構が欲しい
- 契約内容の前提次第の為、機能の有効化については選択制であることが必要、サイト管理辺りか。
- 下記の辺りを弄る。Connectカスタマイズ入っているので要調査
https://github.com/opensource-workshop/connect-cms/blob/master/app/Exceptions/Handler.php#L38-L59
- 通知チャンネル毎にNotificationクラス作る（SlackNotificationとか）
https://github.com/opensource-workshop/connect-cms/tree/master/app/Notifications

**Comment by akagane99** [comment]
https://github.com/opensource-workshop/connect-cms/issues/927#issuecomment-878860164
以下転記です。

> ・今後、プラグインで500エラーでたら、なんか通知飛ばせたらいいね。
　500エラー
　ConnectCommonTrait::view_error() で下記指定された時とか。
```php
            case '500_inframe':
            case '500':
            case 'error_inframe':
            case 'template_notfound':
```
>　通知は１度発報したら、同じエラーは１時間飛ばさないとか、フラグファイル消すまで同じエラーは再発報しないとか、仕組み欲しいなぁ。
