### ISSUE TITLE
【どっかの管理機能】ページトップへ戻るボタンの表示有無選択

### ISSUE THREAD

**Issue by masaton0216** [opensource-workshop/connect-cms#765]
- 表示の有無の設定
- 文字自体の設定
- 不透明度の設定
- 画像の設定の設定

**Comment by kousei86** [comment]
**挙動**
　・ページを少しスクロールした際に、ボタンがフェードしながら登場する
　・そのボタンを押したら、1000msをかけて滑らかにページトップにスクロール移動する

は、変更不可であっても欲しいです。

**スタイル**
　・形　状［　丸　　四角　］
　・大きさ［　幅　　高さ　］
　・背景色［カラーピッカー］　･･･　オンマウス［透明度変化］
　・枠　色［カラーピッカー］
　・上記号［ ^　↑　△   TOP］
　・文字色［カラーピッカー］

あたりを選べるとよいとは思います。

挙動やスタイルについて細々と自由に設定できなくてもあまり気にしませんが、
スタイルの設定を変えている時にリアルタイムで変化を確認できると気が利いていると感じます。
