### ISSUE TITLE
【フレームorデータ】公開期間を設定できる機能の検討

### ISSUE THREAD

**Issue by osws-makino** [opensource-workshop/connect-cms#774]
フレーム、もしくはデータの方に公開期間を設定できると
期間限定で記事等を公開できたりするので便利。せめて固定記事にその機能があると運用が楽になります。

**Comment by masaton0216** [comment]
フレームに持たせた方が柔軟性が上がるのでフレームでやる

**Comment by nagasheep** [comment]
いずれは、フレームとバケツの双方に公開期間があれば良いなぁ、と思います。
フレームは画面上のフレームの公開期間
（複数のフレームで同じバケツを表示している場合、該当フレームのみの制限になる）
バケツは、データとしての公開期間
（複数のフレームで同じバケツを表示している場合、バケツの設定なので、全てのフレームの制限になる）
