### ISSUE TITLE
カテゴリ設定の画面がわかりにくい。

### ISSUE THREAD

**Issue by nagasheep** [opensource-workshop/connect-cms#783]
カテゴリ設定の画面がわかりにくいので、改善したい。
[https://connect-cms.jp/plugin/bbses/show/106/233/123#frame-233](https://connect-cms.jp/plugin/bbses/show/106/233/123#frame-233)

## 対応状況

- [x] ブログ
- [x] FAQ
- [x] 課題管理
- [x] サイト管理＞カテゴリ設定

**Comment by akagane99** [comment]
課題管理で対応してみました。
こんな感じかなぁ。

![image](https://user-images.githubusercontent.com/2756509/113690981-f622b600-9706-11eb-9a8d-ea07b006f95f.png)

## 修正プログラム（課題管理）

https://github.com/opensource-workshop/connect-cms/commit/20b9df8ee19b13508158f2549c13e9f4f6e2e327

**Comment by akagane99** [comment]
課題管理のカテゴリ設定、再度見直してみました。

![image](https://user-images.githubusercontent.com/2756509/113788411-d2e41f00-9777-11eb-9b06-1242d7b3fe5d.png)

**Comment by akagane99** [comment]
課題管理のカテゴリ設定で、統一対応する。

**Comment by akagane99** [comment]
## 残対応メモ

- [ ] サイト管理＞カテゴリ設定下部、説明メッセージ修正
- [ ] サイト管理＞カテゴリ設定のプラグインIDがバグってる。各プラグインで保存時に設定してるプラグインIDが違うと予想。
- [ ] プラグイン側カテゴリ画面の共通化対応
- [ ] 課題管理の` declareRole()`の` role_article`(モデレータ)になってるもの見直し。多分`role_arrangement`(プラグイン管理者)が正解の見通し。
- [ ] cc_role.phpにカテゴリ系の権限追加`listCategories` `saveCategories` `deleteCategories`

**Comment by akagane99** [comment]
メモ：ブログ修正後の画面
![image](https://user-images.githubusercontent.com/2756509/113981188-57bb5f80-9882-11eb-8c00-61a3d367291d.png)

**Comment by akagane99** [comment]
対応しました。
