### ISSUE TITLE
ヘッダーのスマホメニュー、メンバーシップページが表示されない

### ISSUE THREAD

**Issue by akagane99** [opensource-workshop/connect-cms#791]
## 概要
公式サイトにて確認。
報告まで。

## 実行環境

OS: iOS
ブラウザ: safari

## スクリーンショット

ヘッダーのスマホメニュー
![B16A102E-44FA-4B9D-A280-E36CE48550CE](https://user-images.githubusercontent.com/2756509/114107673-6e0dfd80-990c-11eb-9aae-bec2eb961186.png)

メニューだと表示できてる
![DD1763BD-FCE3-4937-8507-DBC6C4B95904](https://user-images.githubusercontent.com/2756509/114107720-7f570a00-990c-11eb-9942-8d1aef1732e6.png)

**Comment by osws-makino** [comment]
修正しましたー。
