### ISSUE TITLE
メニューデザイン変更時の不規則な動き

### ISSUE THREAD

**Issue by dreamer9999** [opensource-workshop/connect-cms#807]
（初めての投稿なので、おかしな書き方などがありましたら、ご指摘お願い致します）
## 概要

メニューのデザイン変更時に奇妙な動きをします
## 実行環境
github最新のサイト

## 再現手順
コトバで表現しづらいので、作成した動画をリンクします。

## 動画リンク先
動画に出てくるメニュー「あ」が正常で、メニュー「い」が奇妙な動きをしてます。
原因は不明ですが。

https://youtu.be/vHAjP6NCx_c[](https://youtu.be/vHAjP6NCx_c)

**Comment by akagane99** [comment]
動画拝見しました。

・メニュー「あ」とメニュー「い」は別メニューっぽいですね。
　メニュー「い」は後から配置したかも？

・ページ「い」のページレイアウトで、ヘッダーエリアが非表示になってるのかも。

**Comment by kousei86** [comment]
ものすごく説明しづらいのですが、
ヘッダーエリアやフッターエリアなどにおいて、
始めにプラグインを設置したページ**以外**で新たにプラグインを追加すると、
「**そのページ固有のヘッダーエリア／フッターエリアを作り直すような挙動をする**」ということです。

分かりにくいので、操作例を示してみます。
－－－－
1.  ページ［home］のヘッダーエリアに「固定記事」３つで〈ロゴ、タイトル、メニュー〉を配置したとする
2.  別のページ［about］［blog］を開くと、 ヘッダーエリアに〈ロゴ、タイトル、メニュー〉が表示されている
3.  ここで［blog］のページを開き、ヘッダーエリアに「カレンダー」を追加する
4.  すると、これまであった〈ロゴ、タイトル、メニュー〉が消え、「カレンダー」だけが表示される
5.  ページ［home］［about］に戻ると、元の〈ロゴ、タイトル、メニュー〉が表示されている
6.  再びページ［blog］に戻ると、「カレンダー」だけがヘッダーエリアに表示されている 
7.  ここでページ［blog］の「カレンダー」を削除すると、先の〈ロゴ、タイトル、メニュー〉が復活する
－－－－

操作として、
異なるページでヘッダーエリアに何かプラグインを配置してみると確認できます。

**Comment by nagasheep** [comment]
@kousei86 
こんにちは。
株式会社オープンソース・ワークショップの永原です。

操作例の通りの動きが、意図したものなのです。

上書きするような動きについては、用語的には、「オーバーライドする」と呼んでいます。
以下はwikipedia のオーバーライド
https://ja.wikipedia.org/wiki/%E3%82%AA%E3%83%BC%E3%83%90%E3%83%BC%E3%83%A9%E3%82%A4%E3%83%89#:~:text=%E3%82%AA%E3%83%96%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88%E6%8C%87%E5%90%91%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%9F%E3%83%B3%E3%82%B0%E3%81%AB%E3%81%8A%E3%81%84%E3%81%A6%E3%82%AA%E3%83%BC%E3%83%90%E3%83%BC%E3%83%A9%E3%82%A4%E3%83%89,%E3%82%92%E7%B6%99%E6%89%BF%E3%81%97%E3%81%9F%E3%81%A8%E3%81%99%E3%82%8B%E3%80%82

また、トップページに設定したヘッダーが、トップページ以下のページにも反映される動きを「継承する」と呼んでいます。
どちらもプログラミングの用語です。

この辺、図にでもしないとわからないですよね。
図を描く時間の捻出がどこでできるかわからないのですが。。。

以上、まずはここまで、説明させていただきます。

**Comment by kousei86** [comment]
ややこしい説明にも関わらず、
正確に理解していただき、ありがとうございます。

こういうことですかね。
－－－－－－－－－－－－－－－－－－－－－－－－

・ヘッダーエリア／フッターエリア／左・右カラムエリアの各エリアに配置されたプラグインは、
　そのレイアウトのまま、ページ間で共有される【これを〈継承〉という】　

・継承には「最初にプラグインを配置したエリア」のレイアウトが使われる。

・継承中のエリアで新しいプラグインを追加すると、継承中のプラグインを覆い隠すように
　そのページ固有のレイアウトが新たに適用される【これを〈オーバーライド〉という】

・オーバーライドしているエリアに配置されたプラグインを全て削除すると、
　オーバーライドは解除され、継承中プラグインが再び表示される

－－－－－－－－－－－－－－－－－－－－－－－－（くどいわぁ）－－－


そうすると、Webページ製作者としては、
今のところ
・ 継承に使える配置は各エリア１種類であり、あとは個別に配置する 
・（ページをグループ化し、その）「グループごとに継承させる」ということはできない
・「エリアごとの複数の配置を登録しておき、ページごとに選べる」という機能はない。
あたりを知っておくとよいですね。

**Comment by nagasheep** [comment]
@kousei86 様

永原です。
ごめんなさい、返信いただいたにもかかわらず、なかなか、返答できていません。
いつも時間切れが。。。

正確に返答しようと思うのですが、申し訳ない。
なんかバタバタしっぱなしでして、ゆっくりお待ちいただければ助かります。

以上、まずは言い訳だけで失礼いたします。

**Comment by kousei86** [comment]
@nagasheep 様
　
「サイト制作中なので、早く反応が欲しい」というのでは全くなく、
単に「いろんな機能を試しているうちに疑問を見つけた」だけですので、
気にせず置いていただいて構いませんよ。
　
ご心労をおかけし、申し訳ございません。
