### ISSUE TITLE
ページ権限設定ができないように思えます。

### ISSUE THREAD

**Issue by dreamer9999** [opensource-workshop/connect-cms#809]
ページ権限設定画面に、マニュアルにある「メンバーシップ一般」の選択機能が表示されないように思います。

①マニュアルにあるページ権限設定画像

![ページ権限1](https://user-images.githubusercontent.com/3895089/114875935-c5462d80-9e38-11eb-97e3-d5c364d34c4b.png)

②現在のページ権限設定画像

![ページ権限2](https://user-images.githubusercontent.com/3895089/114876018-dc851b00-9e38-11eb-8c1b-2fc8109a9c96.png)

**Comment by akagane99** [comment]
・あれ？
　アップデートすると下記メッセージが表示されるので、アップデート前かなと思います。

![image](https://user-images.githubusercontent.com/2756509/115129676-0c901200-a023-11eb-93be-bf6c7c648a09.png)

・公式サイトのマニュアルも画像が古い場合があったりします。その時はごめんね。

**Comment by dreamer9999** [comment]
そうですか、、
今、新規にconnect-cmsをインストールしたのですが、やはり、初めに投稿したものと同じ画面が表示されます。
既存の「わくわく農園」サイトもアップデートしたけれど、やはり、初めに投稿したものと同じ画面が表示されます。
なんでしょうかね、、、

**Comment by akagane99** [comment]
ありゃ、なんでしょうね？
該当画面のプログラムを確認してみましたが、特に条件分岐とかしてないので、最新であれば特別な操作不用で表示されるはずなんだけどなぁ。
ううーん。ちょっとわからずです。
https://github.com/opensource-workshop/connect-cms/blob/master/resources/views/plugins/manage/page/role.blade.php#L54

**Comment by dreamer9999** [comment]
私は、さくらのインストールマニュアルに沿って実行しましたつもりですが、私だけの現象なんでしょうかね、、
他の方は如何なんでしょうかね、、、
たとえば、akagane99さんが、今、新規にインストールしたとしたら正常なページ権限設定画面になるものでしょうか、、、
（お忙しいakagane99さんにおたずねするのも、何なんですが、、、）

**Comment by dreamer9999** [comment]
私のおかしな画面のソースコードは下記の様になってます。
（よくわかっていませんが、関係ありそうな場所を複写してみました）

<div class="card">
    <div class="card-header p-0">
        
        <div class="frame-setting-menu">
    <nav class="navbar navbar-expand-md navbar-light bg-light py-1">
        <span class="d-md-none">処理選択</span>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsingNavbarLg">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse" id="collapsingNavbarLg">
            <ul class="navbar-nav">
                            <li class="nav-item"><a href="https://wakuwaku.cyou/manage/page" class="nav-link">ページ一覧</a></li>
            
                            <li class="nav-item"><a href="https://wakuwaku.cyou/manage/page/edit" class="nav-link">ページ登録</a></li>
            
            
                            <li class="nav-item"><a href="https://wakuwaku.cyou/manage/page/import" class="nav-link">CSVインポート</a></li>
            
                            <li class="nav-item"><span class="nav-link"><span class="active">ページ権限設定</span></span></li>
            
            
            
            </ul>
        </div>
    </nav>
</div>
    </div>
    <div class="card-body">

        <div class="alert alert-info" style="margin-top: 10px;">
            ページ名：メンバー農園予定表
        </div>

        <div class="accordion" id="accordion" role="tablist" aria-multiselectable="true">
                    </div>
        <div class="text-center row mt-3">
            <div class="col-12">
                <button type="button" class="btn btn-secondary mr-2" onclick="location.href='https://wakuwaku.cyou/manage/page/edit/33'">
                    <i class="fas fa-times"></i> キャンセル
                </button>
            </div>
        </div>
    </div>
</div>

        </main>

    </div>
</div>

**Comment by akagane99** [comment]
ちょっとこのissueの本題からは離れてるけど、さくらのインストールマニュアルはこれかなぁ。
https://github.com/opensource-workshop/connect-cms/wiki/Install-sakura

ちょっと今は新規インストールの時間はとれないのです。ごめんね。

あとはViewキャッシュが悪さしてるのかなぁ。（でも新規インストールでは出ないだろうしなぁ。）
下記でLaravelのviewのキャッシュをクリアできるので、お試しあれ。

```
php artisan view:clear
```

原因がキャッシュであれ、別であれ、ページのグループ機能は作成途中で[このコメント](https://github.com/opensource-workshop/connect-cms/issues/809#issuecomment-821904151)の画像の状態でしか動作しないと思います。

**Comment by dreamer9999** [comment]
> ちょっとこのissueの本題からは離れてるけど、さくらのインストールマニュアルはこれかなぁ。
> https://github.com/opensource-workshop/connect-cms/wiki/Install-sakura

はい、それでインストールしてます。

> 下記でLaravelのviewのキャッシュをクリアできるので、お試しあれ。
> php artisan view:clear

実行しましたが、変わりませんでした。

> ちょっと今は新規インストールの時間はとれないのです。ごめんね。

私も、お手間を取らせてしまうことに、非常に恐縮しています。
（結果が、こちらの凡ミスだった場合、自責の念にかられて、夜眠れません、、（？））
akagane99さんの開発業務を最優先してください。

> 原因がキャッシュであれ、別であれ、ページのグループ機能は作成途中でこのコメントの画像の状態でしか動作しないと思います。

私の異常画面のソースコードに、
https://github.com/opensource-workshop/connect-cms/blob/master/resources/views/plugins/manage/page/role.blade.php#L54
の正常なソースコードが現れない、
ことをヒントに、何か分かるもんでしょうかね、、、、

いづれにしても、現在の私のサイト運用には影響しないことですので
（隠しページにし、パスワードかけ、関係者には直アドレス連絡）、
また、機会がありましたら、、ということで、宜しいかと、、、おもっています、、

**Comment by dreamer9999** [comment]
解決しました。
公星様からのアドバイスがあり、

「「ページ権限設定ができない」件について、牟田口様の画像と見比べると、
「グループ管理」でグループを作り、そのグループ内で権限を付与する機能のように思えます。」

に沿って実行したら、正常画面が現れました。

akagane99様につきましても、お時間をとらせてしまい、ありがとうございました。
