### ISSUE TITLE
ヘッダーの文字色を変更可能にしていただきたいです。

### ISSUE THREAD

**Issue by dreamer9999** [opensource-workshop/connect-cms#811]
ヘッダーの文字色を変更できるようにしていただきたいです。

ページ全体を真っ白にして高級感？を出すためヘッダーの背景色を白色にしたいのですが、ヘッダーの文字（ログイン、サイト名など）の色も白色のため、ヘッダーの文字の判読ができなくなります。
その際、ヘッダのサイト名文字色を白色にして隠し、ログインの文字を薄いグレーに変更できるとしたら、上品？な画面になる気がします。

また、白色の場合に限らず、ヘッダーの背景色に合わせてサイト名・ログイン文字の文字色を別々に変更できると、サイト画面の見栄えがいっそう素敵になる気がします。

以上、今後の検討のひとつとして含んでいただければ、嬉しく思います。

※バグではないのですが、「bug」のラベルが自動的に付いてしまいます。直し方がわかりません、、、
※別件、スマホ(andoroid）で、このissuesをみると、文章がおかしな表現に変わってしまいますが、直し方がわかりません、、、

**Comment by akagane99** [comment]
> ※バグではないのですが、「bug」のラベルが自動的に付いてしまいます。直し方がわかりません、、、

どうもラベルは権限ないと付け直せないようなので、こちらで付け直しました。

また、新たにアイデアissueとフリー入力issueをできるよう設定しました。
今後は使い分けて頂ければ、それぞれで自動にラベル付きます。（フリー入力はラベル付かないようになってます）
https://github.com/opensource-workshop/connect-cms/issues/new/choose

> ※別件、スマホ(andoroid）で、このissuesをみると、文章がおかしな表現に変わってしまいますが、直し方がわかりません、、、

こちらは私の方ではちょっとわからず。ごめん。

**Comment by akagane99** [comment]
slackより転記

https://connect-cms.slack.com/archives/C016EL48G83/p1620621683005500
> 透過できるんですね、
別件になってしまいますが、`rgba(255,0,0,0)`　だと、ヘッダ色が白色になり、ヘッダにあるサイト名文字色、ログイン文字色も白色のため、サイト名文字、ログイン名が見えなくなります。
サイト文字色、ログイン文字色も任意に変更できれば、と思う次第です。

このissueの件かな。

ヘッダー（bootstrap4 navbar）の文字は、リンクも含まれるので、背景色のように色してすれば解決できないんす。
どうすればいいのかは、ちょっとまだわかんないので、どなたかアイデアあったら教えてください。

## ヘッダー（bootstrap4 navbar）
https://getbootstrap.jp/docs/4.2/components/navbar/#color-schemes

**Comment by kousei86** [comment]
「サイト管理」画面に、「センターエリア任意クラス」「フッターエリア任意クラス」と同様に【 **ヘッダーエリア任意クラス** 】を作っていただければ、独自CSSを使って細かな変更が容易になると思います。
　
（現状１）
　- メニューを設置すると navbarクラスが複数できます。
　- ヘッダーには、より上位の任意クラスを設定できないため、他のnavbarと区別できません。
　- そのため、nabvarクラスのCSSを作ると他のメニューに対しても一斉に反映されてしまいます。
　- 面倒ですが、ヘッダー以外の全ての「メニュー」プラグインに毎回、任意クラスを設定し、そちら側で「優先順位の高い」区別化を図れば可能だと思います。
　
（現状２）
　- 左上のサイト名を示す「nav-brand」クラスだけは固有のようなようです。
　- そのため、CSSで .nav-brand{color: 色;} を指定すれば、サイト名だけはフォントや色・大きさを変えられそうです。

**Comment by akagane99** [comment]
@dreamer9999 @kousei86 
情報ありがとうございます！参考になります。

text-danger (text-〇〇〇) の指定だと、リンクの上にマウスが乗った時（オンマウス）の色が飛んじゃうので別の方法をとりたいと思います。

dreamer9999さんが参考にしたブログの別記事に、文字色の変更記事がありました。
https://qumeru.com/magazine/288

この記事を参考に、下記２種類から選べるように対応しようかなと思います。
`navbar-light`を追加すれば、白めの背景色でも表示できると思います。

・`navbar-dark` （明るめの文字：Connect-CMSはこれ固定）
・`navbar-light`  (暗めの文字：これを追加)

-------

また、より簡単にCSSを使ってデザインをいじりたい人のために、画面上部のヘッダーメニューには、空のクラス（例えば `.top-header`）を追加したいなと思ってます。
ちょっと社内でも意見聞いてみるので、お待ちください。
（kousei86 さんの調べてくれた通り、今のところ「nav-brand」は固有だけど、今後他で使ったら影響でそうだしなぁ。うーんといった感じです。）

**Comment by akagane99** [comment]
まずはヘッダー文字色を選択可能にしました。

## 修正プログラム

https://github.com/opensource-workshop/connect-cms/commit/2e62aeea3b29d3b8621598dda9c502941b47a372

**Comment by kousei86** [comment]
この連絡を受けてからアップデートをしたところ、500エラーでサイト全体が表示できなくなりました。
さくらのレンタルサーバーに「test02」として新しくインストールしてみたところ、
手順「サイトにアクセスする」（ https://USERNAME.sakura.ne.jp/test01/   ）〈→ test02〉 でブラウザに500エラーの表示が出ます。
　
なお、同じサーバー上にあるWordPress、およびhtml/PHPのサイトは正常に動いています。

**Comment by akagane99** [comment]
失礼、バグです。
修正しますね。
(なんで俺のは動いちゃったんだ💦)

**Comment by akagane99** [comment]
@kousei86 
もうちょっと詳細知りたいです。
エラーログに何か出てないか教えてもらえると助かります。
storage\logs\laravel-2021-05-14.log

**Comment by akagane99** [comment]
修正してみました。

**Comment by kousei86** [comment]
500エラーが出ず、正しく表示されることを確認しました。

エラーログについては、１回のエラーで約3000行にわたるログが出力されました。
何を置換して提出するかを見ている間に、修正が終わったようです。

**Comment by akagane99** [comment]
いろいろ確認ありがとうです＆お手数かけちゃってごめん。
サイト全体が動かなくなるバグだったので、大変助かりました。<(_ _)>（冷や汗出ました）

また一般画面にはヘッダー文字色反映されたのですが、管理画面で反映されてなかったので再度修正しました。
お知らせまで。

## 修正プログラム

https://github.com/opensource-workshop/connect-cms/commit/1fcaa889a92b4cc788572c6bc53ad230a9069343

**Comment by kousei86** [comment]
管理画面のヘッダーについても、背景色が選択できるようになったことを確認しました。
　
－－－
「サイト管理」＞「サイト基本設定」の中身がだいぶ盛りだくさんになってきましたね。

**Comment by dreamer9999** [comment]
ヘッダ文字色、いい感じです、ありがとうございます。

・気が付いたこと、
①
サイト管理、ページ管理で、共に、サイト背景色・ヘッダ背景色を白色(#ffffff)にしたとき、ヘッダ背景色が、微妙なんですが、灰色っぽい感じに見えます。
私のパソコンディスプレイとかの問題なんでしょうかネ、（このままでも、あまり、違和感はないですが、、、）

②
サイト管理で、サイト名なし（空白）にすると、「Laravel」のサイト名が表示されるみたいです。

③
Twemojiが、かわいいです。（蛇足ながら、、）


'--------------------------------
**【サイト管理画面】**
'--------------------------------
![ヘッダ文字色設定画面](https://user-images.githubusercontent.com/3895089/118383435-92aa7300-b638-11eb-84dd-20750fa44f38.png)

'---------------------------------
**【パソコンディスプレイ画面】**
'----------------------------------
![ヘッダー文字色チェック](https://user-images.githubusercontent.com/3895089/118383443-a48c1600-b638-11eb-8c3f-0c5d501425e0.png)

**Comment by akagane99** [comment]
> ヘッダ文字色、いい感じです、ありがとうございます。

おお、良かった＾＾

> ①
サイト管理で、サイト名なし（空白）にすると、「Laravel」のサイト名が表示されるみたいです。

なるほど。
サイト名が空だと、何も設定されてない時の初期値が表示されるようになってて、 `.env`の`APP_NAME` の値が表示されるみたいです。

> ②
Twemojiが、かわいいです。（蛇足ながら、、）

かわいい。


> また、より簡単にCSSを使ってデザインをいじりたい人のために、画面上部のヘッダーメニューには、空のクラス（例えば .top-header）を追加したいなと思ってます。

以前の内容訂正です。
@kousei86 さんのおっしゃる通りの内容の、任意クラスを追加する方法で、週明けに社内の意見聞いてみます。
（サイト管理いじってたら、何か他の任意クラスと同じにしていいか、と考えなおしました。）

**Comment by dreamer9999** [comment]
> サイト名が空だと、何も設定されてない時の初期値が表示されるようになってて、 .envのAPP_NAME の値が表示されるみたいです。

そうなんですね、
私の場合、サイトのヘッダに固定記事プラグインを追加し、その中にサイト名を含んだ画像を設定しているので、基本ヘッダにはサイト名を表示したくありません。
（個人的な美的センス（？）上、同じ名前が近くにそんざいするのは、美的に許せない？）

インストールマニュアルの「.env変更」に、APP_NAME＝    //(空白）を追記するのも、いいのかな、と思いました。

**Comment by kousei86** [comment]
1.  どのページにも登場する領域に「固定記事」を置く。（→ ページの「レイアウト」でいうヘッダーかフッターが適当）
2.  その固定記事の「フレームタイトル」を〈空白〉、「フレームデザイン」を None にする。
3.［編集］ボタン → 「ソースコード」で次の<style>～</style>のコードを入力し、［OK］ボタンを押す。
＊＊＊＊＊＊＊＊＊＊＊
<style>
.navbar-brand{
    text-indent: 100%;
    white-space: nowrap;
    overflow: hidden;
}
</style>
＊＊＊＊＊＊＊＊＊＊＊
　
![サイトタイトルを不可視](https://user-images.githubusercontent.com/82799412/118400271-d8e4ee00-b69b-11eb-9fda-f90810c627ee.png)

－－－

この「固定記事」について、画面上で何も表示されませんが、
上の入力で **画面左上のサイトタイトルが表示されなくなる**ようなCSSを埋め込みました。
（ → 仕組みの説明が欲しい場合は[このサイト](https://ss-complex.com/css-cleartext/)を参照して下さい）　
　
－－－
まぁ、「やってできないことはない」という方法の提示です。
普通はサイト内に直に書かずに（＝上の方法）、CSSファイルの方に記述する（テーマ/CSS編集）のが普通ですが。

**Comment by akagane99** [comment]
> 私の場合、サイトのヘッダに固定記事プラグインを追加し、その中にサイト名を含んだ画像を設定しているので、基本ヘッダにしつこく、ダブルでサイト名を表示したくありません。
（個人的な美的センス（？）上、同じ名前が近くにそんざいするのは、美的に許せない？）

まぁそうですよね。
現状ではできないので、今後下記issueが実現して、ヘッダーバーに画像アップできるようになればなぁ、と思います。
https://github.com/opensource-workshop/connect-cms-ideas/issues/13

> インストールマニュアルの「.env変更」に、APP_NAME＝ //(空白）を追記指示するのも、いいのかな、と思いました。
（初期値の　APP_NAME＝Laravel　をサイト名にしたい方は、あまり、いないんじゃないかな、、、）

APP_NAMEやサイト名を空にするは、各自判断かなぁと。
ページのtitleタグでサイト名使われてるので、サイト名空だとGoogleとか検索エンジンからの表示がどうなっちゃうかな？と思いました。

簡易的には「サイト名」に全角スペース１個だけで消せたりします。
本格的には kousei86 さんのやり方でいけますね。 https://github.com/opensource-workshop/connect-cms/issues/811#issuecomment-841825229

> ※プラグイン追加の「ヘッダ」とサイト名表示の「基本ヘッダ」って、名前がにてるので、まぎらわしいですね、
サイト名表示の「基本ヘッダ」は「ヘッダバー」とかに呼称変更したほうが、いいんでしょうかね、、、

ヘッダーバー、想像がついていいですね。
今後ヘッダーバーに修正しようと思います。

----

ヘッダーバー任意クラスを追加する方法、対応しました。
ご連絡まで。


## 画面
### サイト管理＞サイト基本設定

![image](https://user-images.githubusercontent.com/2756509/118429184-108b7e80-b70c-11eb-835f-8e53b373090c.png)

## 修正プログラム

https://github.com/opensource-workshop/connect-cms/pull/848/files

**Comment by akagane99** [comment]
基本ヘッダーからヘッダーバーに名称修正しました。
これでこのissueで対応する事は完了かなと思います。

しばらくしたらissueクローズしようと思ってます。

## 画面
### サイト管理＞サイト基本設定
![image](https://user-images.githubusercontent.com/2756509/118438470-66b5ed00-b71f-11eb-9319-1c883e37ca5e.png)

## 修正プログラム

https://github.com/opensource-workshop/connect-cms/commit/76405bfc4a4242e31b42c83d08ad6dc7dc665010

**Comment by akagane99** [comment]
クローズしますね。
