### ISSUE TITLE
固定記事の書式機能が一定でない

### ISSUE THREAD

**Issue by dreamer9999** [opensource-workshop/connect-cms#823]
固定記事の書式機能が一定でないようです。
同一のサイトなのに、ページにより、固定記事の書式機能が違っています。
（アップデートしても、同じ現象で、変わりません）

＜homeページ＞

![書式2](https://user-images.githubusercontent.com/3895089/115484007-e8376e00-a28c-11eb-9961-98baf1a6ab80.png)

＜わくわく農園日記ページ＞

![書式](https://user-images.githubusercontent.com/3895089/115484032-f38a9980-a28c-11eb-9b69-0508445c6ed3.png)

**Comment by akagane99** [comment]
これと同じ現象かと。
今後見直したいと思います。
https://github.com/opensource-workshop/connect-cms/issues/701

**Comment by akagane99** [comment]
修正しました。

## 修正プログラム

https://github.com/opensource-workshop/connect-cms/pull/835/files
