### ISSUE TITLE
【掲示板】メール設定で投稿通知の変更をOFFにしても変更確定時にメールが飛ぶ

### ISSUE THREAD

**Issue by akagane99** [opensource-workshop/connect-cms#829]
## 概要

件名通り

## 実行環境
OS: windows10
ブラウザ: 新Edge
Connect-CMS: 2021/04/24 git pull
php version: 7.3.0

## 調査

* [UserPluginBase::sendPostNotice()](https://github.com/opensource-workshop/connect-cms/blob/master/app/Plugins/User/UserPluginBase.php#L835-L841) でDBカラムに`first_committed_at`があるかどうかで、更新しているかチェック。
* 掲示板の`bbs_posts`テーブルには、`first_committed_at`カラムがなかった。
    * そのため変更なのに、`serPluginBase::sendPostNotice()`では常に // 対象（登録）`$notice_methods[] = "notice_create";` で判定されてました。
このため、メール設定の「登録」が使われ、「変更」設定が使われてませんでした。
* `first_committed_at`でソース全体を検索。[UserableNohistory](https://github.com/opensource-workshop/connect-cms/blob/master/app/UserableNohistory.php#L64-L66) でセットされてた。
  * 【不明点】今のところUserableNohistoryのみ対応。Userableは対応してないだけ？
* `bbs_posts`テーブルのモデル[`BbsPost`は、Userableを使ってた。](https://github.com/opensource-workshop/connect-cms/blob/master/app/Models/User/Bbses/BbsPost.php#L27) →単なる間違い？
  * 【不明点】Userable（履歴保持）を使ってるけど、掲示板の記事の履歴は保持されなかった。履歴保持はしなくていいと思うので掲示板はUserableNohistory（履歴保持しない）かと思った。

## スクリーンショット

※ 送信先メールアドレスは設定していますが、スクリーンショットでは消しました。
![image](https://user-images.githubusercontent.com/2756509/115959246-3dea6f80-a546-11eb-866b-27fd073c0868.png)

**Comment by nagasheep** [comment]
メールを送る処理の方法を変更しようかと思っています。
【タイミング】
いまは記事保存時に、プラグインからスーパークラスの共通メソッドを呼ぶ。
これをモデルのイベントハンドラに持っていこうかなと。
【判定】
いまは、確定になった時点でメール飛ばしているんだけど、一時保存＞確定を繰り返すと、登録とみなされるバグが発現しています。
これは、モデルのイベントハンドラに持っていけば良いかなと思っています。
そのためには、掲示板のモデル保存をsave()ではなく、create()やupdate()に修正は必要かなと思っています。

**Comment by akagane99** [comment]
https://github.com/opensource-workshop/connect-cms/issues/829#issuecomment-826224282
> 【タイミング】
いまは記事保存時に、プラグインからスーパークラスの共通メソッドを呼ぶ。
これをモデルのイベントハンドラに持っていこうかなと。

確認したところ、今後見直し予定。

> 【判定】
いまは、確定になった時点でメール飛ばしているんだけど、一時保存＞確定を繰り返すと、登録とみなされるバグが発現しています。

掲示板に`first_committed_at`抜けてるのを気づいてなかったため、でした。
掲示板に`first_committed_at`カラムを追加したら、一時保存＞確定を繰り返しても問題なしでした。

-----

> ・bbs_postsテーブルのモデルBbsPostは、Userableを使ってた。 →単なる間違い？

単なる間違いだったので、修正しました。

> ・first_committed_atでソース全体を検索。UserableNohistory でセットされてた。
　・【不明点】今のところUserableNohistoryのみ対応。Userableは対応してないだけ？

聞きそびれた。今回の不具合箇所ではないため、そっとしておく。

**Comment by akagane99** [comment]
修正しました。

## 修正プログラム

https://github.com/opensource-workshop/connect-cms/pull/830/files

**Comment by akagane99** [comment]
## 追加テスト
・投稿通知の変更をOFF
　・編集時に一時保存して、その後変更確定しても、メールが飛ばない事を確認しました。
