### ISSUE TITLE
データベースプラグインの絞り込み制御でのエラー

### ISSUE THREAD

**Issue by dreamer9999** [opensource-workshop/connect-cms#834]
＜エラーが出ているプラグイン＞

データベースプラグインでのエラー画面

![ＤＢ検索エラー99](https://user-images.githubusercontent.com/3895089/116772966-82699400-aa8d-11eb-9e9e-cce3818d3363.png)

※対象サイト
https://wakuwaku.cyou/yasaikeikaku

＜エラー出るまでの操作＞

下記画面の下にある「絞り込み表示」で「制御する」にチェックを入れると
エラーが出ました。
他のテストサイトでも、同じ現象でした。
再起動、履歴の削除、などしても、エラー表示が消えなくて、サイトが使えなくなりました。

![ＤＢ絞込2](https://user-images.githubusercontent.com/3895089/116772994-b2189c00-aa8d-11eb-80f5-cdf044c5d514.png)

デバッグモードON  でのエラー表示

![DB絞込デバッグ2](https://user-images.githubusercontent.com/3895089/116773070-20f5f500-aa8e-11eb-80cb-4d2f90eca068.png)

**Comment by akagane99** [comment]
バグっぽいですね💦
絞り込み項目が1個もないと、このエラーになるのかも。

この状態でも「絞り込み表示」で「制御する」のチェック外せたりしますかね？
出来るのであればエラー回避できるかもです。

**Comment by dreamer9999** [comment]
この状態では、500エラー画面が出たままなので、設定画面を開けず、「絞り込み表示」で「制御する」のチェック外せないです。
（私は、昨日のバックアップデータをリストアして、この状態から抜け出しました）

**Comment by akagane99** [comment]
あちゃー、了解です。
早めに調査対応します。

**Comment by akagane99** [comment]
調査しました。

## 原因

データベースに絞り込み項目「単一・複数・リスト」がない状態で、
データベース（右上）歯車＞表示設定
　絞り込み表示・絞り込み制御：● 制御する

にするとシステムエラーになります。

![image](https://user-images.githubusercontent.com/2756509/116796884-0158de00-ab1b-11eb-808b-9f585499f7b0.png)

## 暫定対応

強い権限でログインし、

データベース（右上）歯車＞表示設定
　絞り込み表示・絞り込み制御：● 制御しない

に変更すると、エラー回避できました。

**Comment by akagane99** [comment]
修正しました。
Connect-CMSをgithub最新にすると、エラーでなくなりますので、最新の適用をお願いします。

## 修正プログラム

https://github.com/opensource-workshop/connect-cms/commit/072e63369b951777bb60d36fbd5e79f1e977d65c

**Comment by dreamer9999** [comment]
akagane99様

いつもありがとうございます。

**Comment by akagane99** [comment]
dreamerさん

いえいえ、それではissueクローズします。
