### ISSUE TITLE
ページ管理、ページ権限設定で権限あり・なしのボタン表示色見直し

### ISSUE THREAD

**Issue by akagane99** [opensource-workshop/connect-cms#849]
現在は権限ありを`btn-primary`で指定してます。
`btn-primary`は登録・決定の色だから、できれば別の色にしたいなぁ。

## 現在

権限なし：btn-success
権限あり：btn-primary

![image](https://user-images.githubusercontent.com/2756509/118743921-4bb5bb00-b88e-11eb-9432-27f28708ea26.png)

### タグ
```html
                        @if ($page_item->page_roles->isEmpty())
                            <a href="{{url('/manage/page/role')}}/{{$page_item->id}}" class="btn btn-success btn-sm">
                                <i class="fas fa-users" title="ページ権限設定"></i> <span class="badge badge-light">権限なし</span>
                            </a>
                        @else
                            <a href="{{url('/manage/page/role')}}/{{$page_item->id}}" class="btn btn-primary btn-sm">
                                <i class="fas fa-users" title="ページ権限設定"></i> <span class="badge badge-light">権限あり</span>
                            </a>
                        @endif
```

[/resources/views/plugins/manage/page/page.blade.php](https://github.com/opensource-workshop/connect-cms/blob/master/resources/views/plugins/manage/page/page.blade.php)

## 案1

権限なし：btn-outline-success
権限あり：btn-success

![image](https://user-images.githubusercontent.com/2756509/118744962-3e013500-b890-11eb-89f1-d6accd2e03f2.png)

## 案2

権限なし：btn-success
権限あり：btn-outline-success

![image](https://user-images.githubusercontent.com/2756509/118744834-009ca780-b890-11eb-9422-ee9e244b0e9b.png)

## 案3

権限なし：btn-success
権限あり：btn-info

btn-infoは補色的に使ってるから、これもありかなぁと。

![image](https://user-images.githubusercontent.com/2756509/118744596-9421a880-b88f-11eb-9cb6-8f65419fa285.png)

## 案4

権限なし：btn-success
権限あり：btn-success + active

activeにすると色が暗くなって、ボタン押せ無さそうなイメージで微妙？（実際は押せる）

![image](https://user-images.githubusercontent.com/2756509/118744491-6472a080-b88f-11eb-9453-3d2c4e0778e6.png)

## 参考URL

[wikiのButton（ボタン）#ボタン表示例](https://github.com/opensource-workshop/connect-cms/wiki/Button%EF%BC%88%E3%83%9C%E3%82%BF%E3%83%B3%EF%BC%89#%E3%83%9C%E3%82%BF%E3%83%B3%E8%A1%A8%E7%A4%BA%E4%BE%8B)
[Buttons - Bootstrap 4.1 日本語リファレンス](https://getbootstrap.jp/docs/4.1/components/buttons/)

**Comment by gakigaki** [comment]
個人的は案１に一票です。
色の反転によってオン・オフがわかりやすいUIだと思います。

**Comment by akagane99** [comment]
thank you！
社内でも聞いてみて、案１いいねだったので、案１でいきます。

**Comment by akagane99** [comment]
対応しました。

## 修正プログラム

https://github.com/opensource-workshop/connect-cms/commit/f2797631c9e7fc014e5d3956b6c452adb8fa45c8
