### ISSUE TITLE
【フォーム】項目設定画面がボタンだらけなのでUI検討

### ISSUE THREAD

**Issue by masaton0216** [opensource-workshop/connect-cms#867]
- 行毎に配置されている更新ボタンは画面下部のキャンセルボタン右側に配置し、一括更新仕様にする
- 他あれば、随時検討
- 参考意見：詳細画面ボタンのアイコンが、固定記事等の「編集」の横にあるアイコンと同じだとコピーボタンとの判別がしやすいかと思いました。

**Comment by akagane99** [comment]
> 行毎に配置されている更新ボタンは画面下部のキャンセルボタン右側に配置し、一括更新仕様にする

カテゴリ設定で一括更新やってるよ。参考まで。
