### ISSUE TITLE
スマホでは、「メニューから直接開く外部サイト」機能がはたらかない

### ISSUE THREAD

**Issue by dreamer9999** [opensource-workshop/connect-cms#873]
スマホのハンバーガーメニューでは、「メニューから直接開く外部サイト」機能がはたらかないです。（ＰＣはＯＫ）

・ページ管理⇒ページ変更⇒外部サイトURL

![外部へのリンク](https://user-images.githubusercontent.com/3895089/120049734-d8facb80-c055-11eb-81dc-05bb46c9abf7.png)

**Comment by kousei86** [comment]
昨日 検証した残りから見つけましたが、
「マウスオーバードロップダウン**（ルートなし）**」も同様に機能しませんね。
　
「～（ルートのリンクなし）」の方は正しく外部にリンクするようです。

**Comment by akagane99** [comment]
ご確認ありがとうございました。
スマホメニュー及び、マウスオーバードロップダウン（ルートなし）の外部リンク開かないバグを修正しました。

## 修正プログラム

https://github.com/opensource-workshop/connect-cms/commit/6c2593e936c6a1c0c3e4293867741f036a6ffff1
https://github.com/opensource-workshop/connect-cms/commit/b21f4399fe2cfef13466e38ac7df9fa0f90286c4

**Comment by akagane99** [comment]
> ・スマートフォンでメニューの中身が表示されない。

ドロップダウン系テンプレート・タブテンプレートは意図してスマートフォンでは表示しないようになってると思います。
ヘッダーエリアに同テンプレートを使って、PC時は見えるけど、スマホ時はヘッダーバーのメニューを使う想定なんです。

とりあえず簡単ではありますが、マニュアルに記載しておきました。
https://connect-cms.jp/manual/user/menu#frame-35

以上でクローズさせてもらいます。
