### ISSUE TITLE
新着情報設定でエラーがでます

### ISSUE THREAD

**Issue by dreamer9999** [opensource-workshop/connect-cms#874]
新着情報設定でエラーがでます。
デバッグモードONにしたエラー内容は下記です。
特におかしな設定はしてないのですが、、
エラーが長いので、必要でしたら、別途テキストで全文貼り付けますが、、、

![新着情報エラー](https://user-images.githubusercontent.com/3895089/120098562-90383500-c171-11eb-91a2-cd7f75678701.png)

**Comment by akagane99** [comment]
BbsesPlugin.php（掲示板）の622行目でエラーが出てますね。
バグではなく何か BbsesPlugin.php が変更されてエラーでてるように見えます。

私の開発環境では、掲示板でエラー出ませんでした。

**Comment by kousei86** [comment]
調べたけど再現できませんでした。

－－－【不思議に思うこと】－－－
・BBSesPlugin.phpの622行目にエラーが出ていることが見えるが、「掲示板」プラグインは使用している（いた）か？
・提示されたエラー画面がsymfonyの紫色のものでなく、赤い画面である（Laravel？）
・全体が500エラーになるのではなく、新着プラグイン内だけで500エラーになっている
![500error](https://user-images.githubusercontent.com/82799412/120139315-283a2b00-c213-11eb-8673-11d4eeb44ad5.png)
　
・登録されたデータが25000件近くあるが、登録の仕方に関係があるか？
　（CSVかZIPを使ったと思われるが、その際の設定や方法が想定外である可能性）
・新着情報に関わる処理数が多くてサーバーの許容量を超えた
　（検証 →「新着情報」プラグインをヘッダーに置いたら、メイン以下がレンダリングされなくなるかもしれない）
　
・手動でC-CMSのソースコードを書き換えた 【 私のところでも正常に動くので、なんとなくこれを疑う 】
　（あるいは、「データベース」プラグインへの登録内容がC-CMSのソースコードに影響を与えた。例えば ")" に反応したとか）
－－－　－－－　－－－

結局よく分かりませんでしたが、
とりあえず「コマンドラインからキャッシュをクリアしてみる」というのは如何でしょうか？

私がアップデートの度にやっているキャッシュのクリアは以下のとおりです（ 四連式の一行 ）。
php artisan cache:clear && php artisan config:clear && php artisan route:clear && php artisan view:clear

**Comment by dreamer9999** [comment]
原因が分からないので、サイトを削除して、はじめからインストールし直しました。
インストールしてからすぐに、新着情報を設定してみました。
同じエラーが出ました。
それで、もう一度、はじめからインストールし直しました。
インストールしてからすぐに、新着情報を設定してみました。
同じエラーが出ました。
２回、同じエラーが出たので、ひょっとしたら、最新版をインストールして使用すると、何故か、新着情報のエラーが出るようになってしまっている？可能性があるのかなあ、、と感じた次第です。
（私のインストールの仕方が悪いのが原因なら、ただのお騒がせになってしまいますが、、その時は、本当にスイマセン）

![6 1新着情報エラー](https://user-images.githubusercontent.com/3895089/120317580-c4e6f080-c319-11eb-9ae3-d322113fa025.png)

**Comment by kousei86** [comment]
@dreamer9999 様

そうですか、失礼しました。
改めてインストールしなおしても、私のところではこの問題は発生しません。
（サクラレンタルサーバー： Apache/2.4.46 ）

ならば、と思いつきで申し訳ないのですが、
以下を試してもらえませんか。

１．図でお示しの「　 /（略）/app/Plugins/User/Bbses/BbsesPlugin.php 　」を開き、
　　621行目の「　 'thread_caption'   => $request->thread_caption], 　」の最後についてる「 **,** 」カンマを消す。
２．上書き保存をする
３．エラーの有無を確かめる

（ → もし変わらないようでしたら、半角カンマを戻しておいて下さい ）

**Comment by dreamer9999** [comment]
直りました！
621行目の「 , 」カンマを消すと、その後２回のエラーが出たので、同様に、
667行目の「 , 」　と　682行目の「 , 」カンマを消すとエラーが消えました。
このサイトだけの現象みたいです。
php.iniのmax_execution_time を変更したのが影響している？
何が原因なのでしょうか、、、

**Comment by kousei86** [comment]
以下の記事を見つけました。

・PHP7.2 を使っていると引数末端のカンマを許容しない
・PHP7.3以上で引数末端のカンマを許容する
（ 参考： https://qiita.com/K-Shuuun/items/c48292cd4186a2c1c8fd ）
（ 参考： https://www.javaer101.com/ja/article/23700875.html ）

・ColorfulBoxのPHP初期値設定は7.2 （2019年4月17日時点）
（ 参考： https://www.colorfulbox.jp/info/detail/?id=35 ）

－－－
もしかすると、お使いのPHP7.2なのかもしれません。
私のところはPHP7.4を使っていました。
（なお、さくらのレンタルサーバーでは既にPHP7.2は選択できなくなっており、エラーを確かめてはいません）

**Comment by dreamer9999** [comment]
kousei86様、素晴らしいデス！
全て、おっしゃるとおりです。
ColorfulBoxのPHP初期値設定が7.2のままで、7.4に変えたら、正常に動きました！
いつも、感謝しかありません。
今回も、本当に、ありがとうございました。

※そういえば、connect-cmsのインストールマニュアルで必要条件として、php7.2以上、と記載されているので、php7.3以上と記載を変更したほうがいいのかもしれませんね、
[https://github.com/opensource-workshop/connect-cms/wiki/Install-%28インストール%29](https://github.com/opensource-workshop/connect-cms/wiki/Install-%28インストール%29)

**Comment by nagasheep** [comment]
こんにちは。
永原です。

皆様、情報及び検証をありがとうございます。
PHP の必要バージョン記述については、社内でも確認します。

PHP7.2 はPHP 公式では、サポートは終了していますしね。
https://www.php.net/supported-versions.php

**Comment by nagasheep** [comment]
インストール要件のPHPバージョンを7.3 以上と記載させていただきました。
https://github.com/opensource-workshop/connect-cms/wiki/Install-%28%E3%82%A4%E3%83%B3%E3%82%B9%E3%83%88%E3%83%BC%E3%83%AB%29

報告させていただきます。
ありがとうございました。

このIssue もClose させていただきます。
