### ISSUE TITLE
課題管理の使い方

### ISSUE THREAD

**Issue by kousei86** [opensource-workshop/connect-cms#895]
「どのように表現したらうまく伝わるかも分からないぐらい」によく分かっていないのですが、
課題管理プラグインについて「用意された個々の機能の意図」と「課題管理で想定される使い方の全体像」との関連を
**統合的に把握できない**ために、設定で困惑し、課題をスタートできない状態にあります。

「課題提示と受け取りについて利用する側（＝とりあえず教員）がもっている認識（＝スキーマ）」と
「Connect-CMS側に表示される文字と挙動」が合わないためだと思います。
（なので、操作手順をスクリーンキャプチャー付きで丁寧に説明してくれたら分かるというものでは**なさそう**）

操作中の思考を以下に示します。

－－－－

**（１）プラグイン追加から「新規作成」**
・「明日までの復習（2桁の足し算）」のような具体的な課題（宿題）を念頭に置いて設定を始めるため、
　【基本設定】の「表示件数」という項目にまず困惑する

　 「件数とは、１つのテスト内の問題数のこと？
　 　それとも、ブログやフォームのようなページネーションに関わる件数のこと？」
　　（→ これを確かめるほど、操作を進められていません）
　　（→ そして、この時点で既に開発側の想定を外しているような気がしてなりません）

**（２）レポート設定**
・レポート提出機能：「提出、評価、教員からの参考資料」　（？？？ 選択したら何が起こるのかが分からない）　
・提出～表示方法：　よく分かる。安心する。「この算数の課題についてメールを使う気はないから、『メール送信』にチェックは付けない」

**（３）試験設定**
・試験設定？　（上のレポート設定と違うの？）
・レポート試験機能：「提出、評価、教員からの参考資料」　（？？？  試験だから教員からの評価とフィードバックのことか？「提出」のチェックは何だろう？）
・提出～表示方法：　分かる気がする。「この算数の課題についてメールを使う気はないから、『メール送信』にチェックは付けない」「そうすると上の『レポート設定』は何だったのだろう？ よく分からないけど、先に進めよう」

**（４）総合評価設定**
・「総合評価なのだから、複数の課題の合計値みたいな扱いになるのだろう。ということは、もしかしてこの１つの課題設定の中に（時期の異なる）複数のテストを作るのか？　明日までの宿題を１つ置くという使い方はしないの？」
・総合評価コメント：　分かる。ただし、１つの宿題程度に総合評価の欄が付いていることに困惑する。
　→ もしかして課題管理プラグインは「学級ごとに課題を１つ作り、それを学期を通していろんなテストに使い回しするもの」なのか？

**（５）課題管理の［登録］ボタン → 個々の課題の［新規登録］**
・タイトル、問題文、登録日時、カテゴリ：　すごくよく分かる。（SEQは分からないけど、重要じゃないだろう）

－－－

**（６）受講者を選んで下さい**
・評価する受講生が何のことか分からず、「メンバーシップ」であることに気づくまでしばらく探す（公式ページにあった）
・グループ管理で「５年N組」を作って、メンバーを登録する。課題プラグインを置いたページを「メンバーシップ」に変更する
・課題のページに行くと「403権限がない」と表示される（システム管理者なのに？）
　→ 実はグループ登録だけでなく、さらに「コンテンツ管理者」～「ゲスト」などのチェックを入れる必要がある
・教員（課題提出者）の発想だと、ここは編集権限でなく学生（グループ構成者）の名前になるべき。認識が合わない。
　
　
**ここで挫折。「どのように使うべきか」についての全体イメージが分かりません。**
　
（いちおう、Moodleとか、Google Classroomとか、いくつかの一般的なLMSを使った経験はあります）

**Comment by kousei86** [comment]
図を拝見すると（ https://connect-cms.jp/manual/user/learningtasks#frame-93 ）、
「課題」の一番外の設定（→ 課題管理の歯車マークを押した時のもの）に対する理解の枠組みが
私と異なるのだろうなぁ、と思います。
　
現在、私は【課題】を「単なるeラーニングによくあるテスト機能」だと捉えています。
ですから、「中間試験」や「期末試験」「今日の感想」のような大枠を作り、
その中に「個々の設問（問１、問２、問３･･･）」を作っていくものだと考えて対峙しています。
（→ 基本的に学生の提出は１回だけ。あるいは上書きした最終版だけが重要で、先生はその１つを見る）
　
しかし、もしかして Connect-CMSでは【課題】を
「単なるテスト機能ではなく、『成長が必要な達成すべき目標としての課題』を提示し、
　学生が練習過程であるレポートに何度も何度も取り組むうちに成長して
　もう『目標としての課題』をクリアできると自分が思ったときに、
　それをクリアできることを証明するために【試験】を受ける」
というような学習過程を組み込んだものとして捉えているのかもしれません。
　
これぐらい捉え方が違うと、システムの設定の意図がかみ合わず、
意味が分からなくなるのも納得できます。

となれば、この教育思想が正しく利用者に伝わらないと
「課題管理」プラグインを上手に使いこなせないと思われます。
　
システムの使い方の齟齬をなくすためにも、
この点の設計思想を教えていただけないでしょうか？

**Comment by akagane99** [comment]
> （２）レポート設定
・レポート提出機能：「提出、評価、教員からの参考資料」　（？？？ 選択したら何が起こるのかが分からない）　

・これが機能を使うチェックになってます。
　んで下の項目で、詳細を設定する感じです。

・確か、レポート提出機能：「提出」は、レポート提出機能自体を使うかどうか、の設定にもなっていたと思います。

![image](https://user-images.githubusercontent.com/2756509/121593927-63d8be80-ca77-11eb-866f-dfa15c3217f7.png)

解りずらいですね💦

**Comment by kousei86** [comment]
設計思想の説明について、承知しました。
私が理解するための説明としては十分です。

ちなみに、何の説明もなく「大学のレポート試験テスト機能」と言えば、
教員が自然と思う浮かべるのは「単なるeラーニングによくあるテスト機能」です。
要するに、各学生が１回、自分のファイルを送信するもの。
アンケート機能にファイル添付できれば、それだけでも十分です。

そして、いま実装中の【課題管理】は使い方の説明なしでは伝わらない、
課題内容と順序性に意味をもたせた学習プログラムを発生させるものと言えます。
明確に「学習中心の独学・履修状況マネジメント機能」と認識した上で使わないと、
全く使えない機能だと印象づけてしまいます。

教育者主導のレポート機能（課題を出して、ファイルを回収する。評価する）と、
学習者主導の学習報告機能（←適当な名前： やりたいときにやりたいところまでやってフィードバックをもらう）のは、
全く設計や思想が異なります。
これを知っていれば、「課題管理」プラグインをうまく使える人も出てくると思います。

とてもよく理解しました。
ありがとうございます。

個人的には、機能の中に「全体の到達目標」、途中段階の「個々の細分化された到達目標」が見えるかたちで
学習者に伝わるようになっていると、さらに効果が高まると思いました。

**Comment by akagane99** [comment]
ご意見参考になります。
課題管理もまだまだなんで、今後の課題として覚えておきます。

正直、機能改善はできるけど、どうあるべきなのの全然正解が見えてないので、手探り状態です💦
皆さんの意見や、お客さんの意見聞きながら考えて行きたいと思います。

> そして、いま実装中の【課題管理】は、「課題内容と順序性に意味をもたせた学習プログラムを発生させるもの」と言えます。（残念ながら、使い方の説明なしでは教員にも伝わらない）
したがって、明確に「学習中心の独学・履修状況マネジメント機能」だと認識させないと、「全く使えない機能」だと印象づけてしまいがちです。

下記感じましたが、まだ全然整理できてはないです💦

・「課題管理」のプラグイン名から変えた方が良さそうな感じがする。（簡潔で適当は名前が思い浮かばないなぁ）
　課題管理では伝わらないだろうなぁ。
・「課題管理」とは別に「単なるeラーニングによくあるテスト機能」プラグインがあった方がいいのかなぁ。
　名前はeラーニングプラグインとかテストプラグインとかなぁ。
　それとも「課題管理」にまとめるのがいいのかなぁ。

公式サイトの機能一覧をみると、「課題管理」とは別に「レポート」もありました。
https://connect-cms.jp/manual/function
> レポート | 教員が設定したレポート課題に学生・生徒が提出できる機能

まんま課題管理の事のような気がしたので、今度社内確認しときます。


今回の勉強会で課題管理をとりあえげるので、よければご参加ください。
ご意見聞いてみたいです。
https://connect-cms.jp/plugin/databases/detail/96/216/87#frame-216

**Comment by kousei86** [comment]
私の個人的な印象に過ぎないのですが、と念を押した上で
気を悪くさせてしまう可能性の高い見解をひとつ申し上げます。
既に検討済みかもしれませんが、論点のひとつとして受け取っていただければ幸いです。
　
－－－
学校ホームページの作成支援として、
簡単に操作可能なConnect-CMSはかなり便利に使っていただけると思います。

しかし、授業運営の支援として、「メンバーシップ」での履修者制限、
「固定記事」による多くの教材の記述／ファイルアップロード、
「レポート」「テスト」による提出物/回答の回収、「課題管理」による進捗管理の利用、などは
教員にとってかなり煩雑な作業になると思われます。
　
そのため、学校ホームページ自体はConnect-CMSで構築して構わないのですが、
教室内外での授業運営の支援を提供するなら「 Google Workspace for Education 」の導入を勧めます。
LMS機能である「Google Classroom」ほか、なんといっても「全部入り」ですから。
　
もちろん、学校によっては導入自体が難しい場合もありますし、ネット環境や端末環境によっては
二の足を踏む場合もありますので「絶対に」とは言えません。
それでも、クラス何十人、全校何百人の児童/生徒への登録や回答集約、保護者への連絡なども含め、
かなり効率化を図れると思います。

ですので、学校組織に対してはConnect-CMSでホームページを構築しつつ、
Google Workspace for Education の導入で授業運営を助けるというのも、
想定可能なサービスの在り方かと思ったりもします。
（参画条件などは調べもせず、勝手な言い分でございます）

**Comment by kousei86** [comment]
なお、学校ではなくても、一般向けのeラーニングや社内研修などで
【課題管理】的なことをしたい場合も予想されます。
（以下がお返事の流れを受けたものです）

プラグインの名前について、私はなんとなく次のような印象を持ちます。

－－－－－－－－－－－－－－－－－－－－－
テスト　　・・・　○×、選択肢、単語、一文、文章を入力し、正誤判定ができるような課題。（可能なら自動採点）
レポート　・・・　ファイルをアップロードする提出形式の課題
レッスン　・・・ 「資料提示や学習活動（→ インプットとアプトプット）」の順序が連動しており、１つのeラーニングとしてまとめられているもの（→ 無理矢理な感じがしますが、【課題管理】を言い換えるなら）
－－－－－－－－－－－－－－－－－－－－－
　↑ ただし、いずれも「回答者ごとの提出/得点一覧」機能は必須
－－－－－－－－－－－－－－－－－－－－－
　
多くの教員は、授業の後の確認や宿題として
上の「テスト」「レポート」は単独で使いたい機能だと予想します。
（「フォーム」を流用すればいいだけかもしれない）

レッスン（今の【課題管理】）は「大きな到達目標（最終課題）と細分化された到達目標（途中の課題）」、
あるいは「定期的な課題」が最初から明確にスケジュールされている場合に有用かなぁ、といった印象です。
（まだ使い様をよく理解していません）

**Comment by akagane99** [comment]
Google Workspace for EducationやGoogle Classroomは、他社サービスになりますので、意見を言う立場にないのでなんともなんですが、
便利なサービスやツールはConnect-CMSでなくとも沢山ありますので、それがいい。というのであればそちらを使うのが良いかと個人的に思います。
便利に使ってこそのツール（道具）ですので。

とはいえConnect-CMSの作り手ですから、せっかく作るなら便利に使えるように作りたいものです^^

> プラグインの名前について、私はなんとなく次のような印象を持ちます。（定義ではありません）
> 
> －－－－－－－－－－－－－－－－－－－－－－－－－－－
テスト　　・・・　○×、選択肢、単語、一文、文章を入力し、正誤判定ができるような課題。（可能なら自動採点）
レポート　・・・　ファイルをアップロードする提出形式の課題
レッスン　・・・ 「資料提示と学習活動（→ インプットとアプトプット）」が順序性をもって配置されており、１つのeラーニングとしてまとめられているもの（→ 無理矢理な感じがしますが、【課題管理】を言い換えるならこれ）
－－－－－－－－－－－－－－－－－－－－－－－－－－－
　↑ いずれも「回答者ごとの提出/得点一覧」機能は必須
－－－－－－－－－－－－－－－－－－－－－－－－－－－

上記ありがとうございました。
おっしゃる通りテスト系プラグインとして、上記３つの機能に集約されると思います。
課題管理とテスト系プラグインの整理に役立ちそうです。

今後の開発の参考にさせてもらいます。
ありがとうございました。

**Comment by kousei86** [comment]
「セットアップ」の導入と公式マニュアルの更新により、「課題の出題から、レポート回答の受け取り、レポートの評価と評定、試験のエントリー、試験の実施、試験回答の評価と評定、総合評価まで」の一連の操作が実施できるようになりました。
ありがとうございます。
　
「ん～～～～」とうなるところですが、
どのように使えそうかをしばらく考えてみます。
　
要するに、この機能は「**同じ問題に対し、合格になるまで何度もレポート提出をやり直すタイプの学習活動を発生させる仕組み**」であると理解しました。
　
　
－－－－－－－－－－－－－－－
【疑問２件】
　
・「レポート設定」で「使用項目の設定」を［使用しない］にするなら、「試験」の申し込みができない？
　（ → この状況に該当する選択肢が［試験設定］の中の［申し込み設定］にないように見えます）
　つまりは、練習問題や宿題として使いたい場合は「レポート」だけを使えばいいのですね。
　
　
【まだ不完全な「使い様」の理解に向けて】
・課題を出すのが「役割：教員」ではなく「役割：事務局」であるのは、学校・大学の授業というより、
　（事務局が問題を集積している）資格試験における自主勉強のような使い方が主に想定されているからなのでしょうか？
　
　（ → あるいは「指導員（＝先生）と試験の出題者が同じだと公平な能力評価にならない」という誠実な審査態度が組み込まれているのかもしれません）

**Comment by akagane99** [comment]
> 要するに、この機能は「同じ問題に対し、合格になるまで何度もレポート提出をやり直すタイプの学習活動を発生させる仕組み」であると理解しました。

はい、そのとおりです^ ^

> 【疑問２件】
> 　
> ・「レポート設定」で「使用項目の設定」を［使用しない］にするなら、「試験」の申し込みができない？

あ、言われてみると、その通りですね。
試験のどの条件もレポートを前提にしてるため、そうなってました。

> 【まだ不完全な「使い様」の理解に向けて】
> 
> ・課題を出すのが「役割：教員」ではなく「役割：事務局」であるのは、学校・大学の授業というより、
> 
> 　（事務局が問題を集積している）資格試験における自主勉強のような使い方が主に想定されているからなのでしょうか？

はい、お察しの通り、確か教員免許か何かの資格試験で利用してるお客様いて、そちらの仕組みを実装してます。

ご参考まで。

**Comment by kousei86** [comment]
ありがとうございます。

「課題管理」とは「そういうもので、こういう使い方をする」という一定の枠組みを獲得しました。
検討いたします。
