### ISSUE TITLE
【メール】キューキック

### ISSUE THREAD

**Issue by akagane99** [opensource-workshop/connect-cms#905]
現在のメール送信は、即時送信のみです。
Laravelのメールキューに溜めてから、別途送信できるように対応したい。

## 参考URL
* [キュー 6.x Laravel](https://readouble.com/laravel/6.x/ja/queues.html)
* [Laravel Queueを利用して非同期によるメール送信](https://noumenon-th.net/programming/2020/06/02/laravel-queue/)

**Comment by akagane99** [comment]
## 調査

キューテーブルを作成するコマンドを実行したところ、下記エラーが発生。
`CreateJobsTable`クラスが既に存在している、との事。

下記にあった。
https://github.com/opensource-workshop/connect-cms/blob/master/database/migrations/2021_01_30_130730_create_jobs_table.php
https://github.com/opensource-workshop/connect-cms/blob/master/database/migrations/2021_01_30_130739_create_failed_jobs_table.php

作業途中か不明のため、要確認。


```
>php artisan queue:table

   InvalidArgumentException  : A CreateJobsTable class already exists.

  at C:\projects\connect-cms\htdocs\connect-cms\vendor\laravel\framework\src\Illuminate\Database\Migrations\MigrationCreator.php:90
    86|             }
    87|         }
    88| 
    89|         if (class_exists($className = $this->getClassName($name))) {
  > 90|             throw new InvalidArgumentException("A {$className} class already exists.");
    91|         }
    92|     }
    93| 
    94|     /**

  Exception trace:

  1   Illuminate\Database\Migrations\MigrationCreator::ensureMigrationDoesntAlreadyExist("create_jobs_table", "C:\projects\connect-cms\htdocs\connect-cms\database/migrations")
      C:\projects\connect-cms\htdocs\connect-cms\vendor\laravel\framework\src\Illuminate\Database\Migrations\MigrationCreator.php:50

  2   Illuminate\Database\Migrations\MigrationCreator::create("create_jobs_table", "C:\projects\connect-cms\htdocs\connect-cms\database/migrations")
      C:\projects\connect-cms\htdocs\connect-cms\vendor\laravel\framework\src\Illuminate\Queue\Console\TableCommand.php:80

  Please use the argument -v to see more details.

```

**Comment by akagane99** [comment]
## 調査2

[キュー 6.x Laravel](https://readouble.com/laravel/6.x/ja/queues.html)

**Comment by akagane99** [comment]
## 追加調査・対応メモ

### １．Jobのリトライさせない = `$tries = 1`にする。
 https://readouble.com/laravel/6.x/ja/queues.html#max-job-attempts-and-timeout
```php
<?php

namespace App\Jobs;

class ProcessPodcast implements ShouldQueue
{
    /**
     * 最大試行回数
     *
     * @var int
     */
    public $tries = 1;
}
```

### ２．2重起動時の問題検証
https://github.com/opensource-workshop/connect-cms/pull/925#issuecomment-875211029

**Comment by akagane99** [comment]
## 再調査

\Symfony\Component\Process\Process を使って非同期処理。
現在のバージョンは、Laravelの依存で、[v4.4.22](https://github.com/opensource-workshop/connect-cms/blob/master/composer.lock#L4527-L4528) だった。

**Comment by akagane99** [comment]
# 2重起動時の問題検証

問題なしでした。

## 詳細

### キュー１をキューワーカAが処理中に、キューワーカBが起動した場合

結果
・キューワーカBでキュー１は処理されない。
・databaseキューの処理は、`attempts` `reserved_at` で管理されてそう。
　・未処理キュー：`attempts`=0,  `reserved_at`=null
　・処理中キュー：`attempts`=1,  `reserved_at`=1625816xxxx ←多分時間のint

 id | queue | payload | attempts | reserved_at | available_at | created_at
-- | -- | -- | -- | -- | -- | --
 24 | default | {"displayName":"App\\Jobs\\PostNoticeJob","job":"I... | 0 | NULL | 1625816897 | 1625816897

**Comment by akagane99** [comment]
## ２つのキューワーカA、Bが常駐してる時に、キュー１がきた場合

* 後に起動したキューワーカBで、キュー１が処理される。
* キューワーカAは何もしない。

⇒ 問題なし。

## ２つのキュー１、２があり、１つ目で失敗した場合

タイムアウトを20秒、Jobで`sleep(30);`を入れてテスト。

タイムアウト２０秒
```php
$php_artisan_command = "{$php} \"{$artisan}\" queue:work --stop-when-empty --timeout=20";
```

・結果、キュー１で失敗⇒ 失敗したキューは failed_jobs に入りました。
・キュー２は処理しませんでした。
・失敗してもログに出力なし。

### failed_jobsテーブル

キュー１
 id | connection | queue | payload | exception | failed_at
 -- | -- | -- | -- | -- | --
 1 | database | default | {"displayName":"App\\Jobs\\PostNoticeJob","job":"I... | Illuminate\Queue\MaxAttemptsExceededException: App... | 2021-07-09 17:45:38

コマンドで確認
```
$ php artisan queue:failed
+----+------------+---------+------------------------+---------------------+
| ID | Connection | Queue   | Class                  | Failed At           |
+----+------------+---------+------------------------+---------------------+
| 1  | database   | default | App\Jobs\PostNoticeJob | 2021-07-09 17:45:38 |
+----+------------+---------+------------------------+---------------------+
```

### jobsテーブル

キュー２
 id | queue | payload | attempts | reserved_at | available_at | created_at
 -- | -- | -- | -- | -- | -- | --
25 | default | {"displayName":"App\\Jobs\\PostNoticeJob","job":"I... | 0 | NULL | 1625820318 | 1625820318

**Comment by akagane99** [comment]
キューのguiは必要かなぁ？
こんなんあった。

【Laravel】データベースキューを GUI で監視するためのライブラリ Laravel-Queue-Monitor の紹介
https://cpoint-lab.co.jp/article/202106/20419/

laravel6 も対応してそう。
https://github.com/romanzipp/Laravel-Queue-Monitor/blob/master/composer.json#L17

ルーティングは/manage/jobs/ に変更して別ウィンドウ表示とかかなぁ。
https://github.com/romanzipp/Laravel-Queue-Monitor#routes

**Comment by masaton0216** [comment]
デバッグの初動調査が早くなりそうですしアリかと思います。

**Comment by akagane99** [comment]
サンキュー。月曜にでも試し実装してみる

**Comment by akagane99** [comment]
QUEUE_CONNECTION=sync もどす。.env

**Comment by akagane99** [comment]
対応しました。

## 概要


・キューをセット後に非同期でキューワーカを実行します。
・キューワーカは、キューされたすべてのジョブを実行後に、プロセス停止します。

【利点】
⇒ キューワーカが必要な時だけ非同期実行して、実行終わったら停止してもらう（キューワーカを常駐させない）
⇒⇒ これによって、キューワーカのcronでの実行不要、アプリケーション変更時のキューワーカのリスタート不要になります。

※ キューのメールJobは自動リトライしません。
　（大量メール送信時の途中停止を想定して、自動リトライしない設定にしました。自動リトライすると初めの方に送った人に同じメールが飛ぶため）
※ キューワーカのタイムアウトは１時間に設定。
　（非同期実行で投げっぱなしのため、万が一プロセルが動きつづけても１時間で強制停止します。１時間もかかるメール処理はないだろう想定。）
※ キューワーカのリトライ時間を１時間１分に設定（config\queue.php）
　（タイムアウト前にリトライ時間がくるとエラーが出るため。タイムアウトよりも後の時間に設定。）
　（config\queue.php の [connections => [database => [retry_after]]](リトライ時間) ）

・メールの「送信方式」は削除して１本化。
　・.envの設定で「即時送信」か「スケジュール送信」を切り替えられる事がわかったため。
　　・.envのQUEUE_CONNECTION=sync は「即時送信」
　　・.envのQUEUE_CONNECTION=databaseは「スケジュール（バックグラウンド）送信」
　
参考：メールの「送信方式」
![124560714-14b85a80-de78-11eb-8977-e8671f10d07b](https://user-images.githubusercontent.com/2756509/125049019-7a585100-e0db-11eb-9044-9d75c7c51357.png)


### 要設定変更：キュードライバを database に変更する。

.env
```.env
###QUEUE_CONNECTION=sync
QUEUE_CONNECTION=database
```

### ※ 以下は既に対応済み

* DBテーブルは既に追加済み
  * キューテーブル [database/migrations/2021_01_30_130730_create_jobs_table.php](https://github.com/opensource-workshop/connect-cms/blob/master/database/migrations/2021_01_30_130730_create_jobs_table.php)
  * 失敗キューテーブル [database/migrations/2021_01_30_130739_create_failed_jobs_table.php](https://github.com/opensource-workshop/connect-cms/blob/master/database/migrations/2021_01_30_130739_create_failed_jobs_table.php)
* jobクラス
  * 既に [app/Jobs](https://github.com/opensource-workshop/connect-cms/tree/master/app/Jobs) 配下にあり。
  * dispatchNowメソッドで既に動かしていました。

### ※ キューは2重起動するのか動作検証

https://github.com/opensource-workshop/connect-cms/issues/905#issuecomment-876994341

## 修正後画面

### メール設定「送信方式」がなくなりました。

![image](https://user-images.githubusercontent.com/2756509/125050219-be982100-e0dc-11eb-9784-aa68663b6213.png)

**Comment by akagane99** [comment]
https://github.com/opensource-workshop/connect-cms/issues/905#issuecomment-877034070

##  キューワーカのテスト前提

* Linuxでテストする。
  * ※ windows ではタイムアウトが機能しない
* pcntl PHP extensionをインストールする。
  * ※ ないとタイムアウト機能しない 

## 詳細：windows ではタイムアウトが機能しない
* windowsではキューワーカ―のタイムアウトは設定してもタイムアウトしない事がわかった。
  * https://readouble.com/laravel/6.x/ja/queues.html#time-based-attempts
> Note: The timeout feature is optimized for PHP 7.1+ and the pcntl PHP extension. (pcntl のphpエクステンション必要)
  * pcntl PHP extension
https://www.php.net/manual/ja/pcntl.installation.php
> 現在、このモジュールは非 Unix 環境(Windows)では動作しません。
