### ISSUE TITLE
インストールでエラーがでます。

### ISSUE THREAD

**Issue by zanjibar** [opensource-workshop/connect-cms#909]
docker 作成中ですが、結構つまっています。

インストールにしたがって、
php artisan key:generate
をすると、下記のエラーがでます。github の source には vendor のディレクトリがないみたいです。どこでつくられるのでしょうか？

```
Fatal error: require(): Failed opening required '/var/www/html/connect-cms/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/html/connect-cms/artisan on line 18
```
composer 自体ははいっているようです。
Download the library using composer(composerで利用ライブラリのダウンロード)ではなく、
Dockerfile で、composer を導入しています。

```
Composer - Dependency Manager for PHP - version 2.1.3
Composer is a dependency manager tracking local dependencies of your projects and libraries.
See https://getcomposer.org/ for more information.
```

**Comment by akagane99** [comment]
composer installコマンドを実行すれば、ディレクトリできると思いますよ。

**Comment by zanjibar** [comment]
手動ですが、できました。ただ、docker-compose なんで、自動化できないのかなと試しています。。。
