### ISSUE TITLE
【フレーム】ログインすると、非公開設定＆限定公開フレームが見えてしまう

### ISSUE THREAD

**Issue by osws-makino** [opensource-workshop/connect-cms#915]
## 概要
ログインすると、非公開設定＆限定公開フレームが見えてしまう

## 再現手順
・「固定記事」等のフレームにて、非公開、もしくは限定公開に設定する
・未ログイン状態だと見えない事を確認
・ログインすると、当該ユーザーが何の権限もなくても、非表示設定されたフレームも見えてしまう

## 原因
フレームを表示するか否かの判定の部分に、権限による制限がない為

**Comment by akagane99** [comment]
@osws-makino これ直ってたらクローズお願い
