### ISSUE TITLE
ログイン画面がでません。Docker 作成中

### ISSUE THREAD

**Issue by zanjibar** [opensource-workshop/connect-cms#916]
Docker なかなか苦労しています。ログイン画面が、エラーになります。

connect-cms 用のデータベースは作成できており、データもはいっています。

エラーを見るのにどのログをみるがのいいでしょうか？

![image](https://user-images.githubusercontent.com/1680694/122867602-bada6f80-d364-11eb-8d9e-05cbaa0272fe.png)

![image](https://user-images.githubusercontent.com/1680694/122867681-d9d90180-d364-11eb-94e0-fb0d38f30f55.png)

**Comment by nagasheep** [comment]
Dockerはわからないんですけど、Apache のエラーですね。
・mod_rewrite は有効になってます？
・ドキュメントルートはconnect-cms\public に設定しています？

**Comment by akagane99** [comment]
apacheエラーなので、Connect-CMS側ではエラーでてないかもですが、
Connect-CMS側のログは下記です。

storage\logs\laravel-2021-06-22.log

**Comment by zanjibar** [comment]
ありがとうございます。apache は、超ひさしぶりなんで、忘れていました。
とりあえず、でるようになりました。
![image](https://user-images.githubusercontent.com/1680694/122872149-fd06af80-d36a-11eb-9e6f-e40fbaf2c1ce.png)
