### ISSUE TITLE
【初回メッセージ管理】最新版で本機能を使用するとシステムエラー

### ISSUE THREAD

**Issue by masaton0216** [opensource-workshop/connect-cms#918]
## 概要
- 手持ちクライアントサイトで最新版にアップデートしたところ、TOPページ表示でシステムエラー
- エラーログから「in_array() expects parameter 2 to be array, string given」とあり＠app.blade.php
	- どうも第二引数にstring型が来ている模様
- 発生個所はおそらく下記
	- https://github.com/opensource-workshop/connect-cms/blob/master/resources/views/layouts/app.blade.php#L464
- 発生個所を含む一連の処理の行を削除することで復旧を確認
	- https://github.com/opensource-workshop/connect-cms/blob/master/resources/views/layouts/app.blade.php#L464-L499

## スクリーンショット
![無題](https://user-images.githubusercontent.com/13323806/123271096-748b3900-d53b-11eb-95f3-78c3054e701a.png)

**Comment by masaton0216** [comment]
- 原因：過去の設定取得方式の変更時のデグレ
- 対応済み
https://github.com/opensource-workshop/connect-cms/commit/27f90d3d6ed8ad5189b518be99697cd208e2d77b

**Comment by akagane99** [comment]
デグレごめん🙏
