### ISSUE TITLE
「HTML記述制限」された者がアップロードした画像にレスポンシブ設定が付かない

### ISSUE THREAD

**Issue by kousei86** [opensource-workshop/connect-cms#919]
「掲示板」に横幅の大きな画像をアップロードした際、
レスポンシブについて以下のようになりました。

　○ システム管理者だと、
 　　画像の設定で［クラス　responsive］を選ぶと「class="img-fluid"」が付いて枠内に収まる

　× 編集権限だけのユーザーだと、
　　画像の設定で［クラス　responsive］を選んでも「**class="img-fluid"**」**が付かずに枠外にはみ出す**

－－

「掲示板」の投稿にJavaScript制限を設けてからだと思いますが、
できれば一般ユーザーがアップロードした画像も枠内に納まるようにしていただきたく思います。

**Comment by akagane99** [comment]
ご連絡ありがとうございました。

>　× 編集権限だけのユーザーだと、
>　　画像の設定で［クラス　responsive］を選んでも「class="img-fluid"」が付かずに枠外にはみ出す

・編集権限でも「class="img-fluid"」を消さないようにプログラムしていましたが、そこバグってclassが消えていましたので、修正しました。
・Connect-CMS公式サイトにも、さきほど修正を反映して、編集権限で「class="img-fluid"」が消えない事を確認しました。

## 修正プログラム

https://github.com/opensource-workshop/connect-cms/commit/15a6bb247e0e0403ec7fe36ad5631e190440da6d

クローズさせて頂きます。
