### ISSUE TITLE
【ページ管理】ルートURL（HOME）を移動先として指定するとシステムエラー

### ISSUE THREAD

**Issue by masaton0216** [opensource-workshop/connect-cms#921]
## 概要
ルートURL（HOME）を移動先として指定するとシステムエラー

## 再現手順
1. ページ管理開く
2. ページ一覧上でHOME以外の任意ページの移動先をHOMEに指定する

## スクリーンショット
![image](https://user-images.githubusercontent.com/13323806/123726098-52424400-d8ca-11eb-90fa-b626470c5caa.png)
![image](https://user-images.githubusercontent.com/13323806/123726143-66864100-d8ca-11eb-813a-49a6ab7d64c0.png)

**Comment by masaton0216** [comment]
### メモ
- 下記の手前にバリデーションを設置（移動先の_lgt、_rgtが0,0（入れ子集合上の最上位ノード）なら弾く）すればよいのかなと考えてますが、入れ子集合をあまり理解できてないので一旦メモ書きレベル
https://github.com/opensource-workshop/connect-cms/blob/master/app/Plugins/Manage/PageManage/PageManage.php#L296

**Comment by akagane99** [comment]
重複issue
https://github.com/opensource-workshop/connect-cms/issues/187

**Comment by masaton0216** [comment]
https://github.com/opensource-workshop/connect-cms/issues/187 で解消済み
