### ISSUE TITLE
ヘッダー右にあるメニューを開く操作はクリックの方がベター？

### ISSUE THREAD

**Issue by gakigaki** [opensource-workshop/connect-cms#935]
ヘッダー右の管理機能やユーザメニュー（画像赤枠部）を開く操作は、クリックかマウスオーバーどちらがよいでしょうか？
![image](https://user-images.githubusercontent.com/32890286/126262854-56f33c47-2768-47eb-8fd8-bf843ad4672b.png)

現在のConnect-CMSはマウスオーバーで開くようになっています。
ただ、一般的なUIではクリックで開くと考えています。
例を挙げると、Github、Jira、Backlogなどの有名なサービスではクリックです。

そのため、クリックに変更したほうが良いかと思うのですが、いかがでしょうか？

**Comment by masaton0216** [comment]
ブラウザウィンドウの右上周辺は諸々の操作（後述）が集中する為、
マウスオーバーで意図せずサイトのアクション（メニューOPEN）が起動してしまうのはUX的に若干ですがハンディを背負ってしまうのではないかなという想いがあります。ということで私はクリック派。
 - 縮小、閉じる等のクリック操作
 - ブラウザ設定やブラウザに入れてる拡張の操作

**Comment by nagasheep** [comment]
しばらく、意識して触ってみました。
結果、永原はクリックに1票です。

オンマウスで反応することで、スピーディーさと1クリックの省略というメリットはあるけれど、反応が良すぎて、意識が追い付かない＆意図した操作（クリック）が意図と違う動きをする（メニューが閉じる）。

この、意図した操作と違う動きをするのはなんでだろうと考えたんだけど、ログイン前の右上のメニューではクリックしているのよね。その操作は学習として、人の中に残っているのだと思う。

以上

**Comment by akagane99** [comment]
マウスオーバーで開かないよう対応しました。
https://github.com/opensource-workshop/connect-cms/commit/4db18bcfb9c66e29a161f44d262cb55ffa71d377

**Comment by gakigaki** [comment]
@akagane99
対応ありがとうございます！
