### ISSUE TITLE
debug用ファイルが残っている？

### ISSUE THREAD

**Issue by akagane99** [opensource-workshop/connect-cms#95]
下記デバッグ用ファイルであれば、githubで管理不要かと思います。
削除した方がいいかと。

https://github.com/opensource-workshop/connect-cms/blob/master/public/info.php
https://github.com/opensource-workshop/connect-cms/blob/master/public/test.html
https://github.com/opensource-workshop/connect-cms/blob/master/public/datepicker.html
https://github.com/opensource-workshop/connect-cms/blob/master/public/datepicker2.html
https://github.com/opensource-workshop/connect-cms/tree/master/public/uploads

開発で作るファイルは/debug/とかディレクトリ作って.gitignoreで除外する方向がいいのかなぁ

**Comment by nagasheep** [comment]
サンキュー。
見直しました。
> 開発で作るファイルは/debug/とかディレクトリ作って.gitignoreで除外する方向
これにしてみました。
