### ISSUE TITLE
Blog の削除で選択したものでなく、表示しているものが削除される。

### ISSUE THREAD

**Issue by nagasheep** [opensource-workshop/connect-cms#96]

**Comment by akagane99** [comment]
・ブログは表示したものしか削除できないため、問題なしでした。クローズします。
※ フォームのようなバケツ選択画面に「設定変更」ボタンはないので、表示ブログ以外を消す手段はなかったです。


## ブログ選択画面
![image](https://user-images.githubusercontent.com/2756509/119243715-647ee300-bba4-11eb-82d2-b2dd430312a8.png)
