### ISSUE TITLE
Blog の削除でBuckets が残るケースがある。

### ISSUE THREAD

**Issue by nagasheep** [opensource-workshop/connect-cms#97]

**Comment by akagane99** [comment]
Buckets が残るケースは不明でした。
ロジック上はbuckets_idを指定しているため、残らないと判断しました。

また、ブログの削除時に消してないテーブル BlogsPostsTags, Categories, BlogsCategories, BucketsRoles があったため削除しました。

## 修正プログラム

https://github.com/opensource-workshop/connect-cms/commit/6f55bf46729bb96ec995863197f72d60a73921e4

**Comment by akagane99** [comment]
問題なしだったので、クローズします。
