### ISSUE TITLE
WYSIWYG でembed のレスポンシブ対応とアスペクト比の指定がしたい。

### ISSUE THREAD

**Issue by nagasheep** [opensource-workshop/connect-cms#976]
## 概要

WYSIWYG でembed のレスポンシブ対応とアスペクト比の指定がしたい。

**Comment by akagane99** [comment]
https://github.com/opensource-workshop/connect-cms/commit/9026c4aa80e5a36cb94e3e444ccfde136d854b85

上記で対応済みのため、クローズします。
