### ISSUE TITLE
画像アップロードのオリジナルTinyMCEプラグイン

### ISSUE THREAD

**Issue by nagasheep** [opensource-workshop/connect-cms#979]
## 概要
- アップロード時に、画像のサイズ指定が簡単に（選択で）できるようにした。
- サイズ（大⇒何ピクセル、など）は初期値はあるけど、管理者機能で設定できるようにしたい。
- TinyMCE 標準のものと、Connect-CMS オリジナルのもの、選択できるようにしたい。両方使える設定もアリかも。チェックボックスで選ぶ？（Connect-CMS オリジナル版ですべての機能をまかなえれば、選択の必要性はないかもしれないけど。画像の編集とかは、どうだろう？）

**Comment by akagane99** [comment]
* https://github.com/opensource-workshop/connect-cms-ideas/issues/74

上記で対応済みのため、こちらはクローズします。
