### ISSUE TITLE
メニューでサイトマップテンプレートを使用時、表示されないパターンあり

### ISSUE THREAD

**Issue by osws-makino** [opensource-workshop/connect-cms#981]
## 概要
メニューが表示されないパターンがある。

## 再現手順
Connect-CMS公式サイトより
https://connect-cms.jp/manual/common/frame-setting
「メニュー」プラグイン

## スクリーンショット
![image](https://user-images.githubusercontent.com/34463938/132473464-1624c69b-1978-4dd6-b1d9-1629f2ef9831.png)

【設定】
![image](https://user-images.githubusercontent.com/34463938/132473570-356310a8-ea00-4100-9814-48ca0c5e1778.png)
![image](https://user-images.githubusercontent.com/34463938/132473647-89206c2d-07e8-4de4-9b60-88138757e69f.png)

**Comment by kousei86** [comment]
第１階層のサブメニュー「フレーム編集」の上にある、親メニュー「共通機能」に表示のチェックは入っているでしょうか？
　
サイトマップ形式によらず、
親メニューが表示されていないと、第１階層・第２階層の子メニュー達は表示されなかったと思います。

**Comment by osws-makino** [comment]
＞子メニュー「フレーム編集」の上にある、親メニュー「共通機能」のチェックボックスはONになっているでしょうか？
なっておりません。チェックを入れれば、確かに表示されました。

このページの階層は、
マニュアル
　共通機能
　　フレーム編集
　　　幅100％設定の例
　　　このページにのみ表示
　　　このページにのみ表示しない
となっております。
「共通機能」のページに配置したメニューでは、親メニューの「マニュアル」にチェックを入れていませんが、問題なく表示されます。
なので、単純に「親にチェックが入っていないから」とは少し違うような気がします。

ちなみに、サイトマップ以外のテンプレートでも発生しました。
実際にチェックして出て来ない事を確認したのは以下です。
・default
・タブ
・親子のみ

**Comment by kousei86** [comment]
メニューの階層を作って検証してところ、私の「親となるメニュー」という言葉が不確かでしたが、
「class="depth-1"」となるメニューがキーになっている印象を受けました。
![メニュー階層検証２](https://user-images.githubusercontent.com/82799412/132607300-a9976e5a-c90d-4bc6-8b52-81fb822dd413.png)

－－－
次の図の上側は「マニュアル＋」－「共通機能」－「フレーム編集」の再現です。
親（＝マニュアル）にチェックはなくても、子（＝共通機能）以下が表示されました。
子（共通機能）にチェックがないと、（孫＝フレーム編集）以下は表示されませんでした。
![メニュー階層検証](https://user-images.githubusercontent.com/82799412/132607637-1674acea-018f-4b3d-a9d2-35d4c85434a9.png)

表示までの仕組みにはたどり着いていませんでしたが、
depth-1（白丸）がキーになっているような気がします。

**Comment by osws-makino** [comment]
なるほど理解！　そしてとても分かりやすい！！
ありがとうございます。
